option('build_shared_libs', type: 'boolean', value: false,
  description: 'Build shared libraries.')
option('build_static_libs', type: 'boolean', value: true,
  description: 'Build static libraries.')
option('pcre2_build_pcre2_8', type: 'boolean', value: true,
  description: 'Build 8 bit PCRE2 library')
option('pcre2_build_pcre2_16', type: 'boolean', value: false,
  description: 'Build 16 bit PCRE2 library')
option('pcre2_build_pcre2_32', type: 'boolean', value: false,
  description: 'Build 32 bit PCRE2 library')
option('pcre2_static_pic', type: 'boolean', value: false,
  description: 'Build the static library with position independent code enabled.')
option('pcre2_debug', type: 'combo', choices: ['IfDebugBuild', 'ON', 'OFF'],
  value: 'IfDebugBuild', description: 'Include debugging code')
option('pcre2_disable_percent_zt', type: 'boolean', value: false,
  description: 'Disable the use of %zu and %td (rarely needed)')
option('pcre2_ebcdic', type: 'boolean', value: false,
  description: 'Use EBCDIC coding instead of ASCII.')
option('pcre2_ebcdic_nl25', type: 'boolean', value: false,
  description: 'Use 0x25 as EBCDIC NL character instead of 0x15; implies EBCDIC.')
option('pcre2_ebcdic_ignoring_compiler', type: 'boolean', value: false,
  description: 'Force EBCDIC 1047 using numeric literals; implies EBCDIC.')
option('pcre2_rebuild_chartables', type: 'boolean', value: false,
  description: 'Rebuild char tables')
option('pcre2_link_size', type: 'combo', choices: ['2', '3', '4'], value: '2',
  description: 'Internal link size.')
option('pcre2_parens_nest_limit', type: 'string', value: '250',
  description: 'Default nested parentheses limit.')
option('pcre2_heap_limit', type: 'string', value: '20000000',
  description: 'Default limit on heap memory (kibibytes).')
option('pcre2_max_varlookbehind', type: 'string', value: '255',
  description: 'Default limit on variable lookbehinds.')
option('pcre2_match_limit', type: 'string', value: '10000000',
  description: 'Default limit on internal looping.')
option('pcre2_match_limit_depth', type: 'string', value: 'MATCH_LIMIT',
  description: 'Default limit on internal depth of search.')
option('pcre2grep_bufsize', type: 'string', value: '20480',
  description: 'Buffer starting size parameter for pcre2grep.')
option('pcre2grep_max_bufsize', type: 'string', value: '1048576',
  description: 'Buffer maximum size parameter for pcre2grep.')
option('pcre2_newline', type: 'combo',
  choices: ['CR', 'LF', 'CRLF', 'ANY', 'ANYCRLF', 'NUL'], value: 'LF',
  description: 'What to recognize as a newline.')
option('pcre2_heap_match_recurse', type: 'boolean', value: false,
  description: 'Obsolete option: do not use')
option('pcre2_support_jit', type: 'combo', choices: ['OFF', 'ON', 'AUTO'],
  value: 'OFF', description: 'Enable support for Just-in-time compiling.')
option('pcre2_support_jit_sealloc', type: 'boolean', value: false,
  description: 'Enable SELinux compatible execmem allocator in JIT (experimental).')
option('pcre2grep_support_jit', type: 'boolean', value: true,
  description: 'Enable use of Just-in-time compiling in pcre2grep.')
option('pcre2grep_support_callout', type: 'boolean', value: true,
  description: 'Enable callout string support in pcre2grep.')
option('pcre2grep_support_callout_fork', type: 'boolean', value: true,
  description: 'Enable callout string fork support in pcre2grep.')
option('pcre2_support_unicode', type: 'boolean', value: true,
  description: 'Enable support for Unicode and UTF encodings.')
option('pcre2_support_bsr_anycrlf', type: 'boolean', value: false,
  description: 'Make backslash-R match only LF, CR and CRLF.')
option('pcre2_never_backslash_c', type: 'boolean', value: false,
  description: 'Lock out backslash-C.')
option('pcre2_support_valgrind', type: 'boolean', value: false,
  description: 'Enable Valgrind support.')
option('pcre2_fuzz_support', type: 'boolean', value: false,
  description: 'Enable fuzzer support')
option('pcre2_diff_fuzz_support', type: 'boolean', value: false,
  description: 'Enable differential fuzzer support (requires fuzz support and JIT)')
option('pcre2_show_report', type: 'boolean', value: true,
  description: 'Show the final configuration report')
option('pcre2_build_pcre2grep', type: 'boolean', value: true,
  description: 'Build pcre2grep')
option('pcre2_build_tests', type: 'boolean', value: true,
  description: 'Build the tests')
option('pcre2_install_cmakedir', type: 'string', value: '',
  description: 'Install path for PCRE2 CMake config files; defaults to libdir/cmake/pcre2.')
option('pcre2_symvers', type: 'boolean', value: true,
  description: 'Enable library symbol versioning')
option('pcre2_support_libbz2', type: 'feature', value: 'auto',
  description: 'Enable support for linking pcre2grep with libbz2.')
option('pcre2_support_libz', type: 'feature', value: 'auto',
  description: 'Enable support for linking pcre2grep with libz.')
option('pcre2_support_libedit', type: 'feature', value: 'disabled',
  description: 'Enable support for linking pcre2test with libedit.')
option('pcre2_support_libreadline', type: 'feature', value: 'auto',
  description: 'Enable support for linking pcre2test with libreadline.')
option('non_standard_lib_prefix', type: 'boolean', value: false,
  description: 'Remove the lib prefix from MinGW shared library names.')
option('non_standard_lib_suffix', type: 'boolean', value: false,
  description: 'Use the legacy -0.dll suffix for MinGW shared libraries.')
