option('BUILD_SHARED_LIBS', type: 'boolean', value: false,
  description: 'Build shared libraries.')
option('BUILD_STATIC_LIBS', type: 'boolean', value: true,
  description: 'Build static libraries.')
option('PCRE2_BUILD_PCRE2_8', type: 'boolean', value: true,
  description: 'Build 8 bit PCRE2 library')
option('PCRE2_BUILD_PCRE2_16', type: 'boolean', value: false,
  description: 'Build 16 bit PCRE2 library')
option('PCRE2_BUILD_PCRE2_32', type: 'boolean', value: false,
  description: 'Build 32 bit PCRE2 library')
option('PCRE2_STATIC_PIC', type: 'boolean', value: false,
  description: 'Build the static library with position independent code enabled.')
option('PCRE2_DEBUG', type: 'combo', choices: ['IfDebugBuild', 'ON', 'OFF'],
  value: 'IfDebugBuild', description: 'Include debugging code')
option('PCRE2_DISABLE_PERCENT_ZT', type: 'boolean', value: false,
  description: 'Disable the use of %zu and %td (rarely needed)')
option('PCRE2_EBCDIC', type: 'boolean', value: false,
  description: 'Use EBCDIC coding instead of ASCII.')
option('PCRE2_EBCDIC_NL25', type: 'boolean', value: false,
  description: 'Use 0x25 as EBCDIC NL character instead of 0x15; implies EBCDIC.')
option('PCRE2_EBCDIC_IGNORING_COMPILER', type: 'boolean', value: false,
  description: 'Force EBCDIC 1047 using numeric literals; implies EBCDIC.')
option('PCRE2_REBUILD_CHARTABLES', type: 'boolean', value: false,
  description: 'Rebuild char tables')
option('PCRE2_LINK_SIZE', type: 'combo', choices: ['2', '3', '4'], value: '2',
  description: 'Internal link size.')
option('PCRE2_PARENS_NEST_LIMIT', type: 'string', value: '250',
  description: 'Default nested parentheses limit.')
option('PCRE2_HEAP_LIMIT', type: 'string', value: '20000000',
  description: 'Default limit on heap memory (kibibytes).')
option('PCRE2_MAX_VARLOOKBEHIND', type: 'string', value: '255',
  description: 'Default limit on variable lookbehinds.')
option('PCRE2_MATCH_LIMIT', type: 'string', value: '10000000',
  description: 'Default limit on internal looping.')
option('PCRE2_MATCH_LIMIT_DEPTH', type: 'string', value: 'MATCH_LIMIT',
  description: 'Default limit on internal depth of search.')
option('PCRE2GREP_BUFSIZE', type: 'string', value: '20480',
  description: 'Buffer starting size parameter for pcre2grep.')
option('PCRE2GREP_MAX_BUFSIZE', type: 'string', value: '1048576',
  description: 'Buffer maximum size parameter for pcre2grep.')
option('PCRE2_NEWLINE', type: 'combo',
  choices: ['CR', 'LF', 'CRLF', 'ANY', 'ANYCRLF', 'NUL'], value: 'LF',
  description: 'What to recognize as a newline.')
option('PCRE2_HEAP_MATCH_RECURSE', type: 'boolean', value: false,
  description: 'Obsolete option: do not use')
option('PCRE2_SUPPORT_JIT', type: 'combo', choices: ['OFF', 'ON', 'AUTO'],
  value: 'OFF', description: 'Enable support for Just-in-time compiling.')
option('PCRE2_SUPPORT_JIT_SEALLOC', type: 'boolean', value: false,
  description: 'Enable SELinux compatible execmem allocator in JIT (experimental).')
option('PCRE2GREP_SUPPORT_JIT', type: 'boolean', value: true,
  description: 'Enable use of Just-in-time compiling in pcre2grep.')
option('PCRE2GREP_SUPPORT_CALLOUT', type: 'boolean', value: true,
  description: 'Enable callout string support in pcre2grep.')
option('PCRE2GREP_SUPPORT_CALLOUT_FORK', type: 'boolean', value: true,
  description: 'Enable callout string fork support in pcre2grep.')
option('PCRE2_SUPPORT_UNICODE', type: 'boolean', value: true,
  description: 'Enable support for Unicode and UTF encodings.')
option('PCRE2_SUPPORT_BSR_ANYCRLF', type: 'boolean', value: false,
  description: 'Make backslash-R match only LF, CR and CRLF.')
option('PCRE2_NEVER_BACKSLASH_C', type: 'boolean', value: false,
  description: 'Lock out backslash-C.')
option('PCRE2_SUPPORT_VALGRIND', type: 'boolean', value: false,
  description: 'Enable Valgrind support.')
option('PCRE2_FUZZ_SUPPORT', type: 'boolean', value: false,
  description: 'Enable fuzzer support')
option('PCRE2_DIFF_FUZZ_SUPPORT', type: 'boolean', value: false,
  description: 'Enable differential fuzzer support (requires fuzz support and JIT)')
option('PCRE2_SHOW_REPORT', type: 'boolean', value: true,
  description: 'Show the final configuration report')
option('PCRE2_BUILD_PCRE2GREP', type: 'boolean', value: true,
  description: 'Build pcre2grep')
option('PCRE2_BUILD_TESTS', type: 'boolean', value: true,
  description: 'Build the tests')
option('PCRE2_SYMVERS', type: 'boolean', value: true,
  description: 'Enable library symbol versioning')
option('PCRE2_SUPPORT_LIBBZ2', type: 'feature', value: 'auto',
  description: 'Enable support for linking pcre2grep with libbz2.')
option('PCRE2_SUPPORT_LIBZ', type: 'feature', value: 'auto',
  description: 'Enable support for linking pcre2grep with libz.')
option('PCRE2_SUPPORT_LIBEDIT', type: 'feature', value: 'disabled',
  description: 'Enable support for linking pcre2test with libedit.')
option('PCRE2_SUPPORT_LIBREADLINE', type: 'feature', value: 'auto',
  description: 'Enable support for linking pcre2test with libreadline.')

