#! /bin/sh

# Run pcre2grep tests. The assumption is that the PCRE2 tests check the library
# itself. What we are checking here is the file handling and options that are
# supported by pcre2grep. This script must be run in the build directory.

# CODING CONVENTIONS:
# * Put printf arguments in single, not double quotes to avoid unwanted
#     escaping.
# * Use \0 for binary zero in printf, not \x0, for the benefit of older
#     versions (and use octal for other special values).

# Set the C locale, so that sort(1) behaves predictably.

LC_ALL=C
export LC_ALL

# Remove any non-default colouring and aliases that the caller may have set.

unset PCRE2GREP_COLOUR PCRE2GREP_COLOR PCREGREP_COLOUR PCREGREP_COLOR
unset GREP_COLOR GREP_COLORS
unset cp ls mv rm

# Remember the current (build) directory, set the program to be tested, and
# valgrind settings when requested.

builddir=`pwd`
: ${pcre2grep:=./pcre2grep}
: ${pcre2test:=./pcre2test}
pcre2grep_opts=

valgrind=
while [ $# -gt 0 ] ; do
  case $1 in
    valgrind|-valgrind|--valgrind) valgrind="valgrind -q --leak-check=no --smc-check=all-non-file --error-exitcode=70";;
    srcdir|-srcdir|--srcdir) if [ $# -lt 2 ]; then echo "Missing argument after '$1'"; exit 1; fi; shift; srcdir="$1";;
    pcre2test|-pcre2test|--pcre2test) if [ $# -lt 2 ]; then echo "Missing argument after '$1'"; exit 1; fi; shift; pcre2test="$1";;
    pcre2grep|-pcre2grep|--pcre2grep) if [ $# -lt 2 ]; then echo "Missing argument after '$1'"; exit 1; fi; shift; pcre2grep="$1";;
    *) echo "RunGrepTest: Unknown argument $1"; exit 1;;
  esac
  shift
done

if [ ! -x "$pcre2grep" ] ; then
  echo "** $pcre2grep does not exist or is not executable."
  exit 1
fi

if [ ! -x "$pcre2test" ] ; then
  echo "** $pcre2test does not exist or is not executable."
  exit 1
fi

# Support relative paths for pcre2test and pcre2grep; these are referenced after
# changing directory to srcdir.

case "$pcre2grep" in
  /*) ;;
  *) pcre2grep="$builddir/$pcre2grep";;
esac
case "$pcre2test" in
  /*) ;;
  *) pcre2test="$builddir/$pcre2test";;
esac

# Print the version header

pcre2grep_version=`"$pcre2grep" -V`
if [ "$valgrind" = "" ] ; then
  echo "Testing $pcre2grep_version"
else
  echo "Testing $pcre2grep_version using valgrind"
fi

# Set up a suitable "diff" command for comparison. Some systems have a diff
# that lacks a -u option.

cf="diff"
diff -u /dev/null /dev/null 2>/dev/null && cf="diff -u"

# Add a -a (always treat as text) if available. This was added in an attempt
# to get more detail from an Alpine Linux test failure on GitHub.

$cf -a /dev/null /dev/null 2>/dev/null && cf="$cf -a"

# Some tests involve NUL characters. It seems impossible to handle them easily
# in many operating systems. An earlier version of this script used sed to
# translate NUL into the string ZERO, but this didn't work on Solaris (aka
# SunOS), where the version of sed explicitly doesn't like them, and also MacOS
# (Darwin), OpenBSD, FreeBSD, NetBSD, and some Linux distributions like Alpine,
# even when using GNU sed. A user suggested using tr instead, which
# necessitates translating to a single character. However, on (some versions
# of?) Solaris, the normal "tr" cannot handle binary zeros, but if
# /usr/xpg4/bin/tr is available, it can do so, so test for that.

if [ -x /usr/xpg4/bin/tr ] ; then
  tr=/usr/xpg4/bin/tr
else
  tr=tr
fi

# If this test is being run from "make check", $srcdir will be set. If not, set
# it to the current or parent directory, whichever one contains the test data.
# Subsequently, we run most of the pcre2grep tests in the source directory so
# that the file names in the output are always the same.

if [ -z "$srcdir" ] ; then
  if [ -d "./testdata" ] ; then
    srcdir=.
  elif [ -d "../testdata" ] ; then
    srcdir=..
  else
    echo "Cannot find the testdata directory"
    exit 1
  fi
elif [ ! -d "$srcdir/testdata" ] ; then
  echo "The specified srcdir '$srcdir' does not contain a testdata directory"
  exit 1
fi

# Set up the path to the valgrind JIT suppressions

vjs=
if [ "$valgrind" != "" ] ; then
  "$pcre2test" -C jit >/dev/null
  if [ $? -ne 0 ]; then
    vjs="--suppressions=`realpath "$srcdir"`/testdata/valgrind-jit.supp"
  fi
fi

# Check for the availability of UTF-8 support

"$pcre2test" -C unicode >/dev/null
utf8=$?

# Check default newline convention. If it does not include LF, force LF.

nl=`"$pcre2test" -C newline`
if [ "$nl" != "LF" -a "$nl" != "ANY" -a "$nl" != "ANYCRLF" ]; then
  pcre2grep_opts="-N LF"
  echo "Default newline setting forced to LF"
fi

# ------ Function to run and check a special pcre2grep arguments test -------

checkspecial()
  {
  expect=$1
  shift
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts "$@" >>testtrygrep 2>&1
  if [ $? -ne "$expect" ] ; then
    echo "** pcre2grep $* failed - check testtrygrep"
    exit 1
  fi
  }

# ------ Functions to run with piped output -------

run_sorted()
  {
  "$@" >teststdout
  grep_rc=$?
  sort teststdout
  # Technique to pipe output to `sort`, while returning the exit code of the
  # first process in the pipe. Use a file instead.
  return $grep_rc
  }

run_null_translated()
  {
  "$@" >teststdout
  grep_rc=$?
  $tr '\000' '@' <teststdout
  return $grep_rc
  }

# ------ Normal tests ------

echo "Testing pcre2grep main features"

rm -f testtrygrep
echo "---------------------------- Test 1 -----------------------------" >testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts PATTERN ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 2 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts '^PATTERN' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 3 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -in PATTERN ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 4 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -ic PATTERN ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 5 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -in PATTERN ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 6 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -inh PATTERN ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 7 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -il PATTERN ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 8 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -l PATTERN ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 9 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -q PATTERN ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 10 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -q NEVER-PATTERN ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 11 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -vn pattern ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 12 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -ix pattern ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 13 -----------------------------" >>testtrygrep
echo seventeen >testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -f./testdata/greplist -f "$builddir/testtemp1grep" ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 14 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -w pat ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 15 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts 'abc^*' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 16 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts abc ./testdata/grepinput ./testdata/nonexistfile) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 17 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -M 'the\noutput' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 18 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mn '(the\noutput|dog\.\n--)' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 19 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mix 'Pattern' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 20 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mixn 'complete pair\nof lines' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 21 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nA3 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 22 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nB3 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 23 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -C3 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 24 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -A9 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 25 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nB9 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 26 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -A9 -B9 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 27 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -A10 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 28 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nB10 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 29 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -C12 -B10 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 30 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -inB3 'pattern' ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 31 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -inA3 'pattern' ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 32 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -L 'fox' ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 33 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts 'fox' ./testdata/grepnonexist) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 34 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -s 'fox' ./testdata/grepnonexist) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 35 -----------------------------" >>testtrygrep
(cd "$srcdir"; run_sorted $valgrind $vjs "$pcre2grep" $pcre2grep_opts -L -r --include=grepinputx --include grepinput8 --exclude-dir='^\.' 'fox' ./testdata) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 36 -----------------------------" >>testtrygrep
(cd "$srcdir"; run_sorted $valgrind $vjs "$pcre2grep" $pcre2grep_opts -L -r --include='grepinput[^C]' --exclude 'grepinput$' --exclude='grepinput(Bad)?8' --exclude=grepinputM --exclude=grepinputUN --exclude-dir='^\.' 'fox' ./testdata) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 37 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts  '^(a+)*\d' ./testdata/grepinput) >>testtrygrep 2>teststderrgrep
echo "RC=$?" >>testtrygrep
echo "======== STDERR ========" >>testtrygrep
cat teststderrgrep >>testtrygrep

echo "---------------------------- Test 38 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts '>\x00<' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 39 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -A1 'before the binary zero' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 40 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -B1 'after the binary zero' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 41 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -B1 -o '\w+ the binary zero' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 42 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -B1 -onH '\w+ the binary zero' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 43 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -on 'before|zero|after' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 44 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -on -e before -ezero -e after ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 45 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -on -f ./testdata/greplist -e binary ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 46 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -e 'unopened)' -e abc ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -eabc -e '(unclosed' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -eabc -e xyz -e '[unclosed' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --regex=123 -eabc -e xyz -e '[unclosed' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 47 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Fx "AB.VE
elephant" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 48 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -F "AB.VE
elephant" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 49 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -F -e DATA -e "AB.VE
elephant" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 50 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts "^(abc|def|ghi|jkl)" ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 51 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mv "brown\sfox" ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 52 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=always jumps ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 53 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --file-offsets 'before|zero|after' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 54 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --line-offsets 'before|zero|after' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 55 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -f./testdata/greplist --color=always ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 56 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -c --exclude=grepinputC lazy ./testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 57 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -c -l --exclude=grepinputC lazy ./testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 58 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --regex=PATTERN ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 59 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --regexp=PATTERN ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 60 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --regex PATTERN ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 61 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --regexp PATTERN ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 62 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind "$pcre2grep" $pcre2grep_opts --match-limit=1000 --no-jit -M 'This is a file(.|\R)*file.' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 63 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind "$pcre2grep" $pcre2grep_opts --recursion-limit=1K --no-jit -M 'This is a file(.|\R)*file.' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 64 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o1 '(?<=PAT)TERN (ap(pear)s)' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 65 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o2 '(?<=PAT)TERN (ap(pear)s)' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 66 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o3 '(?<=PAT)TERN (ap(pear)s)' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 67 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o12 '(?<=PAT)TERN (ap(pear)s)' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 68 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --only-matching=2 '(?<=PAT)TERN (ap(pear)s)' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 69 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -vn --colour=always pattern ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 70 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --color=always -M "triple:\t.*\n\n" ./testdata/grepinput3) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --color=always -M -n "triple:\t.*\n\n" ./testdata/grepinput3) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -M "triple:\t.*\n\n" ./testdata/grepinput3) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -M -n "triple:\t.*\n\n" ./testdata/grepinput3) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 71 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o "^01|^02|^03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 72 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --color=always "^01|^02|^03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 73 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o --colour=always "^01|^02|^03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 74 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o "^01|02|^03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 75 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --color=always "^01|02|^03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 76 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o --colour=always "^01|02|^03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 77 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o "^01|^02|03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 78 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --color=always "^01|^02|03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 79 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o --colour=always "^01|^02|03" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 80 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o "\b01|\b02" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 81 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --color=always "\\b01|\\b02" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 82 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o --colour=always "\\b01|\\b02" ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 83 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --buffer-size=10 --max-buffer-size=100 "^a" ./testdata/grepinput3) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 84 -----------------------------" >>testtrygrep
echo testdata/grepinput3 >testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --file-list ./testdata/grepfilelist --file-list "$builddir/testtemp1grep" "fox|complete|t7") >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 85 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --file-list=./testdata/grepfilelist "dolor" ./testdata/grepinput3) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 86 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts "dog" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 87 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts "cat" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 88 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -v "cat" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 89 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -I "dog" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 90 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --binary-files=without-match "dog" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 91 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -a "dog" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 92 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --binary-files=text "dog" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 93 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --text "dog" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 94 -----------------------------" >>testtrygrep
(cd "$srcdir"; run_sorted $valgrind $vjs "$pcre2grep" $pcre2grep_opts -L -r --include=grepinputx --include grepinput8 'fox' ./testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 95 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --file-list ./testdata/grepfilelist --exclude grepinputv "fox|complete") >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 96 -----------------------------" >>testtrygrep
(cd "$srcdir"; run_sorted $valgrind $vjs "$pcre2grep" $pcre2grep_opts -L -r --include-dir=testdata --exclude '^(?!grepinput)' --exclude=grepinput[MCU] 'fox' ./test*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 97 -----------------------------" >>testtrygrep
echo "grepinput$" >testtemp1grep
echo "grepinput8" >>testtemp1grep
echo "grepinputBad8" >>testtemp1grep
(cd "$srcdir"; run_sorted $valgrind $vjs "$pcre2grep" $pcre2grep_opts -L -r --include=grepinput --exclude=grepinput[MCU] --exclude-from "$builddir/testtemp1grep" --exclude-dir='^\.' 'fox' ./testdata) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 98 -----------------------------" >>testtrygrep
echo "grepinput$" >testtemp1grep
echo "grepinput8" >>testtemp1grep
echo "grepinputBad8" >>testtemp1grep
(cd "$srcdir"; run_sorted $valgrind $vjs "$pcre2grep" $pcre2grep_opts -L -r --exclude=grepinput3 --exclude=grepinput[MCU] --include=grepinput --exclude-from "$builddir/testtemp1grep" --exclude-dir='^\.' 'fox' ./testdata) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 99 -----------------------------" >>testtrygrep
echo "grepinput$" >testtemp1grep
echo "grepinput8" >testtemp2grep
echo "grepinputBad8" >>testtemp1grep
(cd "$srcdir"; run_sorted $valgrind $vjs "$pcre2grep" $pcre2grep_opts -L -r --include grepinput --exclude=grepinput[MCU] --exclude-from "$builddir/testtemp1grep" --exclude-from="$builddir/testtemp2grep" --exclude-dir='^\.' 'fox' ./testdata) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 100 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Ho2 --only-matching=1 -o3 '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 101 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o3 -Ho2 -o12 --only-matching=1 -o3 --colour=always --om-separator='|' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 102 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n "^$" ./testdata/grepinput3) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 103 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --only-matching "^$" ./testdata/grepinput3) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 104 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --only-matching "^$" ./testdata/grepinput3) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 105 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=always "ipsum|" ./testdata/grepinput3) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 106 -----------------------------" >>testtrygrep
(cd "$srcdir"; echo "a" | $valgrind $vjs "$pcre2grep" $pcre2grep_opts -M "|a" ) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 107 -----------------------------" >>testtrygrep
echo "a" >testtemp1grep
echo "aaaaa" >>testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts  --line-offsets --allow-lookaround-bsk '(?<=\Ka)' "$builddir/testtemp1grep") >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 108 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -lq PATTERN ./testdata/grepinput ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 109 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -cq --exclude=grepinputC lazy ./testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 110 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --om-separator / -Mo0 -o1 -o2 'match (\d+):\n (.)\n' testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 111 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --line-offsets -M 'match (\d+):\n (.)\n' testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 112 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --file-offsets -M 'match (\d+):\n (.)\n' testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 113 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --total-count --exclude=grepinputC 'the' testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 114 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -tc --exclude=grepinputC 'the' testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 115 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -tlc --exclude=grepinputC 'the' testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 116 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --exclude=grepinput[MCU] -th 'the' testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 117 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -tch --exclude=grepinputC 'the' testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 118 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -tL --exclude=grepinputC 'the' testdata/grepinput*) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 119 -----------------------------" >>testtrygrep
printf '123\n456\n789\n---abc\ndef\nxyz\n---\n' >testNinputgrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mo '(\n|[^-])*---' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 120 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -HO '$0:$2$1$3' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -HO '$&:$2$1$3' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m 1 -O '$0:$a$b$e$f$r$t$v' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -HO '${X}' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -HO 'XX$' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -O '$x{12345678}' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -O '$x{123Z' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --output '$x{1234}' '(\w+) binary (\w+)(\.)?' ./testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 121 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -F '\E and (regex)' testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 122 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -w 'cat|dog' testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 123 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -w 'dog|cat' testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 124 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mn --colour=always 'start[\s]+end' testdata/grepinputM) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mn --colour=always -A2 'start[\s]+end' testdata/grepinputM) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mn 'start[\s]+end' testdata/grepinputM) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -Mn -A2 'start[\s]+end' testdata/grepinputM) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 125 -----------------------------" >>testtrygrep
printf 'abcd\n' >testNinputgrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=always --allow-lookaround-bsk '(?<=\K.)' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=always --allow-lookaround-bsk '(?=.\K)' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=always --allow-lookaround-bsk '(?<=\K[ac])' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=always --allow-lookaround-bsk '(?=[ac]\K)' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
GREP_COLORS='ms=1;20' $valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=always --allow-lookaround-bsk '(?=[ac]\K)' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 126 -----------------------------" >>testtrygrep
printf 'Next line pattern has binary zero\nABC\0XYZ\n' >testtemp1grep
printf 'ABC\0XYZ\nABCDEF\nDEFABC\n' >testtemp2grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -a -f testtemp1grep testtemp2grep >>testtrygrep
echo "RC=$?" >>testtrygrep
printf 'Next line pattern is erroneous.\n^abc)(xy' >testtemp1grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -a -f testtemp1grep testtemp2grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 127 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o --om-capture=0 'pattern()()()()' testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 128 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m1M -o1 --om-capture=0 'pattern()()()()' testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 129 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m 2 'fox' testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 130 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o -m2 'fox' testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 131 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -oc -m2 'fox' testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 132 -----------------------------" >>testtrygrep
(cd "$srcdir"; exec 3<testdata/grepinput; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m1 -A3 '^match' <&3; echo "RC=$?"; echo '---'; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m1 '.*' <&3; echo "RC=$?"; exec 3<&-) >>testtrygrep 2>&1

echo "---------------------------- Test 133 -----------------------------" >>testtrygrep
(cd "$srcdir"; exec 3<testdata/grepinput; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m1 -A3 '^match' <&3; echo "RC=$?"; echo '---'; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m1 -A3 '^match' <&3; echo "RC=$?"; exec 3<&-) >>testtrygrep 2>&1

echo "---------------------------- Test 134 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --max-count=1 -nH -O '=$x{41}$x423$o{103}$o1045=' 'fox' -) <"$srcdir/testdata/grepinputv" >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 135 -----------------------------" >>testtrygrep
(cd "$srcdir"; run_null_translated $valgrind $vjs "$pcre2grep" $pcre2grep_opts -HZ 'word' ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; run_null_translated $valgrind $vjs "$pcre2grep" $pcre2grep_opts -lZ 'word' ./testdata/grepinputv ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; run_null_translated $valgrind $vjs "$pcre2grep" $pcre2grep_opts -A 1 -B 1 -HZ 'word' ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -MHZn 'start[\s]+end' testdata/grepinputM) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 136 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m1MK -o1 --om-capture=0 'pattern()()()()' testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --max-count=1MK -o1 --om-capture=0 'pattern()()()()' testdata/grepinput) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 137 -----------------------------" >>testtrygrep
printf 'Last line\nhas no newline' >testtemp1grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -A1 Last testtemp1grep >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 138 -----------------------------" >>testtrygrep
printf 'AbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\nAbC\n' >testtemp1grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit --heap-limit=0 b testtemp1grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 139 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --line-buffered 'fox' testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 140 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --buffer-size=10 -A1 'brown' testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 141 -----------------------------" >>testtrygrep
printf "%s/testdata/grepinputv\n-\n" "$srcdir" >testtemp1grep
printf 'This is a line from stdin.' >testtemp2grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --file-list testtemp1grep "line from stdin" <testtemp2grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 142 -----------------------------" >>testtrygrep
printf "/does/not/exist\n" >testtemp1grep
printf 'This is a line from stdin.' >testtemp2grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --file-list testtemp1grep "line from stdin" >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 143 -----------------------------" >>testtrygrep
printf 'fox|cat' >testtemp1grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -f - "$srcdir/testdata/grepinputv" <testtemp1grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 144 -----------------------------" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -f /non/exist "$srcdir/testdata/grepinputv" >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 145 -----------------------------" >>testtrygrep
printf '*meta*\rdog.' >testtemp1grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -Ncr -F -f testtemp1grep "$srcdir/testdata/grepinputv" >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 146 -----------------------------" >>testtrygrep
printf 'A123B' >testtemp1grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -H -e '123|fox' - <testtemp1grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -h -e '123|fox' - "$srcdir/testdata/grepinputv" <testtemp1grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts - "$srcdir/testdata/grepinputv" <testtemp1grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 147 -----------------------------" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -e '123|fox' -- -nonfile >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
printf 'A123B' >testtemp1grep
printf 'C123D' > ./-testtemp1grep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts '123' -- -testtemp1grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts '123' testtemp1grep -- -testtemp1grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts '123' -- <testtemp1grep >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
printf 'E123F' > ./--
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -- '123' -- >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 148 -----------------------------" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --nonexist >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -n-n-bad >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --context >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --only-matching --output=xx >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=badvalue >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --newline=badvalue >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -d badvalue >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -D badvalue >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --buffer-size=0 >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --exclude '(badpat' abc /dev/null >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --exclude-from /non/exist abc /dev/null >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --include-from /non/exist abc /dev/null >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --file-list=/non/exist abc /dev/null >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 149 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --binary-files=binary "dog" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --binary-files=wrong "dog" ./testdata/grepbinary) >>testtrygrep 2>&1
echo "RC=$?" >>testtrygrep

# This test runs the code that tests locale support. However, on some systems
# (e.g. Alpine Linux) there is no locale support and running this test just
# generates a "no match" result. Therefore, we test for locale support, and if
# it is found missing, we pretend that the test has run as expected so that the
# output matches.

echo "---------------------------- Test 150 -----------------------------" >>testtrygrep
which locale >/dev/null 2>&1
if [ $? -ne 0 ]; then
  echo "pcre2grep: Failed to set locale locale.bad (obtained from LC_CTYPE)" >>testtrygrep
  echo "RC=2" >>testtrygrep
else
  (cd "$srcdir"; unset LC_ALL; LC_CTYPE=locale.bad; export LC_CTYPE; $valgrind $vjs "$pcre2grep" $pcre2grep_opts abc /dev/null >>"$builddir/testtrygrep" 2>&1) >testtemp1grep 2>&1
  echo "RC=$?" >>testtrygrep
  shell_errors=`cat testtemp1grep`
  if [ x"$shell_errors" != x ] ; then
    printf "shell errors during locale test: "
    echo "$shell_errors"
  fi
fi

echo "---------------------------- Test 151 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --colour=always -e this -e The -e 'The wo' testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 152 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nA3 --group-separator='++' 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 153 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nA3 --no-group-separator 'four' ./testdata/grepinputx) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 154 -----------------------------" >>testtrygrep
>testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -f "$builddir/testtemp1grep" ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 155 -----------------------------" >>testtrygrep
echo "" >testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -f "$builddir/testtemp1grep" ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 156 -----------------------------" >>testtrygrep
echo "" >testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --posix-pattern-file --file "$builddir/testtemp1grep" ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 157 -----------------------------" >>testtrygrep
echo "spaces " >testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -o --posix-pattern-file --file="$builddir/testtemp1grep" ./testdata/grepinputv >"$builddir/testtemp2grep" && $valgrind $vjs "$pcre2grep" $pcre2grep_opts -q "s " "$builddir/testtemp2grep") >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 158 -----------------------------" >>testtrygrep
echo "spaces." >testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -f "$builddir/testtemp1grep" ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 159 -----------------------------" >>testtrygrep
printf "spaces.\r\n" >testtemp1grep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --posix-pattern-file -f"$builddir/testtemp1grep" ./testdata/grepinputv) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 160 -----------------------------" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nC3 '^(ert|jkl)' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep
(cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -B4 -A2 '^(ert|dfg)' ./testdata/grepinput) >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "---------------------------- Test 161 -----------------------------" >>testtrygrep
printf 'XfooY\n' >testNinputgrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --allow-lookaround-bsk -o '(?=foo\K)' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --allow-lookaround-bsk --output '$0' '(?=foo\K)' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --allow-lookaround-bsk --line-offsets '(?=foo\K)' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts --allow-lookaround-bsk --file-offsets '(?=foo\K)' testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep


# Now compare the results.

$cf "$srcdir/testdata/grepoutput" testtrygrep
if [ $? != 0 ] ; then exit 1; fi


# These tests require UTF-8 support

if [ $utf8 -ne 0 ] ; then
  echo "Testing pcre2grep UTF-8 features"

  rm -f testtrygrep
  echo "---------------------------- Test U1 -----------------------------" >testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -u --newline=any "^X" ./testdata/grepinput8) >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U2 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -u -C 3 --newline=any "Match" ./testdata/grepinput8) >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U3 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts --line-offsets -u --newline=any --allow-lookaround-bsk '(?<=\K\x{17f})' ./testdata/grepinput8) >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U4 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -u -o '....' ./testdata/grepinputBad8) >>testtrygrep 2>&1
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U5 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -U -o '....' ./testdata/grepinputBad8) >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U6 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -u -m1 -O '=$x{1d3}$o{744}=' 'fox') <"$srcdir/testdata/grepinputv" >>testtrygrep 2>&1
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U7 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -ui --colour=always 'k+|\babc\b' ./testdata/grepinput8) >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U8 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -UiEP --colour=always 'k+|\babc\b' ./testdata/grepinput8) >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U9 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -u --colour=always 'A\d' ./testdata/grepinput8) >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U10 -----------------------------" >>testtrygrep
  (cd "$srcdir"; $valgrind $vjs "$pcre2grep" $pcre2grep_opts -u --posix-digit --colour=always 'A\d' ./testdata/grepinput8) >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "---------------------------- Test U11 -----------------------------" >>testtrygrep
  printf '................................................' | tr '.' '\200' >testtemp1grep
  printf 'x\n' >>testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit --buffer-size=16 -U --allow-lookaround-bsk -o '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "only-matching RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit --buffer-size=16 -U --allow-lookaround-bsk -M '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "multiline RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit --buffer-size=16 -U --allow-lookaround-bsk --colour=always '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "colour RC=$?" >>testtrygrep

  echo "---------------------------- Test U12 -----------------------------" >>testtrygrep
  # Colouring only, so the subject is a single line. An empty match at the end
  # of the subject, then one that matches before retrying at the end.
  printf 'abc\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -u '$' testtemp1grep >>testtrygrep 2>&1
  echo "colour-empty-at-end RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -u '.?' testtemp1grep >>testtrygrep 2>&1
  echo "colour-nonempty-then-empty RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -u '^' testtemp1grep >>testtrygrep 2>&1
  echo "colour-empty-at-start RC=$?" >>testtrygrep

  # An empty line, so the first match is empty with nothing following it, and a
  # final line with no newline, so a restart can reach the end of the line.
  printf '\nabc\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -u '.?' testtemp1grep >>testtrygrep 2>&1
  echo "colour-empty-line RC=$?" >>testtrygrep
  printf 'abc' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -u '.?' testtemp1grep >>testtrygrep 2>&1
  echo "colour-no-final-newline RC=$?" >>testtrygrep

  # Multiline, where a restart may have to move on to a following line.
  printf 'a\nb\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -u '$' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-empty-at-line-end RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -u '^' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-empty-at-line-start RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -u '.?' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-nonempty-then-empty RC=$?" >>testtrygrep

  # A match that spans several lines, so that the restart has to skip over more
  # than one line before looking for the next match.
  printf 'a\nb\nc\nd\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -u '(?s)a.*c' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-spanning RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -u '(?s)a.*c|$' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-spanning-then-empty RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M --colour=always -u '(?s)a.*c|$' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-colour-spanning RC=$?" >>testtrygrep

  # Invalid UTF-8 after an empty match, which is when the scan over
  # continuation bytes that follow the restart point can run. Here the scan
  # stops at the start of the next character.
  printf 'x\200\200y\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -U '^' testtemp1grep >>testtrygrep 2>&1
  echo "colour-utf-scan-to-char RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -U '^' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-utf-scan-to-char RC=$?" >>testtrygrep

  # The continuation bytes run up to the newline, and then up to the end of the
  # subject, when there is no newline to stop the scan.
  printf 'x\200\200\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -U '^' testtemp1grep >>testtrygrep 2>&1
  echo "colour-utf-scan-to-newline RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -U '^' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-utf-scan-to-newline RC=$?" >>testtrygrep
  printf 'x\200\200' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -U '^' testtemp1grep >>testtrygrep 2>&1
  echo "colour-utf-scan-to-end RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -U '^' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-utf-scan-to-end RC=$?" >>testtrygrep

  # A subject that is nothing but continuation bytes, so the very first match
  # is empty and the scan immediately reaches the end.
  printf '\200\200' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -U '.?' testtemp1grep >>testtrygrep 2>&1
  echo "colour-utf-only-continuations RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -U '.?' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-utf-only-continuations RC=$?" >>testtrygrep

  # Continuation bytes at the end of a multi-line subject, reached after an
  # empty match on an earlier line, and after a match that spans lines.
  printf 'a\nb\n\n\200\200' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -U '.?' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-utf-trailing RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -U '$' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-utf-trailing-empty RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M --colour=always -U '(?s)a.*b|$' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-colour-utf-trailing-spanning RC=$?" >>testtrygrep

  echo "---------------------------- Test U13 -----------------------------" >>testtrygrep
  # The same restart, but reached by \K rather than by an empty match.
  printf 'abc\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --colour=always -u --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "colour-bsk RC=$?" >>testtrygrep
  printf 'a\nb\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -M -u --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-bsk RC=$?" >>testtrygrep

  # The same, but with the restart landing on invalid UTF-8.
  printf 'x\200\200y\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit -n --colour=always -U --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "colour-bsk-utf-scan-to-char RC=$?" >>testtrygrep
  printf 'x\200\200' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit -n -M -U --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-bsk-utf-scan-to-end RC=$?" >>testtrygrep
  printf 'a\nx\200\200' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit -n -M --colour=always -U --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-colour-bsk-utf-trailing RC=$?" >>testtrygrep


  echo "---------------------------- Test U14 -----------------------------" >>testtrygrep

  # A pattern that keeps making progress, so the restart is the ordinary one
  # and the line is never advanced. This is the path the other U14 tests build on.
  printf 'abcabc\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -u 'a.' testtemp1grep >>testtrygrep 2>&1
  echo "control-progress RC=$?" >>testtrygrep

  # An empty match, which is the case the restart exists for. "$" matches only
  # at the end of the subject, so the restart is immediately at the end; "^"
  # matches at the start, so it has to step forward by one character first.
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -u '$' testtemp1grep >>testtrygrep 2>&1
  echo "empty-at-end RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -u '^' testtemp1grep >>testtrygrep 2>&1
  echo "empty-at-start RC=$?" >>testtrygrep

  # \K in a lookbehind reports a non-empty match that ends no later than the
  # offset it was started from. PCRE2_NOTEMPTY is set once a match has been
  # found, so this, unlike an empty match, can stop the loop making progress on
  # every iteration and not just the first.
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -u --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "bsk-restart RC=$?" >>testtrygrep

  # The step forward lands on invalid UTF-8, so the scan over continuation
  # bytes runs. Here it stops at the start of the next character, and then at
  # the newline, both of which are within the subject.
  printf 'x\200\200y\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit -n -o -U --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "bsk-utf-scan-to-char RC=$?" >>testtrygrep
  printf 'x\200\200\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit -n -o -U --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "bsk-utf-scan-to-newline RC=$?" >>testtrygrep

  # The same, but with no newline to stop the scan, so it runs to the end of
  # the subject and then looks at the byte after it.
  printf 'x\200\200' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts --no-jit -n -o -U --allow-lookaround-bsk '(?<=\K.)' testtemp1grep >>testtrygrep 2>&1
  echo "bsk-utf-scan-to-end RC=$?" >>testtrygrep

  # Moving on to another line, which only happens in multiline mode. The first
  # match ends exactly at the start of the next line, so the line is advanced
  # and the line number with it; the second ends two lines further on.
  printf 'ab\ncd\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -M -u 'ab\n' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-line-boundary RC=$?" >>testtrygrep
  printf 'ab\ncd\nef\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -M -u '(?s)ab.*ef' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-spanning RC=$?" >>testtrygrep

  # An empty match in multiline mode, where the step forward is what takes the
  # restart past the end of the line.
  printf 'a\nb\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -M -u '$' testtemp1grep >>testtrygrep 2>&1
  echo "multiline-empty RC=$?" >>testtrygrep

  # A match that ends between the CR and the LF of a CRLF line ending, so the
  # restart is past the text of the line but short of the start of the next
  # one. Without -M the line is never advanced, so that is the control.
  printf 'ab\r\ncd\r\n' >testtemp1grep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -N CRLF '\r' testtemp1grep >>testtrygrep 2>&1
  echo "crlf-not-multiline RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -M -N CRLF '\r' testtemp1grep >>testtrygrep 2>&1
  echo "crlf-mid-terminator RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -o -M -N ANY '\r' testtemp1grep >>testtrygrep 2>&1
  echo "any-mid-terminator RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -M -N CRLF --line-offsets '\r' testtemp1grep >>testtrygrep 2>&1
  echo "crlf-mid-terminator-line-offsets RC=$?" >>testtrygrep

  $cf "$srcdir/testdata/grepoutput8" testtrygrep
  if [ $? != 0 ] ; then exit 1; fi

else
  echo "Skipping pcre2grep UTF-8 tests: no UTF-8 support in PCRE2 library"
fi


# We go to some contortions to try to ensure that the tests for the various
# newline settings will work in environments where the normal newline sequence
# is not \n. Do not use exported files, whose line endings might be changed.
# Instead, create an input file using printf so that its contents are exactly
# what we want. Note the messy fudge to get printf to write a string that
# starts with a hyphen. These tests are run in the build directory.

echo "Testing pcre2grep newline settings"
printf 'abc\rdef\r\nghi\njkl' >testNinputgrep

rm -f testtrygrep
printf '%c--------------------------- Test N1 -----------------------------\r\n' - >testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -n -N CR "^(abc|def|ghi|jkl)" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -B1 -n -N CR "^def" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

printf '%c--------------------------- Test N2 -----------------------------\r\n' - >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --newline=crlf "^(abc|def|ghi|jkl)" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -B1 -n -N CRLF "^ghi" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

printf '%c--------------------------- Test N3 -----------------------------\r\n' - >>testtrygrep
pattern=`printf 'def\rjkl'`
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --newline=cr -F "$pattern" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

printf '%c--------------------------- Test N4 -----------------------------\r\n' - >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --newline=crlf -F -f "$srcdir/testdata/greppatN4" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

printf '%c--------------------------- Test N5 -----------------------------\r\n' - >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --newline=any "^(abc|def|ghi|jkl)" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -B1 -n --newline=any "^def" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

printf '%c--------------------------- Test N6 -----------------------------\r\n' - >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -n --newline=anycrlf "^(abc|def|ghi|jkl)" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -B1 -n --newline=anycrlf "^jkl" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

printf '%c--------------------------- Test N7 -----------------------------\r\n' - >>testtrygrep
printf 'xyz\0abc\0def' >testNinputgrep
run_null_translated $valgrind $vjs "$pcre2grep" $pcre2grep_opts -na --newline=nul "^(abc|def)" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep
run_null_translated $valgrind $vjs "$pcre2grep" $pcre2grep_opts -B1 -na --newline=nul "^(abc|def)" testNinputgrep >>testtrygrep
echo "RC=$?" >>testtrygrep

printf '%c--------------------------- Test N8 -----------------------------\r\n' - >>testtrygrep
$valgrind $vjs "$pcre2grep" $pcre2grep_opts -na --newline=anycrlf "^a" "$srcdir/testdata/grepinputBad8_Trail" >>testtrygrep
echo "RC=$?" >>testtrygrep

echo "" >>testtrygrep

$cf "$srcdir/testdata/grepoutputN" testtrygrep
if [ $? != 0 ] ; then exit 1; fi


# These newline tests need UTF support.

if [ $utf8 -ne 0 ] ; then
  echo "Testing pcre2grep newline settings with UTF-8 features"

  rm -f testtrygrep
  printf '%c--------------------------- Test UN1 -----------------------------\r\n' - >testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nau --newline=anycrlf "^(abc|def)" "$srcdir/testdata/grepinputUN" >>testtrygrep
  echo "RC=$?" >>testtrygrep

  printf '%c--------------------------- Test UN2 -----------------------------\r\n' - >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -nauU --newline=anycrlf "^a" "$srcdir/testdata/grepinputBad8_Trail" >>testtrygrep
  echo "RC=$?" >>testtrygrep

  echo "" >>testtrygrep

  $cf "$srcdir/testdata/grepoutputUN" testtrygrep
  if [ $? != 0 ] ; then exit 1; fi
else
  echo "Skipping pcre2grep newline UTF-8 tests: no UTF-8 support in PCRE2 library"
fi


# If pcre2grep supports script callouts, run some tests on them. It is possible
# to restrict these callouts to the non-fork case, either for security, or for
# environments that do not support fork(). This is handled by comparing to a
# different output.

if $valgrind $vjs "$pcre2grep" $pcre2grep_opts --help | $valgrind $vjs "$pcre2grep" $pcre2grep_opts -q 'callout scripts in patterns are supported'; then
  echo "Testing pcre2grep script callouts"
  rm -f testtrygrep
  echo "--- Test 1 ---" >testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts '(T)(..(.))(?C"/bin/echo|Arg1: [$1] [$2] [$3]|Arg2: $|${1}$| ($4) ($14) ($0)")()' "$srcdir/testdata/grepinputv" >>testtrygrep
  echo "RC=$?" >>testtrygrep
  echo "--- Test 2 ---" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts '(T)(..(.))()()()()()()()(..)(?C"/bin/echo|Arg1: [$11] [${11}]")' "$srcdir/testdata/grepinputv" >>testtrygrep
  echo "RC=$?" >>testtrygrep
  echo "--- Test 3 ---" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts '(T)(?C"|$0:$1$n")' "$srcdir/testdata/grepinputv" >>testtrygrep
  echo "RC=$?" >>testtrygrep
  echo "--- Test 4 ---" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts '(T)(?C"/bin/echo|$0:$1$n")' "$srcdir/testdata/grepinputv" >>testtrygrep
  echo "RC=$?" >>testtrygrep
  echo "--- Test 5 ---" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts '(T)(?C"|$1$n")(*F)' "$srcdir/testdata/grepinputv" >>testtrygrep
  echo "RC=$?" >>testtrygrep
  echo "--- Test 6 ---" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts -m1 '(T)(?C"|$0:$1:$x{41}$o{101}$n")' "$srcdir/testdata/grepinputv" >>testtrygrep
  echo "RC=$?" >>testtrygrep

  if $valgrind $vjs "$pcre2grep" $pcre2grep_opts --help | $valgrind $vjs "$pcre2grep" $pcre2grep_opts -q 'Non-fork callout scripts in patterns are supported'; then
    nonfork=1
    $cf "$srcdir/testdata/grepoutputCN" testtrygrep
  else
    nonfork=0
    $cf "$srcdir/testdata/grepoutputC" testtrygrep
  fi
  if [ $? != 0 ] ; then exit 1; fi

  # These callout tests need UTF support.

  if [ $utf8 -ne 0 ] ; then
    echo "Testing pcre2grep script callout with UTF-8 features"
    rm -f testtrygrep
    echo "--- Test 1 ---" >testtrygrep
    $valgrind $vjs "$pcre2grep" $pcre2grep_opts -u '(T)(?C"|$0:$x{a6}$n")' "$srcdir/testdata/grepinputv" >>testtrygrep
    echo "RC=$?" >>testtrygrep
    echo "--- Test 2 ---" >>testtrygrep
    $valgrind $vjs "$pcre2grep" $pcre2grep_opts -u '(T)(?C"/bin/echo|$0:$x{a6}$n")' "$srcdir/testdata/grepinputv" >>testtrygrep
    echo "RC=$?" >>testtrygrep

    if [ $nonfork = 1 ] ; then
      $cf "$srcdir/testdata/grepoutputCNU" testtrygrep
    else
      $cf "$srcdir/testdata/grepoutputCU" testtrygrep
    fi
    if [ $? != 0 ] ; then exit 1; fi
  else
    echo "Skipping pcre2grep script callout UTF-8 tests: no UTF-8 support in PCRE2 library"
  fi

  unset nonfork
else
  echo "Script callouts are not supported"
fi


# Test reading .gz and .bz2 files when supported.

if $valgrind $vjs "$pcre2grep" $pcre2grep_opts --help | $valgrind $vjs "$pcre2grep" $pcre2grep_opts -q '\.gz are read using zlib'; then
  echo "Testing reading .gz file"
  rm -f testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts 'one|two' "$srcdir/testdata/grepinputC.gz" >testtrygrep
  echo "RC=$?" >>testtrygrep
  $cf "$srcdir/testdata/grepoutputCgz" testtrygrep
  if [ $? != 0 ] ; then exit 1; fi
fi

if $valgrind $vjs "$pcre2grep" $pcre2grep_opts --help | $valgrind $vjs "$pcre2grep" $pcre2grep_opts -q '\.bz2 are read using bzlib2'; then
  echo "Testing reading .bz2 file"
  rm -f testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts 'one|two' "$srcdir/testdata/grepinputC.bz2" >testtrygrep
  echo "RC=$?" >>testtrygrep
  $valgrind $vjs "$pcre2grep" $pcre2grep_opts 'one|two' "$srcdir/testdata/grepnot.bz2" >>testtrygrep
  echo "RC=$?" >>testtrygrep
  $cf "$srcdir/testdata/grepoutputCbz2" testtrygrep
  if [ $? != 0 ] ; then exit 1; fi
fi


# Finally, some tests to exercise code that is not tested above, just to be
# sure that it runs OK. Doing this improves the coverage statistics. The output
# is not checked.

echo "Testing miscellaneous pcre2grep arguments (unchecked)"
rm -f testtrygrep
echo '' >testtrygrep
checkspecial 2 -xxxxx
checkspecial 0 --help
checkspecial 1 --line-buffered --colour=auto abc /dev/null
checkspecial 1 --line-buffered --color abc /dev/null
checkspecial 1 -dskip abc .
checkspecial 1 -Dread -Dskip abc /dev/null
checkspecial 2 -f "$srcdir/testdata/greplistBad" /dev/null
checkspecial 2 "(unpaired" /dev/null
checkspecial 2 -e "(unpaired1" -e "(unpaired2" /dev/null

# Clean up local working files
rm -f testNinputgrep teststderrgrep testtrygrep testtemp1grep testtemp2grep teststdout
rm -f ./-testtemp1grep ./--

exit 0

# End
