= pcre2_compile(3)
:doctype: manpage
:manname: pcre2_compile
:manpurpose: compile a regular expression pattern
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 30 October 2024
:revdate: 30 October 2024

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

pcre2_code *pcre2_compile(PCRE2_SPTR pattern, PCRE2_SIZE patlen,
                          uint32_t options, int *errorptr,
                          PCRE2_SIZE *erroroffset,
                          pcre2_compile_context *ccontext);
----

== Description

This function compiles a regular expression pattern into an internal form. Its
arguments are:

[.parameters]
arg:pattern::
    A string containing expression to be compiled
arg:patlen::
    The length of the string or const:PCRE2_ZERO_TERMINATED
arg:options::
    Primary option bits
arg:errorptr::
    Where to put an error code
arg:erroroffset::
    Where to put an error offset
arg:ccontext::
    Pointer to a compile context or const:NULL

The length of the pattern and any error offset that is returned are in code
units, not characters. A const:NULL pattern with zero length is treated as an empty
string. A compile context is needed only if you want to provide custom memory
allocation functions, or to provide an external function for system stack size
checking (see func:pcre2_set_compile_recursion_guard()), or to change one or
more of these parameters:

* What [.regex]`\R` matches (Unicode newlines, or CR, LF, CRLF only);
* PCRE2's character tables;
* The newline character sequence;
* The compile time nested parentheses limit;
* The maximum pattern length (in code units) that is allowed;
* The additional options bits.

The primary option bits are:

[.options]
const:PCRE2_ANCHORED::
    Force pattern anchoring
const:PCRE2_ALLOW_EMPTY_CLASS::
    Allow empty classes
const:PCRE2_ALT_BSUX::
    Alternative handling of [.regex]`\u`, [.regex]`\U`, and [.regex]`\x`
const:PCRE2_ALT_CIRCUMFLEX::
    Alternative handling of [.regex]`+^+` in multiline mode
const:PCRE2_ALT_EXTENDED_CLASS::
    Alternative extended character class syntax
const:PCRE2_ALT_VERBNAMES::
    Process backslashes in verb names
const:PCRE2_AUTO_CALLOUT::
    Compile automatic callouts
const:PCRE2_CASELESS::
    Do caseless matching
const:PCRE2_DOLLAR_ENDONLY::
    [.regex]`$` not to match newline at end
const:PCRE2_DOTALL::
    [.regex]`.` matches anything including NL
const:PCRE2_DUPNAMES::
    Allow duplicate names for subpatterns
const:PCRE2_ENDANCHORED::
    Pattern can match only at end of subject
const:PCRE2_EXTENDED::
    Ignore white space and [.regex]`+#+` comments
const:PCRE2_FIRSTLINE::
    Force matching to be before newline
const:PCRE2_LITERAL::
    Pattern characters are all literal
const:PCRE2_MATCH_INVALID_UTF::
    Enable support for matching invalid UTF
const:PCRE2_MATCH_UNSET_BACKREF::
    Match unset backreferences
const:PCRE2_MULTILINE::
    [.regex]`+^+` and [.regex]`$` match newlines within data
const:PCRE2_NEVER_BACKSLASH_C::
    Lock out the use of [.regex]`\C` in patterns
const:PCRE2_NEVER_UCP::
    Lock out const:PCRE2_UCP, e.g. via [.regex]`+(*UCP)+`
const:PCRE2_NEVER_UTF::
    Lock out const:PCRE2_UTF, e.g. via [.regex]`+(*UTF)+`
const:PCRE2_NO_AUTO_CAPTURE::
    Disable numbered capturing paren-
    theses (named ones available)
const:PCRE2_NO_AUTO_POSSESS::
    Disable auto-possessification
const:PCRE2_NO_DOTSTAR_ANCHOR::
    Disable automatic anchoring for [.regex]`+.*+`
const:PCRE2_NO_START_OPTIMIZE::
    Disable match-time start optimizations
const:PCRE2_NO_UTF_CHECK::
    Do not check the pattern for UTF validity
    (only relevant if const:PCRE2_UTF is set)
const:PCRE2_UCP::
    Use Unicode properties for [.regex]`\d`, [.regex]`\w`, etc.
const:PCRE2_UNGREEDY::
    Invert greediness of quantifiers
const:PCRE2_USE_OFFSET_LIMIT::
    Enable offset limit for unanchored matching
const:PCRE2_UTF::
    Treat pattern and subjects as UTF strings

PCRE2 must be built with Unicode support (the default) in order to use
const:PCRE2_UTF, const:PCRE2_UCP and related options.

Additional options may be set in the compile context via the
func:pcre2_set_compile_extra_options()
function.

If either of arg:errorptr or arg:erroroffset is const:NULL, the function returns
const:NULL immediately. Otherwise, the yield of this function is a pointer to a
private data structure that contains the compiled pattern, or const:NULL if an error
was detected. In the error case, a text error message can be obtained by
passing the value returned via the arg:errorptr argument to the
func:pcre2_get_error_message() function. The offset (in code units) where the
error was encountered is returned via the arg:erroroffset argument.

If there is no error, the value passed via arg:errorptr returns the message
"no error" if passed to func:pcre2_get_error_message(), and the value passed
via arg:erroroffset is zero.

There is a complete description of the PCRE2 native API, with more detail on
each option, in the
xref:pcre2api.adoc[`pcre2api`]
page, and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
