= pcre2_serialize_decode(3)
:doctype: manpage
:manname: pcre2_serialize_decode
:manpurpose: decode serialized compiled patterns
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 22 April 2022
:revdate: 22 April 2022

== Synopsis

[synopsis]
....
#include <pcre2.h>

int32_t pcre2_serialize_decode(pcre2_code **codes,
                               int32_t number_of_codes,
                               const uint8_t *bytes,
                               pcre2_general_context *gcontext);
....

== Description

This function decodes a serialized set of compiled patterns back into a list of
individual patterns. This is possible only on a host that is running the same
version of PCRE2, with the same code unit width, and the host must also have
the same endianness, pointer width and PCRE2_SIZE type. The arguments for
`pcre2_serialize_decode()` are:

[literal,subs=normal]
....
_codes_            pointer to a vector in which to build the list
_number_of_codes_  number of slots in the vector
_bytes_            the serialized byte stream
_gcontext_         pointer to a general context or NULL
....

The _bytes_ argument must point to a block of data that was originally
created by `pcre2_serialize_encode()`, though it may have been saved on
disc or elsewhere in the meantime. If there are more codes in the serialized
data than slots in the list, only those compiled patterns that will fit are
decoded. The yield of the function is the number of decoded patterns, or one of
the following negative error codes:

[literal,subs=normal]
....
PCRE2_ERROR_BADDATA   _number_of_codes_ is zero or less
PCRE2_ERROR_BADMAGIC  mismatch of id bytes in _bytes_
PCRE2_ERROR_BADMODE   mismatch of variable unit size or PCRE version
PCRE2_ERROR_NOMEMORY  memory allocation failed
PCRE2_ERROR_NULL      _codes_ or _bytes_ is NULL
....

PCRE2_ERROR_BADMAGIC may mean that the data is corrupt, or that it was compiled
on a system with different endianness.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the serialization functions in the
xref:pcre2serialize.adoc[`pcre2serialize`]
page.
