= pcre2_pattern_info(3)
:doctype: manpage
:manname: pcre2_pattern_info
:manpurpose: extract information about a pattern
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 14 February 2019
:revdate: 14 February 2019

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

int pcre2_pattern_info(const pcre2_code *code, uint32_t what,
                       void *where);
----

== Description

This function returns information about a compiled pattern. Its arguments are:

[.parameters]
arg:code::
    Pointer to a compiled regular expression pattern
arg:what::
    What information is required
arg:where::
    Where to put the information

The recognized values for the arg:what argument, and the information they
request are as follows:

[.values]
const:PCRE2_INFO_ALLOPTIONS::
    Final options after compiling
const:PCRE2_INFO_ARGOPTIONS::
    Options passed to func:pcre2_compile()
const:PCRE2_INFO_BACKREFMAX::
    Number of highest backreference
const:PCRE2_INFO_BSR::
    What [.regex]`\R` matches:
    const:PCRE2_BSR_UNICODE:::
        Unicode line endings
    const:PCRE2_BSR_ANYCRLF:::
        CR, LF, or CRLF only
const:PCRE2_INFO_CAPTURECOUNT::
    Number of capturing subpatterns
const:PCRE2_INFO_DEPTHLIMIT::
    Backtracking depth limit if set,
    otherwise const:PCRE2_ERROR_UNSET
const:PCRE2_INFO_EXTRAOPTIONS::
    Extra options that were passed in the
    compile context
const:PCRE2_INFO_FIRSTBITMAP::
    Bitmap of first code units, or [.c]`NULL`
const:PCRE2_INFO_FIRSTCODETYPE::
    Type of start-of-match information
    [.c]`0` nothing set
    [.c]`1` first code unit is set
    [.c]`2` start of string or after newline
const:PCRE2_INFO_FIRSTCODEUNIT::
    First code unit when type is [.c]`1`
const:PCRE2_INFO_FRAMESIZE::
    Size of backtracking frame
const:PCRE2_INFO_HASBACKSLASHC::
    Return [.c]`1` if pattern contains [.regex]`\C`
const:PCRE2_INFO_HASCRORLF::
    Return [.c]`1` if explicit CR or LF matches
    exist in the pattern
const:PCRE2_INFO_HEAPLIMIT::
    Heap memory limit if set,
    otherwise const:PCRE2_ERROR_UNSET
const:PCRE2_INFO_JCHANGED::
    Return [.c]`1` if [.regex]`(?J)` or [.regex]`(?-J)` was used
const:PCRE2_INFO_JITSIZE::
    Size of JIT compiled code, or [.c]`0`
const:PCRE2_INFO_LASTCODETYPE::
    Type of must-be-present information
    [.c]`0` nothing set
    [.c]`1` code unit is set
const:PCRE2_INFO_LASTCODEUNIT::
    Last code unit when type is [.c]`1`
const:PCRE2_INFO_MATCHEMPTY::
    [.c]`1` if the pattern can match an
    empty string, [.c]`0` otherwise
const:PCRE2_INFO_MATCHLIMIT::
    Match limit if set,
    otherwise const:PCRE2_ERROR_UNSET
const:PCRE2_INFO_MAXLOOKBEHIND::
    Length (in characters) of the longest
    lookbehind assertion
const:PCRE2_INFO_MINLENGTH::
    Lower bound length of matching strings
const:PCRE2_INFO_NAMECOUNT::
    Number of named subpatterns
const:PCRE2_INFO_NAMEENTRYSIZE::
    Size of name table entries
const:PCRE2_INFO_NAMETABLE::
    Pointer to name table
const:PCRE2_CONFIG_NEWLINE::
    Code for the newline sequence:
    const:PCRE2_NEWLINE_CR::
    const:PCRE2_NEWLINE_LF::
    const:PCRE2_NEWLINE_CRLF::
    const:PCRE2_NEWLINE_ANY::
    const:PCRE2_NEWLINE_ANYCRLF::
    const:PCRE2_NEWLINE_NUL::
const:PCRE2_INFO_RECURSIONLIMIT::
    Obsolete synonym for const:PCRE2_INFO_DEPTHLIMIT
const:PCRE2_INFO_SIZE::
    Size of compiled pattern

If arg:where is [.c]`NULL`, the function returns the amount of memory needed for
the requested information, in bytes. Otherwise, the arg:where argument must
point to an unsigned 32-bit integer ([.c]`uint32_t` variable), except for the
following arg:what values, when it must point to a variable of the type
shown:

[.values]
const:PCRE2_INFO_FIRSTBITMAP::
    [.c]`const uint8_t *`
const:PCRE2_INFO_JITSIZE::
    [.c]`size_t`
const:PCRE2_INFO_NAMETABLE::
    type:PCRE2_SPTR
const:PCRE2_INFO_SIZE::
    [.c]`size_t`

The yield of the function is zero on success or:

[.errors]
const:PCRE2_ERROR_NULL::
    the argument arg:code is [.c]`NULL`
const:PCRE2_ERROR_BADMAGIC::
    the "magic number" was not found
const:PCRE2_ERROR_BADOPTION::
    the value of arg:what is invalid
const:PCRE2_ERROR_BADMODE::
    the pattern was compiled in the wrong mode
const:PCRE2_ERROR_UNSET::
    the requested information is not set

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
