= pcre2_serialize_encode(3)
:doctype: manpage
:manname: pcre2_serialize_encode
:manpurpose: serialize compiled patterns for save/restore
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 13 August 2018
:revdate: 13 August 2018

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

int32_t pcre2_serialize_encode(const pcre2_code **codes,
                               int32_t number_of_codes,
                               uint8_t **serialized_bytes,
                               PCRE2_SIZE *serialized_size,
                               pcre2_general_context *gcontext);
----

== Description

This function encodes a list of compiled patterns into a byte stream that can
be saved on disc or elsewhere. Note that this is not an abstract format like
Java or .NET. Conversion of the byte stream back into usable compiled patterns
can only happen on a host that is running the same version of PCRE2, with the
same code unit width, and the host must also have the same endianness, pointer
width and type:PCRE2_SIZE type. The arguments for func:pcre2_serialize_encode()
are:

[.parameters]
arg:codes::
    pointer to a vector containing the list
arg:number_of_codes::
    number of slots in the vector
arg:serialized_bytes::
    set to point to the serialized byte stream
arg:serialized_size::
    set to the number of bytes in the byte stream
arg:gcontext::
    pointer to a general context or const:NULL

The context argument is used to obtain memory for the byte stream. When the
serialized data is no longer needed, it must be freed by calling
func:pcre2_serialize_free(). The yield of the function is the number of
serialized patterns, or one of the following negative error codes:

[.errors]
const:PCRE2_ERROR_BADDATA::
    arg:number_of_codes is zero or less
const:PCRE2_ERROR_BADMAGIC::
    mismatch of id bytes in one of the patterns
const:PCRE2_ERROR_MEMORY::
    memory allocation failed
const:PCRE2_ERROR_MIXEDTABLES::
    the patterns do not all use the same tables
const:PCRE2_ERROR_NULL::
    an argument other than arg:gcontext is const:NULL

const:PCRE2_ERROR_BADMAGIC means either that a pattern's code has been corrupted, or
that a slot in the vector does not point to a compiled pattern.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the serialization functions in the
xref:pcre2serialize.adoc[`pcre2serialize`]
page.
