= pcre2_set_compile_recursion_guard(3)
:doctype: manpage
:manname: pcre2_set_compile_recursion_guard
:manpurpose: set up a compile recursion guard function
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 26 November 2014
:revdate: 26 November 2014

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

int pcre2_set_compile_recursion_guard(pcre2_compile_context *ccontext,
                                      int (*guard)(uint32_t depth,
                                                   void *user_data),
                                      void *user_data);
----

== Description

This function defines, within a compile context, a function that is called
whenever func:pcre2_compile() starts to compile a parenthesized part of a
pattern. The first argument to the function gives the current depth of
parenthesis nesting, and the second is user data that is supplied when the
function is set up. The callout function should return zero if all is well, or
non-zero to force an error. This feature is provided so that applications can
check the available system stack space, in order to avoid running out. The
result of func:pcre2_set_compile_recursion_guard() is always zero.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
