= pcre2_jit_stack_assign(3)
:doctype: manpage
:manname: pcre2_jit_stack_assign
:manpurpose: assign stack for JIT matching
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 13 August 2018
:revdate: 13 August 2018

== Synopsis

[synopsis]
....
#include <pcre2.h>

void pcre2_jit_stack_assign(pcre2_match_context *mcontext,
                            pcre2_jit_callback callback,
                            void *callback_data);
....

== Description

This function provides control over the memory used by JIT as a run-time stack
when `pcre2_match()` or `pcre2_jit_match()` is called with a pattern
that has been successfully processed by the JIT compiler. The information that
determines which stack is used is put into a match context that is subsequently
passed to a matching function. The arguments of this function are:

[literal]
....
mcontext       a pointer to a match context
callback       a callback function
callback_data  a JIT stack or a value to be passed to the callback
....

If _mcontext_ is NULL, the function returns immediately, without doing
anything.

If _callback_ is NULL and _callback_data_ is NULL, an internal 32KiB
block on the machine stack is used.

If _callback_ is NULL and _callback_data_ is not NULL,
_callback_data_ must be a valid JIT stack, the result of calling
`pcre2_jit_stack_create()`.

If _callback_ not NULL, it is called with _callback_data_ as an
argument at the start of matching, in order to set up a JIT stack. If the
result is NULL, the internal 32KiB stack is used; otherwise the return value
must be a valid JIT stack, the result of calling
`pcre2_jit_stack_create()`.

You may safely use the same JIT stack for multiple patterns, as long as they
are all matched in the same thread. In a multithread application, each thread
must use its own JIT stack. For more details, see the
xref:pcre2jit.adoc[`pcre2jit`]
page.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
