= pcre2_callout_enumerate(3)
:doctype: manpage
:manname: pcre2_callout_enumerate
:manpurpose: enumerate callouts in a compiled pattern
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 23 March 2017
:revdate: 23 March 2017

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

int pcre2_callout_enumerate(
      const pcre2_code *code,
      int (*callback)(pcre2_callout_enumerate_block *callout_block,
                      void *callout_data),
      void *callout_data);
----

== Description

This function scans a compiled regular expression and calls the [.c]`callback()`
function for each callout within the pattern. The yield of the function is zero
for success and non-zero otherwise. The arguments are:

[.parameters]
arg:code::
      Points to the compiled pattern
arg:callback::
      The callback function
arg:callout_data::
      User data that is passed to the callback

The [.c]`callback()` function is passed a pointer to a data block containing
the following fields (not necessarily in this order):

[.members]
[.c]`uint32_t` arg:version::
      Block version number
[.c]`uint32_t` arg:callout_number::
      Number for numbered callouts
type:PCRE2_SIZE arg:pattern_position::
      Offset to next item in pattern
type:PCRE2_SIZE arg:next_item_length::
      Length of next item in pattern
type:PCRE2_SIZE arg:callout_string_offset::
      Offset to string within pattern
type:PCRE2_SIZE arg:callout_string_length::
      Length of callout string
type:PCRE2_SPTR arg:callout_string::
      Points to callout string or is [.c]`NULL`

The second argument passed to the [.c]`callback()` function is the callout data
that was passed to func:pcre2_callout_enumerate(). The [.c]`callback()`
function must return zero for success. Any other value causes the pattern scan
to stop, with the value being passed back as the result of
func:pcre2_callout_enumerate().

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
