= pcre2_get_mark(3)
:doctype: manpage
:manname: pcre2_get_mark
:manpurpose: get a (*MARK) name
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 13 January 2018
:revdate: 13 January 2018

== Synopsis

[synopsis]
....
#include <pcre2.h>

PCRE2_SPTR pcre2_get_mark(pcre2_match_data *match_data);
....

== Description

After a call of `pcre2_match()` that was passed the match block that is
this function's argument, this function returns a pointer to the last (pass:[*]MARK),
(pass:[*]PRUNE), or (pass:[*]THEN) name that was encountered during the matching process. The
name is zero-terminated, and is within the compiled pattern. The length of the
name is in the preceding code unit. If no name is available, NULL is returned.

After a successful match, the name that is returned is the last one on the
matching path. After a failed match or a partial match, the last encountered
name is returned.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
