= pcre2_set_newline(3)
:doctype: manpage
:manname: pcre2_set_newline
:manpurpose: set the newline convention
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 19 July 2017
:revdate: 19 July 2017

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

int pcre2_set_newline(pcre2_compile_context *ccontext,
                      uint32_t newline);
----

== Description

This function sets the newline convention within a compile context. This
specifies which character(s) are recognized as newlines when compiling and
matching patterns. The second argument must be one of:

[.values]
const:PCRE2_NEWLINE_CR::
    Carriage return only
const:PCRE2_NEWLINE_LF::
    Linefeed only
const:PCRE2_NEWLINE_CRLF::
    CR followed by LF only
const:PCRE2_NEWLINE_ANYCRLF::
    Any of the above
const:PCRE2_NEWLINE_ANY::
    Any Unicode newline sequence
const:PCRE2_NEWLINE_NUL::
    The NUL character (binary zero)

The result is zero for success or const:PCRE2_ERROR_BADDATA if the second argument is
invalid.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
