= pcre2_pattern_convert(3)
:doctype: manpage
:manname: pcre2_pattern_convert
:manpurpose: foreign pattern converter
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 12 July 2017
:revdate: 12 July 2017

== Synopsis

[synopsis]
....
#include <pcre2.h>

int pcre2_pattern_convert(PCRE2_SPTR pattern, PCRE2_SIZE plength,
                          uint32_t options, PCRE2_UCHAR **buffptr,
                          PCRE2_SIZE *bufflenptr,
                          pcre2_convert_context *ccontext);
....

== Description

This function is part of an experimental set of pattern conversion functions.
It converts a foreign pattern (for example, a glob) into a PCRE2 regular
expression pattern. Its arguments are:

[literal,subs=normal]
....
_pattern_     The foreign pattern
_length_      The length of the input pattern or PCRE2_ZERO_TERMINATED
_options_     Option bits
_buffer_      Pointer to pointer to output buffer, or NULL
_blength_     Pointer to output length field
_cvcontext_   Pointer to a convert context or NULL
....

The length of the converted pattern (excluding the terminating zero) is
returned via _blength_. If _buffer_ is NULL, the function just returns
the output length. If _buffer_ points to a NULL pointer, heap memory is
obtained for the converted pattern, using the allocator in the context if
present (or else `malloc()`), and the field pointed to by _buffer_ is
updated. If _buffer_ points to a non-NULL field, that must point to a
buffer whose size is in the variable pointed to by _blength_. This value is
updated.

The option bits are:

[literal]
....
PCRE2_CONVERT_UTF                     Input is UTF
PCRE2_CONVERT_NO_UTF_CHECK            Do not check UTF validity
PCRE2_CONVERT_POSIX_BASIC             Convert POSIX basic pattern
PCRE2_CONVERT_POSIX_EXTENDED          Convert POSIX extended pattern
PCRE2_CONVERT_GLOB                    ) Convert
PCRE2_CONVERT_GLOB_NO_WILD_SEPARATOR  )   various types
PCRE2_CONVERT_GLOB_NO_STARSTAR        )     of glob
....

The return value from `pcre2_pattern_convert()` is zero on success or a
non-zero PCRE2 error code.

The pattern conversion functions are described in the
xref:pcre2convert.adoc[`pcre2convert`]
documentation.
