= pcre2_match_data_create_from_pattern(3)
:doctype: manpage
:manname: pcre2_match_data_create_from_pattern
:manpurpose: create a match data block getting size from pattern
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 11 August 2025
:revdate: 11 August 2025

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

pcre2_match_data *pcre2_match_data_create_from_pattern(
      const pcre2_code *code, pcre2_general_context *gcontext);
----

== Description

This function creates a new match data block for holding the result of a match.
If the first argument is const:NULL, this function returns const:NULL, otherwise the first
argument points to a compiled pattern. The number of capturing parentheses
within the pattern is used to compute the number of pairs of offsets that are
required in the match data block. These form the "output vector" (ovector)
within the match data block, and are used to identify the matched string and
any captured substrings when matching with func:pcre2_match(). If you are
using func:pcre2_dfa_match(), which uses the output vector in a different way,
you should use func:pcre2_match_data_create() instead of this function.

The second argument points to a general context, for custom memory management,
or is const:NULL to use the same memory allocator that was used for the compiled
pattern. The result of the function is const:NULL if the memory for the block could
not be obtained or if const:NULL was provided as the first argument.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
