= pcre2_match_data_create(3)
:doctype: manpage
:manname: pcre2_match_data_create
:manpurpose: create a match data block
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 28 August 2021
:revdate: 28 August 2021

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

pcre2_match_data *pcre2_match_data_create(
      uint32_t oveccount, pcre2_general_context *gcontext);
----

== Description

This function creates a new match data block, which is used for holding the
result of a match. The first argument specifies the number of pairs of offsets
that are required. These form the "output vector" (ovector) within the match
data block, and are used to identify the matched string and any captured
substrings when matching with func:pcre2_match(), or a number of different
matches at the same point when used with func:pcre2_dfa_match(). There is
always one pair of offsets; if arg:oveccount is zero, it is treated as one.

The second argument points to a general context, for custom memory management,
or is [.c]`NULL` for system memory management. The result of the function is [.c]`NULL` if
the memory for the block could not be obtained.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
