= pcre2_substring_copy_bynumber(3)
:doctype: manpage
:manname: pcre2_substring_copy_bynumber
:manpurpose: extract numbered substring into given buffer
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 13 December 2014
:revdate: 13 December 2014

== Synopsis

[synopsis]
....
#include <pcre2.h>

int pcre2_substring_copy_bynumber(pcre2_match_data *match_data,
                                  uint32_t stringnumber,
                                  PCRE2_UCHAR *buffer,
                                  PCRE2_SIZE *sizeptr);
....

== Description

This is a convenience function for extracting a captured substring into a given
buffer. The arguments are:

[literal,subs=normal]
....
_match_data_    The match data block for the match
_number_        Number of the required substring
_buffer_        Buffer to receive the string
_bufflen_       Length of buffer
....

The _bufflen_ variable is updated with the length of the extracted string,
excluding the terminating zero. The yield of the function is zero for success
or one of the following error numbers:

[literal]
....
PCRE2_ERROR_NOSUBSTRING   there are no groups of that number
PCRE2_ERROR_UNAVAILBLE    the ovector was too small for that group
PCRE2_ERROR_UNSET         the group did not participate in the match
PCRE2_ERROR_NOMEMORY      the buffer is too small
....

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
