= pcre2_match_data_free(3)
:doctype: manpage
:manname: pcre2_match_data_free
:manpurpose: free a match data block
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 16 August 2023
:revdate: 16 August 2023

== Synopsis

[synopsis]
....
#include <pcre2.h>

void pcre2_match_data_free(pcre2_match_data *match_data);
....

== Description

If _match_data_ is NULL, this function does nothing. Otherwise,
_match_data_ must point to a match data block, which this function frees,
using the memory freeing function from the general context or compiled pattern
with which it was created, or `free()` if that was not set. If the match
data block was previously passed to `pcre2_match()`, it will have an
attached heapframe vector; this is also freed.

If the PCRE2_COPY_MATCHED_SUBJECT was used for a successful match using this
match data block, the copy of the subject that was referenced within the block
is also freed.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
