= pcre2posix(3)
:doctype: manpage
:manname: pcre2posix
:manpurpose: PCRE2 POSIX API
:description: The POSIX API to the PCRE2 8-bit library
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 27 November 2024
:revdate: 27 November 2024
:toc: right

== Synopsis

[source,c,role=prototype]
----
#include <pcre2posix.h>

int pcre2_regcomp(regex_t *preg, const char *pattern,
     int cflags);

int pcre2_regexec(const regex_t *preg, const char *string,
     size_t nmatch, regmatch_t pmatch[], int eflags);

size_t pcre2_regerror(int errcode, const regex_t *preg,
     char *errbuf, size_t errbuf_size);

void pcre2_regfree(regex_t *preg);
----

== Description

This set of functions provides a POSIX-style API for the PCRE2 regular
expression 8-bit library. There are no POSIX-style wrappers for PCRE2's 16-bit
and 32-bit libraries. See the
xref:pcre2api.adoc[`pcre2api`]
documentation for a description of PCRE2's native API, which contains much
additional functionality.

[IMPORTANT]
====
The functions described here are NOT thread-safe, and
should not be used in multi-threaded applications. They are also limited to
processing subjects that are not bigger than 2GB. Use the native API instead.
====

These functions are wrapper functions that ultimately call the PCRE2 native
API. Their prototypes are defined in the `pcre2posix.h` header file, and
they all have unique names starting with [.c]`pcre2_`. However, the
`pcre2posix.h` header also contains macro definitions that convert the
standard POSIX names such as [.c]`regcomp()` into func:pcre2_regcomp() etc. This
means that a program can use the usual POSIX names without running the risk of
accidentally linking with POSIX functions from a different library.

On Unix-like systems the PCRE2 POSIX library is called `libpcre2-posix`, so
can be accessed by adding `-lpcre2-posix` to the command for linking an
application. Because the POSIX functions call the native ones, it is also
necessary to add `-lpcre2-8`.

On Windows systems, if you are linking to a DLL version of the library, it is
recommended that const:PCRE2POSIX_SHARED is defined before including the
`pcre2posix.h` header, as it will allow for a more efficient way to
invoke the functions by adding the [.c]`__declspec(dllimport)` decorator.

Although they were not defined as prototypes in `pcre2posix.h`, releases
10.33 to 10.36 of the library contained functions with the POSIX names
[.c]`regcomp()` etc. These simply passed their arguments to the PCRE2
functions. These functions were provided for backwards compatibility with
earlier versions of PCRE2, which had only POSIX names. However, this has proved
troublesome in situations where a program links with several libraries, some of
which use PCRE2's POSIX interface while others use the real POSIX functions.
For this reason, the POSIX names have been removed since release 10.37.

Calling the header file `pcre2posix.h` avoids any conflict with other POSIX
libraries. It can, of course, be renamed or aliased as `regex.h`, which is
the "correct" name, if there is no clash. It provides two structure types,
type:regex_t for compiled internal forms, and type:regmatch_t for returning
captured substrings. It also defines some constants whose names start with
[.c]`REG_`; these are used for setting options and identifying error codes.

== Using the POSIX functions

Note that these functions are just POSIX-style wrappers for PCRE2's native API.
They do not give POSIX regular expression behaviour, and they are not
thread-safe or even POSIX compatible.

Those POSIX option bits that can reasonably be mapped to PCRE2 native options
have been implemented. In addition, the option const:REG_EXTENDED is defined with the
value zero. This has no effect, but since programs that are written to the
POSIX interface often use it, this makes it easier to slot in PCRE2 as a
replacement library. Other POSIX options are not even defined.

There are also some options that are not defined by POSIX. These have been
added at the request of users who want to make use of certain PCRE2-specific
features via the POSIX calling interface or to add BSD or GNU functionality.

When PCRE2 is called via these functions, it is only the API that is POSIX-like
in style. The syntax and semantics of the regular expressions themselves are
still those of Perl, subject to the setting of various PCRE2 options, as
described below. "POSIX-like in style" means that the API approximates to the
POSIX definition; it is not fully POSIX-compatible, and in multi-unit encoding
domains it is probably even less compatible.

The descriptions below use the actual names of the functions, but, as described
above, the standard POSIX names (without the [.c]`pcre2_` prefix) may also be
used.

== Compiling a pattern

The function func:pcre2_regcomp() is called to compile a pattern into an
internal form. By default, the pattern is a C string terminated by a binary
zero (but see const:REG_PEND below). The arg:preg argument is a pointer to a
type:regex_t structure that is used as a base for storing information about
the compiled regular expression. It is also used for input when const:REG_PEND is
set. The type:regex_t structure used by func:pcre2_regcomp() is defined in
`pcre2posix.h` and is not the same as the structure used by other libraries
that provide POSIX-style matching.

The argument arg:cflags is either zero, or contains one or more of the bits
defined by the following macros:

[.options]
const:REG_DOTALL::
     The const:PCRE2_DOTALL option is set when the regular expression is passed for
     compilation to the native function. Note that const:REG_DOTALL is not part of the
     POSIX standard.

const:REG_ICASE::
     The const:PCRE2_CASELESS option is set when the regular expression is passed for
     compilation to the native function.

const:REG_NEWLINE::
     The const:PCRE2_MULTILINE option is set when the regular expression is passed for
     compilation to the native function. Note that this does _not_ mimic the
     defined POSIX behaviour for const:REG_NEWLINE (see the section
     <<matching-newline-characters>>).

const:REG_NOSPEC::
     The const:PCRE2_LITERAL option is set when the regular expression is passed for
     compilation to the native function. This disables all meta characters in the
     pattern, causing it to be treated as a literal string. The only other options
     that are allowed with const:REG_NOSPEC are const:REG_ICASE, const:REG_NOSUB, const:REG_PEND, and
     const:REG_UTF. Note that const:REG_NOSPEC is not part of the POSIX standard.

const:REG_NOSUB::
     When a pattern that is compiled with this flag is passed to
     func:pcre2_regexec() for matching, the arg:nmatch and arg:pmatch arguments
     are ignored, and no captured strings are returned. Versions of the PCRE2 library
     prior to 10.22 used to set the const:PCRE2_NO_AUTO_CAPTURE compile option, but this
     no longer happens because it disables the use of backreferences.

const:REG_PEND::
     If this option is set, the arg:reg_endp field in the arg:preg structure
     (which has the type [.c]`+const char *+`) must be set to point to the character beyond
     the end of the pattern before calling func:pcre2_regcomp(). The pattern itself
     may now contain binary zeros, which are treated as data characters. Without
     const:REG_PEND, a binary zero terminates the pattern and the arg:re_endp field is
     ignored. This is a GNU extension to the POSIX standard and should be used with
     caution in software intended to be portable to other systems.

const:REG_UCP::
     The const:PCRE2_UCP option is set when the regular expression is passed for
     compilation to the native function. This causes PCRE2 to use Unicode properties
     when matching [.regex]`\d`, [.regex]`\w`, etc., instead of just recognizing ASCII values. Note
     that const:REG_UCP is not part of the POSIX standard.

const:REG_UNGREEDY::
     The const:PCRE2_UNGREEDY option is set when the regular expression is passed for
     compilation to the native function. Note that const:REG_UNGREEDY is not part of the
     POSIX standard.

const:REG_UTF::
     The const:PCRE2_UTF option is set when the regular expression is passed for
     compilation to the native function. This causes the pattern itself and all data
     strings used for matching it to be treated as UTF-8 strings. Note that const:REG_UTF
     is not part of the POSIX standard.

In the absence of these flags, no options are passed to the native function.
This means that the regex is compiled with PCRE2 default semantics. In
particular, the way it handles newline characters in the subject string is the
Perl way, not the POSIX way. Note that setting const:PCRE2_MULTILINE has only
_some_ of the effects specified for const:REG_NEWLINE. It does not affect the way
newlines are matched by the dot metacharacter (they are not) or by a negative
class such as [.regex]`+[^a]+` (they are).

The yield of func:pcre2_regcomp() is zero on success, and non-zero otherwise.
The arg:preg structure is filled in on success, and one other member of the
structure (as well as arg:re_endp) is public: arg:re_nsub contains the
number of capturing subpatterns in the regular expression. Various error codes
are defined in the header file.

[NOTE]
====
If the yield of func:pcre2_regcomp() is non-zero, you must not attempt
to use the contents of the arg:preg structure. If, for example, you pass it
to func:pcre2_regexec(), the result is undefined and your program is likely to
crash.
====

[[matching-newline-characters]]
== Matching newline characters

This area is not simple, because POSIX and Perl take different views of things.
It is not possible to get PCRE2 to obey POSIX semantics, but then PCRE2 was
never intended to be a POSIX engine. The following table lists the different
possibilities for matching newline characters in Perl and PCRE2:

[cols="2,1,2",options="header"]
|===
| |Default |Change with

|[.regex]`.` matches newline |no |const:PCRE2_DOTALL
|[.regex]`+[^a]+` matches newline |yes |not changeable
|[.regex]`$` matches newline at end |yes |const:PCRE2_DOLLAR_ENDONLY
|[.regex]`$` matches newline in middle |no |const:PCRE2_MULTILINE
|[.regex]`+^+` matches newline in middle |no |const:PCRE2_MULTILINE
|===

This is the equivalent table for a POSIX-compatible pattern matcher:

[cols="2,1,2",options="header"]
|===
| |Default |Change with

|[.regex]`.` matches newline |yes |const:REG_NEWLINE
|[.regex]`+[^a]+` matches newline |yes |const:REG_NEWLINE
|[.regex]`$` matches newline at end |no |const:REG_NEWLINE
|[.regex]`$` matches newline in middle |no |const:REG_NEWLINE
|[.regex]`+^+` matches newline in middle |no |const:REG_NEWLINE
|===

This behaviour is not what happens when PCRE2 is called via its POSIX
API. By default, PCRE2's behaviour is the same as Perl's, except that there is
no equivalent for const:PCRE2_DOLLAR_ENDONLY in Perl. In both PCRE2 and Perl, there
is no way to stop newline from matching [.regex]`+[^a]+`.

Default POSIX newline handling can be obtained by setting const:PCRE2_DOTALL and
const:PCRE2_DOLLAR_ENDONLY when calling func:pcre2_compile() directly, but there is
no way to make PCRE2 behave exactly as for the const:REG_NEWLINE action. When using
the POSIX API, passing const:REG_NEWLINE to PCRE2's func:pcre2_regcomp() function
causes const:PCRE2_MULTILINE to be passed to func:pcre2_compile(), and const:REG_DOTALL
passes const:PCRE2_DOTALL. There is no way to pass const:PCRE2_DOLLAR_ENDONLY.

== Matching a pattern

The function func:pcre2_regexec() is called to match a compiled pattern
arg:preg against a given arg:string, which is by default terminated by a
zero byte (but see const:REG_STARTEND below), subject to the options in arg:eflags.
These can be:

[.options]
const:REG_NOTBOL::
      The const:PCRE2_NOTBOL option is set when calling the underlying PCRE2 matching
      function.

const:REG_NOTEMPTY::
      The const:PCRE2_NOTEMPTY option is set when calling the underlying PCRE2 matching
      function. Note that const:REG_NOTEMPTY is not part of the POSIX standard. However,
      setting this option can give more POSIX-like behaviour in some situations.

const:REG_NOTEOL::
      The const:PCRE2_NOTEOL option is set when calling the underlying PCRE2 matching
      function.

const:REG_STARTEND::
      When this option is set, the subject string starts at [.c]`string + pmatch[0].rm_so`
      and ends at [.c]`string + pmatch[0].rm_eo`, which
      should point to the first character beyond the string. There may be binary
      zeros within the subject string, and indeed, using const:REG_STARTEND is the only
      way to pass a subject string that contains a binary zero.

+
Whatever the value of [.c]`+pmatch[0].rm_so+`, the offsets of the matched string
and any captured substrings are still given relative to the start of
arg:string itself. (Before PCRE2 release 10.30 these were given relative to
[.c]`string + pmatch[0].rm_so`, but this differs from other
implementations.)

+
This is a BSD extension, compatible with but not specified by IEEE Standard
1003.2 (POSIX.2), and should be used with caution in software intended to be
portable to other systems. Note that a non-zero arg:rm_so does not imply
const:REG_NOTBOL; const:REG_STARTEND affects only the location and length of the string,
not how it is matched. Setting const:REG_STARTEND and passing arg:pmatch as const:NULL
are mutually exclusive; the error const:REG_INVARG is returned.

If the pattern was compiled with the const:REG_NOSUB flag, no data about any matched
strings is returned. The arg:nmatch and arg:pmatch arguments of
func:pcre2_regexec() are ignored (except possibly as input for const:REG_STARTEND).

The value of arg:nmatch may be zero, and the value arg:pmatch may be const:NULL
(unless const:REG_STARTEND is set); in both these cases no data about any matched
strings is returned.

Otherwise, the portion of the string that was matched, and also any captured
substrings, are returned via the arg:pmatch argument, which points to an
array of arg:nmatch structures of type type:regmatch_t, containing the
members arg:rm_so and arg:rm_eo. These contain the byte offset to the first
character of each substring and the offset to the first character after the end
of each substring, respectively. The 0th element of the vector relates to the
entire portion of arg:string that was matched; subsequent elements relate to
the capturing subpatterns of the regular expression. Unused entries in the
array have both structure members set to -1.

type:regmatch_t as well as the type:regoff_t typedef it uses are defined in
`pcre2posix.h` and are not warranted to have the same size or layout as other
similarly named types from other libraries that provide POSIX-style matching.

A successful match yields a zero return; various error codes are defined in the
header file, of which const:REG_NOMATCH is the "expected" failure code.

== Error messages

The func:pcre2_regerror() function maps a non-zero errorcode from either
func:pcre2_regcomp() or func:pcre2_regexec() to a printable message. If
arg:preg is not const:NULL, the error should have arisen from the use of that
structure. A message terminated by a binary zero is placed in arg:errbuf. If
the buffer is too short, only the first arg:errbuf_size - 1 characters of the
error message are used. The yield of the function is the size of buffer needed
to hold the whole message, including the terminating zero. This value is
greater than arg:errbuf_size if the message was truncated.

== Memory usage

Compiling a regular expression causes memory to be allocated and associated
with the arg:preg structure. The function func:pcre2_regfree() frees all
such memory, after which arg:preg may no longer be used as a compiled
expression.

[discrete]
== Author

Philip Hazel +
Retired from University Computing Service +
Cambridge, England.

[discrete]
== Revision

Last updated: 27 November 2024 +
Copyright (C) 1997-2024 University of Cambridge.
