= pcre2_match_data_free(3)
:doctype: manpage
:manname: pcre2_match_data_free
:manpurpose: free a match data block
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 16 August 2023
:revdate: 16 August 2023

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

void pcre2_match_data_free(pcre2_match_data *match_data);
----

== Description

If arg:match_data is [.c]`NULL`, this function does nothing. Otherwise,
arg:match_data must point to a match data block, which this function frees,
using the memory freeing function from the general context or compiled pattern
with which it was created, or [.c]`free()` if that was not set. If the match
data block was previously passed to func:pcre2_match(), it will have an
attached heapframe vector; this is also freed.

If const:PCRE2_COPY_MATCHED_SUBJECT was used for a successful match using this
match data block, the copy of the subject that was referenced within the block
is also freed.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
