= pcre2_jit_stack_create(3)
:doctype: manpage
:manname: pcre2_jit_stack_create
:manpurpose: create a stack for JIT matching
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 23 January 2023
:revdate: 23 January 2023

== Synopsis

[synopsis]
....
#include <pcre2.h>

pcre2_jit_stack *pcre2_jit_stack_create(
      size_t startsize, size_t maxsize,
      pcre2_general_context *gcontext);
....

== Description

This function is used to create a stack for use by the code compiled by the JIT
compiler. The first two arguments are a starting size for the stack, and a
maximum size to which it is allowed to grow. The final argument is a general
context, for memory allocation functions, or NULL for standard memory
allocation. The result can be passed to the JIT run-time code by calling
`pcre2_jit_stack_assign()` to associate the stack with a compiled pattern,
which can then be processed by `pcre2_match()` or `pcre2_jit_match()`.
A maximum stack size of 512KiB to 1MiB should be more than enough for any
pattern. If the stack couldn't be allocated or the values passed were not
reasonable, NULL will be returned. For more details, see the
xref:pcre2jit.adoc[`pcre2jit`]
page.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
