= pcre2_serialize_get_number_of_codes(3)
:doctype: manpage
:manname: pcre2_serialize_get_number_of_codes
:manpurpose: get number of serialized compiled patterns
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 13 August 2018
:revdate: 13 August 2018

== Synopsis

[synopsis]
....
#include <pcre2.h>

int32_t pcre2_serialize_get_number_of_codes(const uint8_t *bytes);
....

== Description

The _bytes_ argument must point to a serialized byte stream that was
originally created by `pcre2_serialize_encode()` (though it may have been
saved on disc or elsewhere in the meantime). The function returns the number of
serialized patterns in the byte stream, or one of the following negative error
codes:

[literal,subs=normal]
....
PCRE2_ERROR_BADMAGIC  mismatch of id bytes in _bytes_
PCRE2_ERROR_BADMODE   mismatch of variable unit size or PCRE version
PCRE2_ERROR_NULL      the argument is NULL
....

PCRE2_ERROR_BADMAGIC may mean that the data is corrupt, or that it was compiled
on a system with different endianness.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the serialization functions in the
xref:pcre2serialize.adoc[`pcre2serialize`]
page.
