= pcre2_substring_copy_bynumber(3)
:doctype: manpage
:manname: pcre2_substring_copy_bynumber
:manpurpose: extract numbered substring into given buffer
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 13 December 2014
:revdate: 13 December 2014

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

int pcre2_substring_copy_bynumber(pcre2_match_data *match_data,
                                  uint32_t stringnumber,
                                  PCRE2_UCHAR *buffer,
                                  PCRE2_SIZE *sizeptr);
----

== Description

This is a convenience function for extracting a captured substring into a given
buffer. The arguments are:

[.parameters]
arg:match_data::
    The match data block for the match
arg:stringnumber::
    Number of the required substring
arg:buffer::
    Buffer to receive the string
arg:sizeptr::
    Length of buffer

The arg:sizeptr variable is updated with the length of the extracted string,
excluding the terminating zero. The yield of the function is zero for success
or one of the following error numbers:

[.errors]
const:PCRE2_ERROR_NOSUBSTRING::
    there are no groups of that number
const:PCRE2_ERROR_UNAVAILABLE::
    the ovector was too small for that group
const:PCRE2_ERROR_UNSET::
    the group did not participate in the match
const:PCRE2_ERROR_NOMEMORY::
    the buffer is too small

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
