= pcre2_jit_stack_assign(3)
:doctype: manpage
:manname: pcre2_jit_stack_assign
:manpurpose: assign stack for JIT matching
:manvolnum: 3
:manmanual: PCRE2
:mansource: PCRE2 10.49-DEV
:docdate: 13 August 2018
:revdate: 13 August 2018

== Synopsis

[source,c,role=prototype]
----
#include <pcre2.h>

void pcre2_jit_stack_assign(pcre2_match_context *mcontext,
                            pcre2_jit_callback callback,
                            void *callback_data);
----

== Description

This function provides control over the memory used by JIT as a run-time stack
when func:pcre2_match() or func:pcre2_jit_match() is called with a pattern
that has been successfully processed by the JIT compiler. The information that
determines which stack is used is put into a match context that is subsequently
passed to a matching function. The arguments of this function are:

[.parameters]
arg:mcontext::
    a pointer to a match context
arg:callback::
    a callback function
arg:callback_data::
    a JIT stack or a value to be passed to the callback

If arg:mcontext is const:NULL, the function returns immediately, without doing
anything.

If arg:callback is const:NULL and arg:callback_data is const:NULL, an internal 32KiB
block on the machine stack is used.

If arg:callback is const:NULL and arg:callback_data is not const:NULL,
arg:callback_data must be a valid JIT stack, the result of calling
func:pcre2_jit_stack_create().

If arg:callback not const:NULL, it is called with arg:callback_data as an
argument at the start of matching, in order to set up a JIT stack. If the
result is const:NULL, the internal 32KiB stack is used; otherwise the return value
must be a valid JIT stack, the result of calling
func:pcre2_jit_stack_create().

You may safely use the same JIT stack for multiple patterns, as long as they
are all matched in the same thread. In a multithread application, each thread
must use its own JIT stack. For more details, see the
xref:pcre2jit.adoc[`pcre2jit`]
page.

There is a complete description of the PCRE2 native API in the
xref:pcre2api.adoc[`pcre2api`]
page and a description of the POSIX API in the
xref:pcre2posix.adoc[`pcre2posix`]
page.
