'\" t
.\"     Title: pcre2_compile_context_free
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 28 June 2018
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_COMPILE_CONTEXT_FREE" "3" "28 June 2018" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_compile_context_free \- free a compile context
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBvoid\fP pcre2_compile_context_free(\fBpcre2_compile_context\fP *\fIccontext\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function frees the memory occupied by a compile context, using the memory
freeing function from the general context with which it was created, or
\f(CRfree()\fP if that was not set. If the argument is \f(CRNULL\fP, the function returns
immediately without doing anything.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.