'\" t
.\"     Title: pcre2_get_subject
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 22 September 2026
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_GET_SUBJECT" "3" "22 September 2026" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_get_subject \- get a match subject pointer
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBPCRE2_SPTR\fP pcre2_get_subject(\fBpcre2_match_data\fP *\fImatch_data\fP,
                             \fBPCRE2_SIZE\fP *\fIlengthptr\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
After a successful match, a partial match, or a failure to match, this function
returns the subject pointer that was passed to the matching function. For a
successful match with \fBPCRE2_COPY_MATCHED_SUBJECT\fP, it returns a pointer to
a copy of the subject that is owned by the match data block instead (except for
pcre2_jit_match() which ignores \fBPCRE2_COPY_MATCHED_SUBJECT\fP). The copy
is exactly the same length as the subject that was passed to the matching
function and is additionally zero\-terminated. The copy is freed when the match
data block is reused for another match or is freed. If there is any match error
other than \fBPCRE2_ERROR_NOMATCH\fP or \fBPCRE2_ERROR_PARTIAL\fP,
pcre2_get_subject() may return \f(CRNULL\fP.
.sp
If the \fIlengthptr\fP argument is not \f(CRNULL\fP, it receives the length of the
string which is returned (the subject string may contain embedded NUL characters).
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.