'\" t
.\"     Title: pcre2_set_max_pattern_compiled_length
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 09 June 2024
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SET_MAX_PATTERN_COMPILED_LENGTH" "3" "09 June 2024" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_set_max_pattern_compiled_length \- set the maximum length of a compiled pattern
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint\fP pcre2_set_max_pattern_compiled_length(
      \fBpcre2_compile_context\fP *\fIccontext\fP, \fBPCRE2_SIZE\fP \fIlength\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function sets, in a compile context, the maximum size (in bytes) for the
memory needed to hold the compiled version of a pattern that is using this
context. The result is always zero. If a pattern that is passed to
pcre2_compile() referencing this context needs more memory, an error is
generated. The default is the largest number that a \fBPCRE2_SIZE\fP variable can
hold, which is effectively unlimited.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.