'\" t
.\"     Title: pcre2_serialize_get_number_of_codes
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 13 August 2018
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SERIALIZE_GET_NUMBER_OF_CODES" "3" "13 August 2018" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_serialize_get_number_of_codes \- get number of serialized compiled patterns
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint32_t\fP pcre2_serialize_get_number_of_codes(\fBconst\fP \fBuint8_t\fP *\fIbytes\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
The \fIbytes\fP argument must point to a serialized byte stream that was
originally created by pcre2_serialize_encode() (though it may have been
saved on disc or elsewhere in the meantime). The function returns the number of
serialized patterns in the byte stream, or one of the following negative error
codes:
.sp
.RS 4
.PD 0
.TP 21
\fBPCRE2_ERROR_BADMAGIC\fP
.ad l
mismatch of id bytes in \fIbytes\fP
.TP 21
\fBPCRE2_ERROR_BADMODE\fP
.ad l
mismatch of variable unit size or PCRE version
.TP 21
\fBPCRE2_ERROR_NULL\fP
.ad l
the argument is \fBNULL\fP
.PD
.RE
.PP
.ad l
.sp
\fBPCRE2_ERROR_BADMAGIC\fP may mean that the data is corrupt, or that it was compiled
on a system with different endianness.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the serialization functions in the
\f(CRpcre2serialize\fP
page.