'\" t
.\"     Title: pcre2_jit_compile
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 22 August 2024
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_JIT_COMPILE" "3" "22 August 2024" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_jit_compile \- process a compiled pattern with the JIT compiler
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint\fP pcre2_jit_compile(\fBpcre2_code\fP *\fIcode\fP, \fBuint32_t\fP \fIoptions\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function requests JIT compilation, which, if the just\-in\-time compiler is
available, further processes a compiled pattern into machine code that executes
much faster than the pcre2_match() interpretive matching function. Full
details are given in the
\f(CRpcre2jit\fP
documentation.
.sp
The availability of JIT support can be tested by calling
pcre2_jit_compile() with a single option \fBPCRE2_JIT_TEST_ALLOC\fP (the
\fIcode\fP argument is ignored, so a \fBNULL\fP value is accepted). Such a call
returns zero if JIT is available and has a working allocator. Otherwise
it returns \fBPCRE2_ERROR_NOMEMORY\fP if JIT is available but cannot allocate
executable memory, or \fBPCRE2_ERROR_JIT_UNSUPPORTED\fP if JIT support is not
compiled.
.sp
Otherwise, the first argument must be a pointer that was returned by a
successful call to pcre2_compile(), and the second must contain one or
more of the following bits:
.sp
.RS 4
.PD 0
.TP 23
\fBPCRE2_JIT_COMPLETE\fP
.ad l
compile code for full matching
.TP 23
\fBPCRE2_JIT_PARTIAL_SOFT\fP
.ad l
compile code for soft partial matching
.TP 23
\fBPCRE2_JIT_PARTIAL_HARD\fP
.ad l
compile code for hard partial matching
.PD
.RE
.PP
.ad l
.sp
There is also an obsolete option called \fBPCRE2_JIT_INVALID_UTF\fP, which has been
superseded by the pcre2_compile() option \fBPCRE2_MATCH_INVALID_UTF\fP. The old
option is deprecated and may be removed in the future.
.sp
The yield of the function when called with any of the three options above is 0
for success, or a negative error code otherwise. In particular,
\fBPCRE2_ERROR_JIT_BADOPTION\fP is returned if JIT is not supported or if an unknown
bit is set in \fIoptions\fP. The function can also return \fBPCRE2_ERROR_NOMEMORY\fP
if JIT is unable to allocate executable memory for the compiler, even if it was
because of a system security restriction. In a few cases, the function may
return with \fBPCRE2_ERROR_JIT_UNSUPPORTED\fP for unsupported features.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.