'\" t
.\"     Title: pcre2syntax
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 14 October 2025
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2SYNTAX" "3" "14 October 2025" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2syntax \- PCRE2 syntax quick reference
.SH "PCRE2 REGULAR EXPRESSION SYNTAX SUMMARY"
.sp
The full syntax and semantics of the regular expression patterns that are
supported by PCRE2 are described in the
\f(CRpcre2pattern\fP
documentation. This document contains a quick\-reference summary of the pattern
syntax followed by the syntax of replacement strings in substitution function.
The full description of the latter is in the
\f(CRpcre2api\fP
documentation.
.SH "QUOTING"
.sp
.ss \n[.ss]
.nf
.fam C
\(rsx         where x is non\-alphanumeric is a literal x
\(rsQ...\(rsE    treat enclosed characters as literal
.fam
.fi
.ss \n[.ss] 0
.sp
Note that white space inside \f(CR\(rsQ...\(rsE\fP is always treated as literal, even if
\fBPCRE2_EXTENDED\fP is set, causing most other white space to be ignored. Note also
that PCRE2\(cqs handling of \f(CR\(rsQ...\(rsE\fP has some differences from Perl\(cqs. See the
\f(CRpcre2pattern\fP
documentation for details.
.SH "BRACED ITEMS"
.sp
With one exception, wherever brace characters \f(CR{\fP and \f(CR}\fP are required to enclose
data for constructions such as \f(CR\(rsg{2}\fP or \f(CR\(rsk{name}\fP, space and/or horizontal tab
characters that follow { or precede } are allowed and are ignored. In the case
of quantifiers, they may also appear before or after the comma. The exception
is \f(CR\(rsu{...}\fP which is not Perl\-compatible and is recognized only when
\fBPCRE2_EXTRA_ALT_BSUX\fP is set. This is an ECMAScript compatibility feature, and
follows ECMAScript\(cqs behaviour.
.SH "ESCAPED CHARACTERS"
.sp
This table applies to ASCII and Unicode environments. An unrecognized escape
sequence causes an error.
.sp
.ss \n[.ss]
.nf
.fam C
\(rsa         alarm, that is, the BEL character (hex 07)
\(rscx        "control\-x", where x is a non\-control ASCII character
\(rse         escape (hex 1B)
\(rsf         form feed (hex 0C)
\(rsn         newline (hex 0A)
\(rsr         carriage return (hex 0D)
\(rst         tab (hex 09)
\(rs0dd       character with octal code 0dd
\(rsddd       character with octal code ddd, or backreference
\(rso{ddd..}  character with octal code ddd..
\(rsN{U+hh..} character with Unicode code point hh.. (Unicode mode only)
\(rsxhh       character with hex code hh
\(rsx{hh..}   character with hex code hh..
.fam
.fi
.ss \n[.ss] 0
.sp
\f(CR\(rsN{U+hh..}\fP is synonymous with \f(CR\(rsx{hh..}\fP but is not supported in environments
that use EBCDIC code (mainly IBM mainframes). Note that \(rsN not followed by an
opening curly bracket has a different meaning (see below).
.sp
If \fBPCRE2_ALT_BSUX\fP or \fBPCRE2_EXTRA_ALT_BSUX\fP is set ("ALT_BSUX mode"), the
following are also recognized:
.sp
.ss \n[.ss]
.nf
.fam C
\(rsU         the character "U"
\(rsuhhhh     character with hex code hhhh
\(rsu{hh..}   character with hex code hh.. but only for EXTRA_ALT_BSUX
.fam
.fi
.ss \n[.ss] 0
.sp
When \f(CR\(rsx\fP is not followed by \f(CR{\fP, one or two hexadecimal digits are read,
but in ALT_BSUX mode \f(CR\(rsx\fP must be followed by two hexadecimal digits to be
recognized as a hexadecimal escape; otherwise it matches a literal "x".
Likewise, if \f(CR\(rsu\fP (in ALT_BSUX mode) is not followed by four hexadecimal digits
or (in EXTRA_ALT_BSUX mode) a sequence of hex digits in curly brackets, it
matches a literal "u".
.sp
Note that \f(CR\(rs0dd\fP is always an octal code. The treatment of backslash followed by
a non\-zero digit is complicated; for details see the section
"Non\-printing characters"
in the
\f(CRpcre2pattern\fP
documentation, where details of escape processing in EBCDIC environments are
also given.
.SH "CHARACTER TYPES"
.sp
.ss \n[.ss]
.nf
.fam C
\&.          any character except newline;
             in dotall mode, any character whatsoever
\(rsC         one code unit, even in UTF mode (best avoided)
\(rsd         a decimal digit
\(rsD         a character that is not a decimal digit
\(rsh         a horizontal white space character
\(rsH         a character that is not a horizontal white space character
\(rsN         a character that is not a newline
\(rsp{_xx_}     a character with the _xx_ property
\(rsP{_xx_}     a character without the _xx_ property
\(rsR         a newline sequence
\(rss         a white space character
\(rsS         a character that is not a white space character
\(rsv         a vertical white space character
\(rsV         a character that is not a vertical white space character
\(rsw         a "word" character
\(rsW         a "non\-word" character
\(rsX         a Unicode extended grapheme cluster
.fam
.fi
.ss \n[.ss] 0
.sp
\f(CR\(rsC\fP is dangerous because it may leave the current matching point in the middle
of a UTF\-8 or UTF\-16 character. The application can lock out the use of \(rsC by
setting the \fBPCRE2_NEVER_BACKSLASH_C\fP option. It is also possible to build PCRE2
with the use of \f(CR\(rsC\fP permanently disabled.
.sp
By default, \f(CR\(rsd\fP, \f(CR\(rss\fP, and \f(CR\(rsw\fP match only ASCII characters, even in UTF\-8 mode
or in the 16\-bit and 32\-bit libraries. However, if locale\-specific matching is
happening, \(rss and \(rsw may also match characters with code points in the range
128\-255. If the \fBPCRE2_UCP\fP option is set, the behaviour of these escape
sequences is changed to use Unicode properties and they match many more
characters, but there are some option settings that can restrict individual
sequences to matching only ASCII characters.
.sp
Property descriptions in \f(CR\(rsp\fP and \f(CR\(rsP\fP are matched caselessly; hyphens,
underscores, and ASCII white space characters are ignored, in accordance with
Unicode\(cqs "loose matching" rules. For example, \f(CR\(rsp{Bidi_Class=al}\fP is the same
as \f(CR\(rsp{ bidi class = AL }\fP.
.SH "GENERAL CATEGORY PROPERTIES FOR \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
.ss \n[.ss]
.nf
.fam C
C          Other
Cc         Control
Cf         Format
Cn         Unassigned
Co         Private use
Cs         Surrogate
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
L          Letter
Lc         Cased letter, the union of Ll, Lu, and Lt
L&         Synonym of Lc
Ll         Lower case letter
Lm         Modifier letter
Lo         Other letter
Lt         Title case letter
Lu         Upper case letter
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
M          Mark
Mc         Spacing mark
Me         Enclosing mark
Mn         Non\-spacing mark
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
N          Number
Nd         Decimal number
Nl         Letter number
No         Other number
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
P          Punctuation
Pc         Connector punctuation
Pd         Dash punctuation
Pe         Close punctuation
Pf         Final punctuation
Pi         Initial punctuation
Po         Other punctuation
Ps         Open punctuation
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
S          Symbol
Sc         Currency symbol
Sk         Modifier symbol
Sm         Mathematical symbol
So         Other symbol
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
Z          Separator
Zl         Line separator
Zp         Paragraph separator
Zs         Space separator
.fam
.fi
.ss \n[.ss] 0
.sp
From release 10.45, when caseless matching is set, Ll, Lu, and Lt are all
equivalent to Lc.
.SH "PCRE2 SPECIAL CATEGORY PROPERTIES FOR \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
.ss \n[.ss]
.nf
.fam C
Xan        Alphanumeric: union of properties L and N
Xps        POSIX space: property Z or tab, NL, VT, FF, CR
Xsp        Perl space: property Z or tab, NL, VT, FF, CR
Xuc        Universally\-named character: one that can be
             represented by a Universal Character Name
Xwd        Perl word: property Xan or underscore
.fam
.fi
.ss \n[.ss] 0
.sp
Perl and POSIX space are now the same. Perl added VT to its space character set
at release 5.18.
.SH "BINARY PROPERTIES FOR \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
Unicode defines a number of binary properties, that is, properties whose only
values are true or false. You can obtain a list of those that are recognized by
\f(CR\(rsp\fP and \f(CR\(rsP\fP, along with their abbreviations, by running this command:
.sp
.ss \n[.ss]
.nf
.fam C
pcre2test \-LP
.fam
.fi
.ss \n[.ss] 0
.SH "SCRIPT MATCHING WITH \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
Many script names and their 4\-letter abbreviations are recognized in
\f(CR\(rsp{sc:...}\fP or \f(CR\(rsp{scx:...}\fP items, or on their own with \f(CR\(rsp\fP (and also \f(CR\(rsP\fP of
course). You can obtain a list of these scripts by running this command:
.sp
.ss \n[.ss]
.nf
.fam C
pcre2test \-LS
.fam
.fi
.ss \n[.ss] 0
.SH "THE BIDI_CLASS PROPERTY FOR \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
.ss \n[.ss]
.nf
.fam C
\(rsp{Bidi_Class:<class>}   matches a character with the given class
\(rsp{BC:<class>}           matches a character with the given class
.fam
.fi
.ss \n[.ss] 0
.sp
The recognized classes are:
.sp
.ss \n[.ss]
.nf
.fam C
AL          Arabic letter
AN          Arabic number
B           paragraph separator
BN          boundary neutral
CS          common separator
EN          European number
ES          European separator
ET          European terminator
FSI         first strong isolate
L           left\-to\-right
LRE         left\-to\-right embedding
LRI         left\-to\-right isolate
LRO         left\-to\-right override
NSM         non\-spacing mark
ON          other neutral
PDF         pop directional format
PDI         pop directional isolate
R           right\-to\-left
RLE         right\-to\-left embedding
RLI         right\-to\-left isolate
RLO         right\-to\-left override
S           segment separator
WS          white space
.fam
.fi
.ss \n[.ss] 0
.SH "CHARACTER CLASSES"
.sp
.ss \n[.ss]
.nf
.fam C
[...]       positive character class
[^...]      negative character class
[x\-y]       range (can be used for hex characters)
[[:xxx:]]   positive POSIX named set
[[:^xxx:]]  negative POSIX named set
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
alnum       alphanumeric
alpha       alphabetic
ascii       0\-127
blank       space or tab
cntrl       control character
digit       decimal digit
graph       printing, excluding space
lower       lower case letter
print       printing, including space
punct       printing, excluding alphanumeric
space       white space
upper       upper case letter
word        same as \(rsw
xdigit      hexadecimal digit
.fam
.fi
.ss \n[.ss] 0
.sp
In PCRE2, POSIX character set names recognize only ASCII characters by default,
but some of them use Unicode properties if \fBPCRE2_UCP\fP is set. You can use
\f(CR\(rsQ...\(rsE\fP inside a character class.
.sp
When \fBPCRE2_ALT_EXTENDED_CLASS\fP is set, UTS#18 extended character classes may be
used, allowing nested character classes, combined using set operators.
.sp
.ss \n[.ss]
.nf
.fam C
[x&&[^y]]   UTS#18 extended character class
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
x||y        set union (OR)
x&&y        set intersection (AND)
x\-\-y        set difference (AND NOT)
x~~y        set symmetric difference (XOR)
.fam
.fi
.ss \n[.ss] 0
.SH "PERL EXTENDED CHARACTER CLASSES"
.sp
.ss \n[.ss]
.nf
.fam C
(?[...])                Perl extended character class
(?[\(rsp{Thai} & \(rsp{Nd}])  operators; white space ignored
(?[(x \- y) & z])        parentheses for grouping
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
(?[ [^3] & \(rsp{Nd} ])    [...] is a nested ordinary class
(?[ [:alpha:] \- [z] ])  POSIX set is allowed outside [...]
(?[ \(rsd \- [3] ])         backslash\-escaped set is allowed outside [...]
(?[ !\(rsn & [:ascii:] ])  backslash\-escaped character is allowed outside [...]
                    all other characters or ranges must be enclosed in [...]
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
x|y, x+y                set union (OR)
x&y                     set intersection (AND)
x\-y                     set difference (AND NOT)
x^y                     set symmetric difference (XOR)
!x                      set complement (NOT)
.fam
.fi
.ss \n[.ss] 0
.sp
Inside a Perl extended character class, [...] switches mode to be interpreted
as an ordinary character class. Outside of a nested [...], the only items
permitted are backslash\-escapes, POSIX sets, operators, and parentheses. Inside
a nested ordinary class, ^ has its usual meaning (inverts the class when used
as the first character); outside of a nested class, ^ is the XOR operator.
.SH "QUANTIFIERS"
.sp
.ss \n[.ss]
.nf
.fam C
?           0 or 1, greedy
?+          0 or 1, possessive
??          0 or 1, lazy
*           0 or more, greedy
*+          0 or more, possessive
*?          0 or more, lazy
+           1 or more, greedy
++          1 or more, possessive
+?          1 or more, lazy
{n}         exactly n
{n,m}       at least n, no more than m, greedy
{n,m}+      at least n, no more than m, possessive
{n,m}?      at least n, no more than m, lazy
{n,}        n or more, greedy
{n,}+       n or more, possessive
{n,}?       n or more, lazy
{,m}        zero up to m, greedy
{,m}+       zero up to m, possessive
{,m}?       zero up to m, lazy
.fam
.fi
.ss \n[.ss] 0
.SH "ANCHORS AND SIMPLE ASSERTIONS"
.sp
.ss \n[.ss]
.nf
.fam C
\(rsb          word boundary
\(rsB          not a word boundary
^           start of subject
              also after an internal newline in multiline mode
              (after any newline if PCRE2_ALT_CIRCUMFLEX is set)
\(rsA          start of subject
$           end of subject
              also before newline at end of subject
              also before internal newline in multiline mode
\(rsZ          end of subject
              also before newline at end of subject
\(rsz          end of subject
\(rsG          first matching position in subject
.fam
.fi
.ss \n[.ss] 0
.SH "REPORTED MATCH POINT SETTING"
.sp
.ss \n[.ss]
.nf
.fam C
\(rsK          set reported start of match
.fam
.fi
.ss \n[.ss] 0
.sp
From release 10.38 \(rsK is not permitted by default in lookaround assertions,
for compatibility with Perl. However, if the \fBPCRE2_EXTRA_ALLOW_LOOKAROUND_BSK\fP
option is set, the previous behaviour is re\-enabled. When this option is set,
\(rsK is honoured in positive assertions, but ignored in negative ones.
.SH "ALTERNATION"
.sp
.ss \n[.ss]
.nf
.fam C
expr|expr|expr...
.fam
.fi
.ss \n[.ss] 0
.SH "CAPTURING"
.sp
.ss \n[.ss]
.nf
.fam C
(...)           capture group
(?<name>...)    named capture group (Perl)
(?\*(Aqname\*(Aq...)    named capture group (Perl)
(?P<name>...)   named capture group (Python)
(?:...)         non\-capture group
(?|...)         non\-capture group; reset group numbers for
                 capture groups in each alternative
.fam
.fi
.ss \n[.ss] 0
.sp
In non\-UTF modes, names may contain underscores and ASCII letters and digits;
in UTF modes, any Unicode letters and Unicode decimal digits are permitted. In
both cases, a name must not start with a digit.
.SH "ATOMIC GROUPS"
.sp
.ss \n[.ss]
.nf
.fam C
(?>...)         atomic non\-capture group
(*atomic:...)   atomic non\-capture group
.fam
.fi
.ss \n[.ss] 0
.SH "COMMENT"
.sp
.ss \n[.ss]
.nf
.fam C
(?#....)        comment (not nestable)
.fam
.fi
.ss \n[.ss] 0
.SH "OPTION SETTING"
.sp
Changes of these options within a group are automatically cancelled at the end
of the group.
.sp
.ss \n[.ss]
.nf
.fam C
(?a)            all ASCII options
(?aD)           restrict \(rsd to ASCII in UCP mode
(?aS)           restrict \(rss to ASCII in UCP mode
(?aW)           restrict \(rsw to ASCII in UCP mode
(?aP)           restrict all POSIX classes to ASCII in UCP mode
(?aT)           restrict POSIX digit classes to ASCII in UCP mode
(?i)            caseless
(?J)            allow duplicate named groups
(?m)            multiline
(?n)            no auto capture
(?r)            restrict caseless to either ASCII or non\-ASCII
(?s)            single line (dotall)
(?U)            default ungreedy (lazy)
(?x)            ignore white space except in classes or \(rsQ...\(rsE
(?xx)           as (?x) but also ignore space and tab in classes
(?\-...)         unset the given option(s)
(?^)            unset imnrsx options
.fam
.fi
.ss \n[.ss] 0
.sp
(?aP) implies (?aT) as well, though this has no additional effect. However, it
means that (?\-aP) also implies (?\-aT) and disables all ASCII restrictions for
POSIX classes.
.sp
Unsetting x or xx unsets both. Several options may be set at once, and a
mixture of setting and unsetting such as (?i\-x) is allowed, but there may be
only one hyphen. Setting (but no unsetting) is allowed after (?^ for example
(?^in). An option setting may appear at the start of a non\-capture group, for
example (?i:...).
.sp
The following are recognized only at the very start of a pattern or after one
of the newline or \(rsR sequences or options with similar syntax. More than one
of them may appear. For the first three, d is a decimal number.
.sp
.ss \n[.ss]
.nf
.fam C
(*LIMIT_DEPTH=d)     set the backtracking limit to d
(*LIMIT_HEAP=d)      set the heap size limit to d * 1024 bytes
(*LIMIT_MATCH=d)     set the match limit to d
(*CASELESS_RESTRICT) set PCRE2_EXTRA_CASELESS_RESTRICT when matching
(*NOTEMPTY)          set PCRE2_NOTEMPTY when matching
(*NOTEMPTY_ATSTART)  set PCRE2_NOTEMPTY_ATSTART when matching
(*NO_AUTO_POSSESS)   no auto\-possessification (PCRE2_NO_AUTO_POSSESS)
(*NO_DOTSTAR_ANCHOR) no .* anchoring (PCRE2_NO_DOTSTAR_ANCHOR)
(*NO_JIT)            disable JIT optimization
(*NO_START_OPT)      no start\-match optimization (PCRE2_NO_START_OPTIMIZE)
(*TURKISH_CASING)    set PCRE2_EXTRA_TURKISH_CASING when matching
(*UTF)               set appropriate UTF mode for the library in use
(*UCP)               set PCRE2_UCP (use Unicode properties for \(rsd etc)
.fam
.fi
.ss \n[.ss] 0
.sp
Note that LIMIT_DEPTH, LIMIT_HEAP, and LIMIT_MATCH can only reduce the value of
the limits set by the caller of pcre2_match() or pcre2_dfa_match(),
not increase them. LIMIT_RECURSION is an obsolete synonym for LIMIT_DEPTH. The
application can lock out the use of \f(CR(*UTF)\fP and \f(CR(*UCP)\fP by setting the
\fBPCRE2_NEVER_UTF\fP or \fBPCRE2_NEVER_UCP\fP options, respectively, at compile time.
.SH "NEWLINE CONVENTION"
.sp
These are recognized only at the very start of the pattern or after option
settings with a similar syntax.
.sp
.ss \n[.ss]
.nf
.fam C
(*CR)           carriage return only
(*LF)           linefeed only
(*CRLF)         carriage return followed by linefeed
(*ANYCRLF)      all three of the above
(*ANY)          any Unicode newline sequence
(*NUL)          the NUL character (binary zero)
.fam
.fi
.ss \n[.ss] 0
.SH "WHAT \(rsR MATCHES"
.sp
These are recognized only at the very start of the pattern or after option
setting with a similar syntax.
.sp
.ss \n[.ss]
.nf
.fam C
(*BSR_ANYCRLF)  CR, LF, or CRLF
(*BSR_UNICODE)  any Unicode newline sequence
.fam
.fi
.ss \n[.ss] 0
.SH "LOOKAHEAD AND LOOKBEHIND ASSERTIONS"
.sp
.ss \n[.ss]
.nf
.fam C
(?=...)                     )
(*pla:...)                  ) positive lookahead
(*positive_lookahead:...)   )
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
(?!...)                     )
(*nla:...)                  ) negative lookahead
(*negative_lookahead:...)   )
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
(?<=...)                    )
(*plb:...)                  ) positive lookbehind
(*positive_lookbehind:...)  )
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
(?<!...)                    )
(*nlb:...)                  ) negative lookbehind
(*negative_lookbehind:...)  )
.fam
.fi
.ss \n[.ss] 0
.sp
Each top\-level branch of a lookbehind must have a limit for the number of
characters it matches. If any branch can match a variable number of characters,
the maximum for each branch is limited to a value set by the caller of
pcre2_compile() or defaulted. The default is set when PCRE2 is built
(ultimate default 255). If every branch matches a fixed number of characters,
the limit for each branch is 65535 characters.
.SH "NON\-ATOMIC LOOKAROUND ASSERTIONS"
.sp
These assertions are specific to PCRE2 and are not Perl\-compatible.
.sp
.ss \n[.ss]
.nf
.fam C
(?*...)                                )
(*napla:...)                           ) synonyms
(*non_atomic_positive_lookahead:...)   )
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
(?<*...)                               )
(*naplb:...)                           ) synonyms
(*non_atomic_positive_lookbehind:...)  )
.fam
.fi
.ss \n[.ss] 0
.SH "SUBSTRING SCAN ASSERTION"
.sp
This feature is not Perl\-compatible.
.sp
.ss \n[.ss]
.nf
.fam C
(*scan_substring:(grouplist)...)  scan captured substring
(*scs:(grouplist)...)             scan captured substring
.fam
.fi
.ss \n[.ss] 0
.sp
The comma\-separated list "grouplist" may identify groups in any of the
following ways:
.sp
.ss \n[.ss]
.nf
.fam C
n       absolute reference
+n      relative reference
\-n      relative reference
<name>  name
\*(Aqname\*(Aq  name
.fam
.fi
.ss \n[.ss] 0
.SH "SCRIPT RUNS"
.sp
.ss \n[.ss]
.nf
.fam C
(*script_run:...)           ) script run, can be backtracked into
(*sr:...)                   )
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
(*atomic_script_run:...)    ) atomic script run
(*asr:...)                  )
.fam
.fi
.ss \n[.ss] 0
.SH "BACKREFERENCES"
.sp
.ss \n[.ss]
.nf
.fam C
\(rsn              reference by number (can be ambiguous)
\(rsgn             reference by number
\(rsg{n}           reference by number
\(rsg+n            relative reference by number (PCRE2 extension)
\(rsg\-n            relative reference by number
\(rsg{+n}          relative reference by number (PCRE2 extension)
\(rsg{\-n}          relative reference by number
\(rsk<name>        reference by name (Perl)
\(rsk\*(Aqname\*(Aq        reference by name (Perl)
\(rsg{name}        reference by name (Perl)
\(rsk{name}        reference by name (.NET)
(?P=name)       reference by name (Python)
.fam
.fi
.ss \n[.ss] 0
.SH "SUBROUTINE REFERENCES (POSSIBLY RECURSIVE)"
.sp
.ss \n[.ss]
.nf
.fam C
(?R)            recurse whole pattern
(?n)            call subroutine by absolute number
(?+n)           call subroutine by relative number
(?\-n)           call subroutine by relative number
(?&name)        call subroutine by name (Perl)
(?P>name)       call subroutine by name (Python)
\(rsg<name>        call subroutine by name (Oniguruma)
\(rsg\*(Aqname\*(Aq        call subroutine by name (Oniguruma)
\(rsg<n>           call subroutine by absolute number (Oniguruma)
\(rsg\*(Aqn\*(Aq           call subroutine by absolute number (Oniguruma)
\(rsg<+n>          call subroutine by relative number (PCRE2 extension)
\(rsg\*(Aq+n\*(Aq          call subroutine by relative number (PCRE2 extension)
\(rsg<\-n>          call subroutine by relative number (PCRE2 extension)
\(rsg\*(Aq\-n\*(Aq          call subroutine by relative number (PCRE2 extension)
.fam
.fi
.ss \n[.ss] 0
.sp
The variants using parentheses (?...) may also specify a list of capture groups
to return, which shall be retained in the calling subexpression if set during
the recursion (this feature is not supported by Perl).
.sp
.ss \n[.ss]
.nf
.fam C
(?R(grouplist))       recurse whole pattern, returning capture groups
                        (PCRE2 extension)
(?n(grouplist))       )
(?+n(grouplist))      ) call subroutine, returning capture groups
(?\-n(grouplist))      )   (PCRE2 extension)
(?&name(grouplist))   )
(?P>name(grouplist))  )
.fam
.fi
.ss \n[.ss] 0
.sp
The comma\-separated list "grouplist" uses the same syntax as
\f(CR(*scan_substring:(grouplist)...)\fP, and may identify groups in any of the
following ways:
.sp
.ss \n[.ss]
.nf
.fam C
n       absolute reference
+n      relative reference
\-n      relative reference
<name>  name
\*(Aqname\*(Aq  name
.fam
.fi
.ss \n[.ss] 0
.SH "CONDITIONAL PATTERNS"
.sp
.ss \n[.ss]
.nf
.fam C
(?(condition)yes\-pattern)
(?(condition)yes\-pattern|no\-pattern)
.fam
.fi
.ss \n[.ss] 0
.sp
.ss \n[.ss]
.nf
.fam C
(?(n)                absolute reference condition
(?(+n)               relative reference condition (PCRE2 extension)
(?(\-n)               relative reference condition (PCRE2 extension)
(?(<name>)           named reference condition (Perl)
(?(\*(Aqname\*(Aq)           named reference condition (Perl)
(?(name)             named reference condition (PCRE2, deprecated)
(?(R)                overall recursion condition
(?(Rn)               specific numbered group recursion condition
(?(R&name)           specific named group recursion condition
(?(DEFINE)           define groups for reference
(?(VERSION[>]=n[.m]) test PCRE2 version
(?(assert)           assertion condition
.fam
.fi
.ss \n[.ss] 0
.sp
Note the ambiguity of (?\(rg and (?(Rn) which might be named reference
conditions or recursion tests. Such a condition is interpreted as a reference
condition if the relevant named group exists.
.sp
The parts within brackets for the VERSION conditional syntax could be ommited.
The fractional part of the version number defaults to 0 in that case.
.SH "BACKTRACKING CONTROL"
.sp
All backtracking control verbs may be in the form \f(CR(*VERB:NAME)\fP. For \f(CR(*MARK)\fP the
name is mandatory, for the others it is optional. \f(CR(*SKIP)\fP changes its behaviour
if :NAME is present. The others just set a name for passing back to the caller,
but this is not a name that \f(CR(*SKIP)\fP can see. The following act immediately they
are reached:
.sp
.ss \n[.ss]
.nf
.fam C
(*ACCEPT)       force successful match
(*FAIL)         force backtrack; synonym (*F)
(*MARK:NAME)    set name to be passed back; synonym (*:NAME)
.fam
.fi
.ss \n[.ss] 0
.sp
The following act only when a subsequent match failure causes a backtrack to
reach them. They all force a match failure, but they differ in what happens
afterwards. Those that advance the start\-of\-match point do so only if the
pattern is not anchored.
.sp
.ss \n[.ss]
.nf
.fam C
(*COMMIT)       overall failure, no advance of starting point
(*PRUNE)        advance to next starting character
(*SKIP)         advance to current matching position
(*SKIP:NAME)    advance to position corresponding to an earlier
                (*MARK:NAME); if not found, the (*SKIP) is ignored
(*THEN)         local failure, backtrack to next alternation
.fam
.fi
.ss \n[.ss] 0
.sp
The effect of one of these verbs in a group called as a subroutine is confined
to the subroutine call.
.SH "CALLOUTS"
.sp
.ss \n[.ss]
.nf
.fam C
(?C)            callout (assumed number 0)
(?Cn)           callout with numerical data n
(?C"text")      callout with string data
.fam
.fi
.ss \n[.ss] 0
.sp
The allowed string delimiters are ` \*(Aq " ^ % # $ (which are the same for the
start and the end), and the starting delimiter { matched with the ending
delimiter }. To encode the ending delimiter within the string, double it.
.SH "REPLACEMENT STRINGS"
.sp
If the \fBPCRE2_SUBSTITUTE_LITERAL\fP option is set, a replacement string for
pcre2_substitute() is not interpreted. Otherwise, by default, the only
special character is the dollar character in one of the following forms:
.sp
.ss \n[.ss]
.nf
.fam C
$$                  insert a dollar character
$n or ${n}          insert the contents of group _n_
$<name>             insert the contents of named group
$0 or $&            insert the entire matched substring
$`                  insert the substring that precedes the match
$\*(Aq                  insert the substring that follows the match
$_                  insert the entire input string
$+                  insert the highest\-numbered capture group which matched
$*MARK or ${*MARK}  insert a control verb name
.fam
.fi
.ss \n[.ss] 0
.sp
For ${n}, n can be a name or a number. If \fBPCRE2_SUBSTITUTE_EXTENDED\fP is set,
there is additional interpretation:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Backslash is an escape character, and the forms described in "ESCAPED
CHARACTERS" above are recognized. Also:
.RE
.sp
.ss \n[.ss]
.nf
.fam C
\(rsQ...\(rsE can be used to suppress interpretation
\(rsl      force the next character to lower case
\(rsu      force the next character to upper case
\(rsL      force subsequent characters to lower case
\(rsU      force subsequent characters to upper case
\(rsu\(rsL    force next character to upper case, then all lower
\(rsl\(rsU    force next character to lower case, then all upper
\(rsE      end \(rsL or \(rsU case forcing
\(rsb      backspace character (note: as in character class in pattern)
\(rsv      vertical tab character (note: not the same as in a pattern)
.fam
.fi
.ss \n[.ss] 0
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
The Python form \(rsg<n>, where the angle brackets are part of the syntax and
\fIn\fP is either a group name or a number, is recognized as an alternative way
of inserting the contents of a group, for example \(rsg<3>.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
Capture substitution supports the following additional forms:
.RE
.sp
.ss \n[.ss]
.nf
.fam C
${n:\-string}             default for unset group
${n:+string1:string2}    values for set/unset group
.fam
.fi
.ss \n[.ss] 0
.sp
The substitution strings themselves are expanded. Backslash can be used to
escape colons and closing curly brackets.
.SH "SEE ALSO"
.sp
\f(CRpcre2pattern\fP(3), \f(CRpcre2api\fP(3), \f(CRpcre2callout\fP(3),
\f(CRpcre2matching\fP(3), \f(CRpcre2\fP(3).
.SH "AUTHOR"
.sp
.ti +2
Philip Hazel
.br
.ti +2
Retired from University Computing Service
.br
.ti +2
Cambridge, England.
.SH "REVISION"
.sp
Last updated: 14 October 2025
.br
Copyright (c) 1997\-2024 University of Cambridge.