'\" t
.\"     Title: pcre2_set_glob_escape
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 12 July 2017
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SET_GLOB_ESCAPE" "3" "12 July 2017" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_set_glob_escape \- set glob escape character
.SH "SYNOPSIS"
.sp
.nf
.fam C
#include <pcre2.h>

int pcre2_set_glob_escape(pcre2_convert_context *ccontext,
                          uint32_t escape_char);
.fam
.fi
.SH "DESCRIPTION"
.sp
This function is part of an experimental set of pattern conversion functions.
It sets the escape character that is used when converting globs. The second
argument must either be zero (meaning there is no escape character) or a
punctuation character whose code point is less than 256. The default is grave
accent if running under Windows, otherwise backslash. The result of the
function is zero for success or PCRE2_ERROR_BADDATA if the second argument is
invalid.
.sp
The pattern conversion functions are described in the
\f(CRpcre2convert\fP
documentation.