'\" t
.\"     Title: pcre2_match_data_create_from_pattern
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 11 August 2025
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_MATCH_DATA_CREATE_FROM_PATTERN" "3" "11 August 2025" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_match_data_create_from_pattern \- create a match data block getting size from pattern
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBpcre2_match_data\fP *pcre2_match_data_create_from_pattern(
      \fBconst\fP \fBpcre2_code\fP *\fIcode\fP, \fBpcre2_general_context\fP *\fIgcontext\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function creates a new match data block for holding the result of a match.
If the first argument is \fBNULL\fP, this function returns \fBNULL\fP, otherwise the first
argument points to a compiled pattern. The number of capturing parentheses
within the pattern is used to compute the number of pairs of offsets that are
required in the match data block. These form the "output vector" (ovector)
within the match data block, and are used to identify the matched string and
any captured substrings when matching with pcre2_match(). If you are
using pcre2_dfa_match(), which uses the output vector in a different way,
you should use pcre2_match_data_create() instead of this function.
.sp
The second argument points to a general context, for custom memory management,
or is \fBNULL\fP to use the same memory allocator that was used for the compiled
pattern. The result of the function is \fBNULL\fP if the memory for the block could
not be obtained or if \fBNULL\fP was provided as the first argument.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.