'\" t
.\"     Title: pcre2grep
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 24 January 2025
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2GREP" "1" "24 January 2025" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2grep \- a grep with Perl\-compatible regular expressions.
.SH "SYNOPSIS"
.sp
.nf
.fam C
pcre2grep [options] [long options] [pattern] [path1 path2 ...]
.fam
.fi
.SH "DESCRIPTION"
.sp
\f(CRpcre2grep\fP searches files for character patterns, in the same way as other
grep commands do, but it uses the PCRE2 regular expression library to support
patterns that are compatible with the regular expressions of Perl 5. See
\f(CRpcre2syntax\fP(3)
for a quick\-reference summary of pattern syntax, or
\f(CRpcre2pattern\fP(3)
for a full description of the syntax and semantics of the regular expressions
that PCRE2 supports.
.sp
Patterns, whether supplied on the command line or in a separate file, are given
without delimiters. For example:
.sp
.ti +2
pcre2grep Thursday /etc/motd
.sp
If you attempt to use delimiters (for example, by surrounding a pattern with
slashes, as is common in Perl scripts), they are interpreted as part of the
pattern. Quotes can of course be used to delimit patterns on the command line
because they are interpreted by the shell, and indeed quotes are required if a
pattern contains white space or shell metacharacters.
.sp
The first argument that follows any option settings is treated as the single
pattern to be matched when neither \f(CR\-e\fP nor \f(CR\-f\fP is present.
Conversely, when one or both of these options are used to specify patterns, all
arguments are treated as path names. At least one of \f(CR\-e\fP, \f(CR\-f\fP, or an
argument pattern must be provided.
.sp
If no files are specified, \f(CRpcre2grep\fP reads the standard input. The
standard input can also be referenced by a name consisting of a single hyphen.
For example:
.sp
.ti +2
pcre2grep some\-pattern file1 \- file3
.sp
By default, input files are searched line by line, so pattern assertions about
the beginning and end of a subject string (^, $, \(rsA, \(rsZ, and \(rsz) match at
the beginning and end of each line. When a line matches a pattern, it is copied
to the standard output, and if there is more than one file, the file name is
output at the start of each line, followed by a colon. However, there are
options that can change how \f(CRpcre2grep\fP behaves. For example, the \f(CR\-M\fP
option makes it possible to search for strings that span line boundaries. What
defines a line boundary is controlled by the \f(CR\-N\fP (\f(CR\-\-newline\fP) option.
The \f(CR\-h\fP and \f(CR\-H\fP options control whether or not file names are shown,
and the \f(CR\-Z\fP option changes the file name terminator to a zero byte.
.sp
The amount of memory used for buffering files that are being scanned is
controlled by parameters that can be set by the \f(CR\-\-buffer\-size\fP and
\f(CR\-\-max\-buffer\-size\fP options. The first of these sets the size of buffer
that is obtained at the start of processing. If an input file contains very
long lines, a larger buffer may be needed; this is handled by automatically
extending the buffer, up to the limit specified by \f(CR\-\-max\-buffer\-size\fP. The
default values for these parameters can be set when \f(CRpcre2grep\fP is
built; if nothing is specified, the defaults are set to 20KiB and 1MiB
respectively. An error occurs if a line is too long and the buffer can no
longer be expanded.
.sp
The block of memory that is actually used is three times the "buffer size", to
allow for buffering "before" and "after" lines. If the buffer size is too
small, fewer than requested "before" and "after" lines may be output.
.sp
When matching with a multiline pattern, the size of the buffer must be at least
half of the maximum match expected or the pattern might fail to match.
.sp
Patterns can be no longer than 8KiB or BUFSIZ bytes, whichever is the greater.
BUFSIZ is defined in \f(CR<stdio.h>\fP. When there is more than one pattern
(specified by the use of \f(CR\-e\fP and/or \f(CR\-f\fP), each pattern is applied to
each line in the order in which they are defined, except that all the \f(CR\-e\fP
patterns are tried before the \f(CR\-f\fP patterns.
.sp
By default, as soon as one pattern matches a line, no further patterns are
considered. However, if \f(CR\-\-colour\fP (or \f(CR\-\-color\fP) is used to colour the
matching substrings, or if \f(CR\-\-only\-matching\fP, \f(CR\-\-file\-offsets\fP,
\f(CR\-\-line\-offsets\fP, or \f(CR\-\-output\fP is used to output only the part of the
line that matched (either shown literally, or as an offset), the behaviour is
different. In this situation, all the patterns are applied to the line. If
there is more than one match, the one that begins nearest to the start of the
subject is processed; if there is more than one match at that position, the one
with the longest matching substring is processed; if the matching substrings
are equal, the first match found is processed.
.sp
Scanning with all the patterns resumes immediately following the match, so that
later matches on the same line can be found. Note, however, that an overlapping
match that starts in the middle of another match will not be processed.
.sp
The above behaviour was changed at release 10.41 to be more compatible with GNU
grep. In earlier releases, \f(CRpcre2grep\fP did not recognize matches from
later patterns that were earlier in the subject.
.sp
Patterns that can match an empty string are accepted, but empty string
matches are never recognized. An example is the pattern "(super)?(man)?", in
which all components are optional. This pattern finds all occurrences of both
"super" and "man"; the output differs from matching with "super|man" when only
the matching substrings are being shown.
.sp
If the \f(CRLC_ALL\fP or \f(CRLC_CTYPE\fP environment variable is set,
\f(CRpcre2grep\fP uses the value to set a locale when calling the PCRE2 library.
The \f(CR\-\-locale\fP option can be used to override this.
.SH "SUPPORT FOR COMPRESSED FILES"
.sp
Compile\-time options for \f(CRpcre2grep\fP can set it up to use \f(CRlibz\fP or
\f(CRlibbz2\fP for reading compressed files whose names end in \f(CR.gz\fP or
\f(CR.bz2\fP, respectively. You can find out whether your \f(CRpcre2grep\fP binary
has support for one or both of these file types by running it with the
\f(CR\-\-help\fP option. If the appropriate support is not present, all files are
treated as plain text. The standard input is always so treated. If a file with
a \f(CR.gz\fP or \f(CR.bz2\fP extension is not in fact compressed, it is read as a
plain text file. When input is from a compressed .gz or .bz2 file, the
\f(CR\-\-line\-buffered\fP option is ignored.
.SH "BINARY FILES"
.sp
By default, a file that contains a binary zero byte within the first 1024 bytes
is identified as a binary file, and is processed specially. However, if the
newline type is specified as NUL, that is, the line terminator is a binary
zero, the test for a binary file is not applied. See the \f(CR\-\-binary\-files\fP
option for a means of changing the way binary files are handled.
.SH "BINARY ZEROS IN PATTERNS"
.sp
Patterns passed from the command line are strings that are terminated by a
binary zero, so cannot contain internal zeros. However, patterns that are read
from a file via the \f(CR\-f\fP option may contain binary zeros.
.SH "OPTIONS"
.sp
The order in which some of the options appear can affect the output. For
example, both the \f(CR\-H\fP and \f(CR\-l\fP options affect the printing of file
names. Whichever comes later in the command line will be the one that takes
effect. Similarly, except where noted below, if an option is given twice, the
later setting is used. Numerical values for options may be followed by K or M,
to signify multiplication by 1024 or 1024*1024 respectively.
.TP 10
\f(CR\-\-\fP
This terminates the list of options. It is useful if the next item on the
command line starts with a hyphen but is not an option. This allows for the
processing of patterns and file names that start with hyphens.
.TP 10
\f(CR\-A\fP \fInumber\fP, \f(CR\-\-after\-context=number\fP
Output up to \fInumber\fP lines of context after each matching line. Fewer
lines are output if the next match or the end of the file is reached, or if the
processing buffer size has been set too small. If file names and/or line
numbers are being output, a hyphen separator is used instead of a colon for the
context lines (the \f(CR\-Z\fP option can be used to change the file name
terminator to a zero byte). A line containing "\-\-" is output between each group
of lines, unless they are in fact contiguous in the input file. The value of
\fInumber\fP is expected to be relatively small. When \f(CR\-c\fP is used,
\f(CR\-A\fP is ignored.
.TP 10
\f(CR\-a\fP, \f(CR\-\-text\fP
Treat binary files as text. This is equivalent to
\f(CR\-\-binary\-files\fP=\fItext\fP.
.TP 10
\f(CR\-\-allow\-lookaround\-bsk\fP
PCRE2 now forbids the use of \(rsK in lookarounds by default, in line with Perl.
This option causes \f(CRpcre2grep\fP to set the PCRE2_EXTRA_ALLOW_LOOKAROUND_BSK
option, which enables this somewhat dangerous usage.
.TP 10
\f(CR\-B\fP \fInumber\fP, \f(CR\-\-before\-context=number\fP
Output up to \fInumber\fP lines of context before each matching line. Fewer
lines are output if the previous match or the start of the file is within
\fInumber\fP lines, or if the processing buffer size has been set too small. If
file names and/or line numbers are being output, a hyphen separator is used
instead of a colon for the context lines (the \f(CR\-Z\fP option can be used to
change the file name terminator to a zero byte). A line containing "\-\-" is
output between each group of lines, unless they are in fact contiguous in the
input file. The value of \fInumber\fP is expected to be relatively small. When
\f(CR\-c\fP is used, \f(CR\-B\fP is ignored.
.TP 10
\f(CR\-\-binary\-files=word\fP
Specify how binary files are to be processed. If the word is "binary" (the
default), pattern matching is performed on binary files, but the only output is
"Binary file <name> matches" when a match succeeds. If the word is "text",
which is equivalent to the \f(CR\-a\fP or \f(CR\-\-text\fP option, binary files are
processed in the same way as any other file. In this case, when a match
succeeds, the output may be binary garbage, which can have nasty effects if
sent to a terminal. If the word is "without\-match", which is equivalent to the
\f(CR\-I\fP option, binary files are not processed at all; they are assumed not to
be of interest and are skipped without causing any output or affecting the
return code.
.TP 10
\f(CR\-\-buffer\-size=number\fP
Set the parameter that controls how much memory is obtained at the start of
processing for buffering files that are being scanned. See also
\f(CR\-\-max\-buffer\-size\fP below.
.TP 10
\f(CR\-C\fP \fInumber\fP, \f(CR\-\-context=number\fP
Output \fInumber\fP lines of context both before and after each matching line.
This is equivalent to setting both \f(CR\-A\fP and \f(CR\-B\fP to the same value.
.TP 10
\f(CR\-c\fP, \f(CR\-\-count\fP
Do not output lines from the files that are being scanned; instead output the
number of lines that would have been shown, either because they matched, or, if
\f(CR\-v\fP is set, because they failed to match. By default, this count is
exactly the same as the number of lines that would have been output, but if the
\f(CR\-M\fP (multiline) option is used (without \f(CR\-v\fP), there may be more
suppressed lines than the count (that is, the number of matches).
.sp
If no lines are selected, the number zero is output. If several files are
being scanned, a count is output for each of them and the \f(CR\-t\fP option can
be used to cause a total to be output at the end. However, if the
\f(CR\-\-files\-with\-matches\fP option is also used, only those files whose counts
are greater than zero are listed. When \f(CR\-c\fP is used, the \f(CR\-A\fP,
\f(CR\-B\fP, and \f(CR\-C\fP options are ignored.
.TP 10
\f(CR\-\-colour\fP, \f(CR\-\-color\fP
If this option is given without any data, it is equivalent to "\-\-colour=auto".
If data is required, it must be given in the same shell item, separated by an
equals sign.
.TP 10
\f(CR\-\-colour=value\fP, \f(CR\-\-color=value\fP
This option specifies under what circumstances the parts of a line that matched
a pattern should be coloured in the output. It is ignored if
\f(CR\-\-file\-offsets\fP, \f(CR\-\-line\-offsets\fP, or \f(CR\-\-output\fP is set. By
default, output is not coloured. The value for the \f(CR\-\-colour\fP option (which
is optional, see above) may be "never", "always", or "auto". In the latter
case, colouring happens only if the standard output is connected to a terminal.
More resources are used when colouring is enabled, because \f(CRpcre2grep\fP has
to search for all possible matches in a line, not just one, in order to colour
them all.
.sp
The colour that is used can be specified by setting one of the environment
variables PCRE2GREP_COLOUR, PCRE2GREP_COLOR, PCREGREP_COLOUR, or
PCREGREP_COLOR, which are checked in that order. If none of these are set,
\f(CRpcre2grep\fP looks for GREP_COLORS or GREP_COLOR (in that order). The value
of the variable should be a string of two numbers, separated by a semicolon,
except in the case of GREP_COLORS, which must start with "ms=" or "mt="
followed by two semicolon\-separated colours, terminated by the end of the
string or by a colon. If GREP_COLORS does not start with "ms=" or "mt=" it is
ignored, and GREP_COLOR is checked.
.sp
If the string obtained from one of the above variables contains any characters
other than semicolon or digits, the setting is ignored and the default colour
is used. The string is copied directly into the control string for setting
colour on a terminal, so it is your responsibility to ensure that the values
make sense. If no relevant environment variable is set, the default is "1;31",
which gives red.
.TP 10
\f(CR\-D\fP \fIaction\fP, \f(CR\-\-devices=action\fP
If an input path is not a regular file or a directory, "action" specifies how
it is to be processed. Valid values are "read" (the default) or "skip"
(silently skip the path).
.TP 10
\f(CR\-d\fP \fIaction\fP, \f(CR\-\-directories=action\fP
If an input path is a directory, "action" specifies how it is to be processed.
Valid values are "read" (the default in non\-Windows environments, for
compatibility with GNU grep), "recurse" (equivalent to the \f(CR\-r\fP option), or
"skip" (silently skip the path, the default in Windows environments). In the
"read" case, directories are read as if they were ordinary files. In some
operating systems the effect of reading a directory like this is an immediate
end\-of\-file; in others it may provoke an error.
.TP 10
\f(CR\-\-depth\-limit\fP=\fInumber\fP
See \f(CR\-\-match\-limit\fP below.
.TP 10
\f(CR\-E\fP, \f(CR\-\-case\-restrict\fP
When case distinctions are being ignored in Unicode mode, two ASCII letters (K
and S) will by default match Unicode characters U+212A (Kelvin sign) and U+017F
(long S) respectively, as well as their lower case ASCII counterparts. When
this option is set, case equivalences are restricted such that no ASCII
character matches a non\-ASCII character, and vice versa.
.TP 10
\f(CR\-e\fP \fIpattern\fP, \f(CR\-\-regex=pattern\fP, \f(CR\-\-regexp=pattern\fP
Specify a pattern to be matched. This option can be used multiple times in
order to specify several patterns. It can also be used as a way of specifying a
single pattern that starts with a hyphen. When \f(CR\-e\fP is used, no argument
pattern is taken from the command line; all arguments are treated as file
names. There is no limit to the number of patterns. They are applied to each
line in the order in which they are defined.
.sp
If \f(CR\-f\fP is used with \f(CR\-e\fP, the command line patterns are matched first,
followed by the patterns from the file(s), independent of the order in which
these options are specified.
.TP 10
\f(CR\-\-exclude\fP=\fIpattern\fP
Files (but not directories) whose names match the pattern are skipped without
being processed. This applies to all files, whether listed on the command line,
obtained from \f(CR\-\-file\-list\fP, or by scanning a directory. The pattern is a
PCRE2 regular expression, and is matched against the final component of the
file name, not the entire path. The \f(CR\-F\fP, \f(CR\-w\fP, and \f(CR\-x\fP options do
not apply to this pattern. The option may be given any number of times in order
to specify multiple patterns. If a file name matches both an \f(CR\-\-include\fP
and an \f(CR\-\-exclude\fP pattern, it is excluded. There is no short form for this
option.
.TP 10
\f(CR\-\-exclude\-from=filename\fP
Treat each non\-empty line of the file as the data for an \f(CR\-\-exclude\fP
option. What constitutes a newline when reading the file is the operating
system's default. The \f(CR\-\-newline\fP option has no effect on this option. This
option may be given more than once in order to specify a number of files to
read.
.TP 10
\f(CR\-\-exclude\-dir\fP=\fIpattern\fP
Directories whose names match the pattern are skipped without being processed,
whatever the setting of the \f(CR\-\-recursive\fP option. This applies to all
directories, whether listed on the command line, obtained from
\f(CR\-\-file\-list\fP, or by scanning a parent directory. The pattern is a PCRE2
regular expression, and is matched against the final component of the directory
name, not the entire path. The \f(CR\-F\fP, \f(CR\-w\fP, and \f(CR\-x\fP options do not
apply to this pattern. The option may be given any number of times in order to
specify more than one pattern. If a directory matches both \f(CR\-\-include\-dir\fP
and \f(CR\-\-exclude\-dir\fP, it is excluded. There is no short form for this
option.
.TP 10
\f(CR\-F\fP, \f(CR\-\-fixed\-strings\fP
Interpret each data\-matching pattern as a list of fixed strings, separated by
newlines, instead of as a regular expression. What constitutes a newline for
this purpose is controlled by the \f(CR\-\-newline\fP option. The \f(CR\-w\fP (match
as a word) and \f(CR\-x\fP (match whole line) options can be used with \f(CR\-F\fP.
They apply to each of the fixed strings. A line is selected if any of the fixed
strings are found in it (subject to \f(CR\-w\fP or \f(CR\-x\fP, if present). This
option applies only to the patterns that are matched against the contents of
files; it does not apply to patterns specified by any of the \f(CR\-\-include\fP or
\f(CR\-\-exclude\fP options.
.TP 10
\f(CR\-f\fP \fIfilename\fP, \f(CR\-\-file=filename\fP
Read patterns from the file, one per line. As is the case with patterns on the
command line, no delimiters should be used. What constitutes a newline when
reading the file is the operating system's default interpretation of \(rsn. The
\f(CR\-\-newline\fP option has no effect on this option. Trailing white space is
removed from each line, and blank lines are ignored unless the
\f(CR\-\-posix\-pattern\-file\fP option is also provided. An empty file contains no
patterns and therefore matches nothing. Patterns read from a file in this way
may contain binary zeros, which are treated as ordinary character literals.
.sp
If this option is given more than once, all the specified files are read. A
data line is output if any of the patterns match it. A file name can be given
as "\-" to refer to the standard input. When \f(CR\-f\fP is used, patterns
specified on the command line using \f(CR\-e\fP may also be present; they are
matched before the file's patterns. However, no pattern is taken from the
command line; all arguments are treated as the names of paths to be searched.
.TP 10
\f(CR\-\-file\-list\fP=\fIfilename\fP
Read a list of files and/or directories that are to be scanned from the given
file, one per line. What constitutes a newline when reading the file is the
operating system's default. Trailing white space is removed from each line, and
blank lines are ignored. These paths are processed before any that are listed
on the command line. The file name can be given as "\-" to refer to the standard
input. If \f(CR\-\-file\fP and \f(CR\-\-file\-list\fP are both specified as "\-",
patterns are read first. This is useful only when the standard input is a
terminal, from which further lines (the list of files) can be read after an
end\-of\-file indication. If this option is given more than once, all the
specified files are read.
.TP 10
\f(CR\-\-file\-offsets\fP
Instead of showing lines or parts of lines that match, show each match as an
offset from the start of the file and a length, separated by a comma. In this
mode, \f(CR\-\-colour\fP has no effect, and no context is shown. That is, the
\f(CR\-A\fP, \f(CR\-B\fP, and \f(CR\-C\fP options are ignored. If there is more than one
match in a line, each of them is shown separately. This option is mutually
exclusive with \f(CR\-\-output\fP, \f(CR\-\-line\-offsets\fP, and \f(CR\-\-only\-matching\fP.
.TP 10
\f(CR\-\-group\-separator\fP=\fItext\fP
Output this text string instead of two hyphens between groups of lines when
\f(CR\-A\fP, \f(CR\-B\fP, or \f(CR\-C\fP is in use. See also \f(CR\-\-no\-group\-separator\fP.
.TP 10
\f(CR\-H\fP, \f(CR\-\-with\-filename\fP
Force the inclusion of the file name at the start of output lines when
searching a single file. The file name is not normally shown in this case.
By default, for matching lines, the file name is followed by a colon; for
context lines, a hyphen separator is used. The \f(CR\-Z\fP option can be used to
change the terminator to a zero byte. If a line number is also being output,
it follows the file name. When the \f(CR\-M\fP option causes a pattern to match
more than one line, only the first is preceded by the file name. This option
overrides any previous \f(CR\-h\fP, \f(CR\-l\fP, or \f(CR\-L\fP options.
.TP 10
\f(CR\-h\fP, \f(CR\-\-no\-filename\fP
Suppress the output file names when searching multiple files. File names are
normally shown when multiple files are searched. By default, for matching
lines, the file name is followed by a colon; for context lines, a hyphen
separator is used. The \f(CR\-Z\fP option can be used to change the terminator to
a zero byte. If a line number is also being output, it follows the file name.
This option overrides any previous \f(CR\-H\fP, \f(CR\-L\fP, or \f(CR\-l\fP options.
.TP 10
\f(CR\-\-heap\-limit\fP=\fInumber\fP
See \f(CR\-\-match\-limit\fP below.
.TP 10
\f(CR\-\-help\fP
Output a help message, giving brief details of the command options and file
type support, and then exit. Anything else on the command line is
ignored.
.TP 10
\f(CR\-I\fP
Ignore binary files. This is equivalent to
\f(CR\-\-binary\-files\fP=\fIwithout\-match\fP.
.TP 10
\f(CR\-i\fP, \f(CR\-\-ignore\-case\fP
Ignore upper/lower case distinctions when pattern matching. This applies when
matching path names for inclusion or exclusion as well as when matching lines
in files.
.TP 10
\f(CR\-\-include\fP=\fIpattern\fP
If any \f(CR\-\-include\fP patterns are specified, the only files that are
processed are those whose names match one of the patterns and do not match an
\f(CR\-\-exclude\fP pattern. This option does not affect directories, but it
applies to all files, whether listed on the command line, obtained from
\f(CR\-\-file\-list\fP, or by scanning a directory. The pattern is a PCRE2 regular
expression, and is matched against the final component of the file name, not
the entire path. The \f(CR\-F\fP, \f(CR\-w\fP, and \f(CR\-x\fP options do not apply to
this pattern. The option may be given any number of times. If a file name
matches both an \f(CR\-\-include\fP and an \f(CR\-\-exclude\fP pattern, it is excluded.
There is no short form for this option.
.TP 10
\f(CR\-\-include\-from=filename\fP
Treat each non\-empty line of the file as the data for an \f(CR\-\-include\fP
option. What constitutes a newline for this purpose is the operating system's
default. The \f(CR\-\-newline\fP option has no effect on this option. This option
may be given any number of times; all the files are read.
.TP 10
\f(CR\-\-include\-dir\fP=\fIpattern\fP
If any \f(CR\-\-include\-dir\fP patterns are specified, the only directories that
are processed are those whose names match one of the patterns and do not match
an \f(CR\-\-exclude\-dir\fP pattern. This applies to all directories, whether listed
on the command line, obtained from \f(CR\-\-file\-list\fP, or by scanning a parent
directory. The pattern is a PCRE2 regular expression, and is matched against
the final component of the directory name, not the entire path. The \f(CR\-F\fP,
\f(CR\-w\fP, and \f(CR\-x\fP options do not apply to this pattern. The option may be
given any number of times. If a directory matches both \f(CR\-\-include\-dir\fP and
\f(CR\-\-exclude\-dir\fP, it is excluded. There is no short form for this option.
.TP 10
\f(CR\-L\fP, \f(CR\-\-files\-without\-match\fP
Instead of outputting lines from the files, just output the names of the files
that do not contain any lines that would have been output. Each file name is
output once, on a separate line by default, but if the \f(CR\-Z\fP option is set,
they are separated by zero bytes instead of newlines. This option overrides any
previous \f(CR\-H\fP, \f(CR\-h\fP, or \f(CR\-l\fP options.
.TP 10
\f(CR\-l\fP, \f(CR\-\-files\-with\-matches\fP
Instead of outputting lines from the files, just output the names of the files
containing lines that would have been output. Each file name is output once, on
a separate line, but if the \f(CR\-Z\fP option is set, they are separated by zero
bytes instead of newlines. Searching normally stops as soon as a matching line
is found in a file. However, if the \f(CR\-c\fP (count) option is also used,
matching continues in order to obtain the correct count, and those files that
have at least one match are listed along with their counts. Using this option
with \f(CR\-c\fP is a way of suppressing the listing of files with no matches that
occurs with \f(CR\-c\fP on its own. This option overrides any previous \f(CR\-H\fP,
\f(CR\-h\fP, or \f(CR\-L\fP options.
.TP 10
\f(CR\-\-label\fP=\fIname\fP
This option supplies a name to be used for the standard input when file names
are being output. If not supplied, "(standard input)" is used. There is no
short form for this option.
.TP 10
\f(CR\-\-lf\fP
Use LF as the line ending for standard output. This has no effect except on
Windows, where CRLF is the default. There is no short form for this option.
.TP 10
\f(CR\-\-line\-buffered\fP
When this option is given, non\-compressed input is read and processed line by
line, and the output is flushed after each write. By default, input is read in
large chunks, unless \f(CRpcre2grep\fP can determine that it is reading from a
terminal, which is currently possible only in Unix\-like environments or
Windows. Output to terminal is normally automatically flushed by the operating
system. This option can be useful when the input or output is attached to a
pipe and you do not want \f(CRpcre2grep\fP to buffer up large amounts of data.
However, its use will affect performance, and the \f(CR\-M\fP (multiline) option
ceases to work. When input is from a compressed .gz or .bz2 file,
\f(CR\-\-line\-buffered\fP is ignored.
.TP 10
\f(CR\-\-line\-offsets\fP
Instead of showing lines or parts of lines that match, show each match as a
line number, the offset from the start of the line, and a length. The line
number is terminated by a colon (as usual; see the \f(CR\-n\fP option), and the
offset and length are separated by a comma. In this mode, \f(CR\-\-colour\fP has no
effect, and no context is shown. That is, the \f(CR\-A\fP, \f(CR\-B\fP, and \f(CR\-C\fP
options are ignored. If there is more than one match in a line, each of them is
shown separately. This option is mutually exclusive with \f(CR\-\-output\fP,
\f(CR\-\-file\-offsets\fP, and \f(CR\-\-only\-matching\fP.
.TP 10
\f(CR\-\-locale\fP=\fIlocale\-name\fP
This option specifies a locale to be used for pattern matching. It overrides
the value in the \f(CRLC_ALL\fP or \f(CRLC_CTYPE\fP environment variables. If no
locale is specified, the PCRE2 library's default (usually the "C" locale) is
used. There is no short form for this option.
.TP 10
\f(CR\-M\fP, \f(CR\-\-multiline\fP
Allow patterns to match more than one line. When this option is set, the PCRE2
library is called in "multiline" mode, and a match is allowed to continue past
the end of the initial line and onto one or more subsequent lines.
.sp
Patterns used with \f(CR\-M\fP may usefully contain literal newline characters and
internal occurrences of ^ and $ characters, because in multiline mode these can
match at internal newlines. Because \f(CRpcre2grep\fP is scanning multiple lines,
the \(rsZ and \(rsz assertions match only at the end of the last line in the file.
The \(rsA assertion matches at the start of the first line of a match. This can
be any line in the file; it is not anchored to the first line.
.sp
The output for a successful match may consist of more than one line. The first
line is the line in which the match started, and the last line is the line in
which the match ended. If the matched string ends with a newline sequence, the
output ends at the end of that line. If \f(CR\-v\fP is set, none of the lines in a
multi\-line match are output. Once a match has been handled, scanning restarts
at the beginning of the line after the one in which the match ended.
.sp
The newline sequence that separates multiple lines must be matched as part of
the pattern. For example, to find the phrase "regular expression" in a file
where "regular" might be at the end of a line and "expression" at the start of
the next line, you could use this command:
.sp
.ti +2
pcre2grep \-M \*(Aqregular\(rss+expression\*(Aq <file>
.sp
The \(rss escape sequence matches any white space character, including newlines,
and is followed by + so as to match trailing white space on the first line as
well as possibly handling a two\-character newline sequence.
.sp
There is a limit to the number of lines that can be matched, imposed by the way
that \f(CRpcre2grep\fP buffers the input file as it scans it. With a sufficiently
large processing buffer, this should not be a problem.
.sp
The \f(CR\-M\fP option does not work when input is read line by line (see
\f(CR\-\-line\-buffered\fP.)
.TP 10
\f(CR\-m\fP \fInumber\fP, \f(CR\-\-max\-count\fP=\fInumber\fP
Stop processing after finding \fInumber\fP matching lines, or non\-matching
lines if \f(CR\-v\fP is also set. Any trailing context lines are output after the
final match. In multiline mode, each multiline match counts as just one line
for this purpose. If this limit is reached when reading the standard input from
a regular file, the file is left positioned just after the last matching line.
If \f(CR\-c\fP is also set, the count that is output is never greater than
\fInumber\fP. This option has no effect if used with \f(CR\-L\fP, \f(CR\-l\fP, or
\f(CR\-q\fP, or when just checking for a match in a binary file.
.TP 10
\f(CR\-\-match\-limit\fP=\fInumber\fP
Processing some regular expression patterns may take a very long time to search
for all possible matching strings. Others may require a very large amount of
memory. There are three options that set resource limits for matching.
.sp
The \f(CR\-\-match\-limit\fP option provides a means of limiting computing resource
usage when processing patterns that are not going to match, but which have a
very large number of possibilities in their search trees. The classic example
is a pattern that uses nested unlimited repeats. Internally, PCRE2 has a
counter that is incremented each time around its main processing loop. If the
value set by \f(CR\-\-match\-limit\fP is reached, an error occurs.
.sp
The \f(CR\-\-heap\-limit\fP option specifies, as a number of kibibytes (units of
1024 bytes), the maximum amount of heap memory that may be used for matching.
.sp
The \f(CR\-\-depth\-limit\fP option limits the depth of nested backtracking points,
which indirectly limits the amount of memory that is used. The amount of memory
needed for each backtracking point depends on the number of capturing
parentheses in the pattern, so the amount of memory that is used before this
limit acts varies from pattern to pattern. This limit is of use only if it is
set smaller than \f(CR\-\-match\-limit\fP.
.sp
There are no short forms for these options. The default limits can be set
when the PCRE2 library is compiled; if they are not specified, the defaults
are very large and so effectively unlimited.
.TP 10
\f(CR\-\-max\-buffer\-size\fP=\fInumber\fP
This limits the expansion of the processing buffer, whose initial size can be
set by \f(CR\-\-buffer\-size\fP. The maximum buffer size is silently forced to be no
smaller than the starting buffer size.
.TP 10
\f(CR\-N\fP \fInewline\-type\fP, \f(CR\-\-newline\fP=\fInewline\-type\fP
Six different conventions for indicating the ends of lines in scanned files are
supported. For example:
.sp
.ti +2
pcre2grep \-N CRLF \*(Aqsome pattern\*(Aq <file>
.sp
The newline type may be specified in upper, lower, or mixed case. If the
newline type is NUL, lines are separated by binary zero characters. The other
types are the single\-character sequences CR (carriage return) and LF
(linefeed), the two\-character sequence CRLF, an "anycrlf" type, which
recognizes any of the preceding three types, and an "any" type, for which any
Unicode line ending sequence is assumed to end a line. The Unicode sequences
are the three just mentioned, plus VT (vertical tab, U+000B), FF (form feed,
U+000C), NEL (next line, U+0085), LS (line separator, U+2028), and PS
(paragraph separator, U+2029).
.sp
When the PCRE2 library is built, a default line\-ending sequence is specified.
This is normally the standard sequence for the operating system. Unless
otherwise specified by this option, \f(CRpcre2grep\fP uses the library's default.
.sp
This option makes it possible to use \f(CRpcre2grep\fP to scan files that have
come from other environments without having to modify their line endings. If
the data that is being scanned does not agree with the convention set by this
option, \f(CRpcre2grep\fP may behave in strange ways. Note that this option does
not apply to files specified by the \f(CR\-f\fP, \f(CR\-\-exclude\-from\fP, or
\f(CR\-\-include\-from\fP options, which are expected to use the operating system's
standard newline sequence.
.TP 10
\f(CR\-n\fP, \f(CR\-\-line\-number\fP
Precede each output line by its line number in the file, followed by a colon
for matching lines or a hyphen for context lines. If the file name is also
being output, it precedes the line number. When the \f(CR\-M\fP option causes a
pattern to match more than one line, only the first is preceded by its line
number. This option is forced if \f(CR\-\-line\-offsets\fP is used.
.TP 10
\f(CR\-\-no\-group\-separator\fP
Do not output a separator between groups of lines when \f(CR\-A\fP, \f(CR\-B\fP, or
\f(CR\-C\fP is in use. The default is to output a line containing two hyphens. See
also \f(CR\-\-group\-separator\fP.
.TP 10
\f(CR\-\-no\-jit\fP
If the PCRE2 library is built with support for just\-in\-time compiling (which
speeds up matching), \f(CRpcre2grep\fP automatically makes use of this, unless it
was explicitly disabled at build time. This option can be used to disable the
use of JIT at run time. It is provided for testing and working around problems.
It should never be needed in normal use.
.TP 10
\f(CR\-O\fP \fItext\fP, \f(CR\-\-output\fP=\fItext\fP
When there is a match, instead of outputting the line that matched, output just
the text specified in this option, followed by an operating\-system standard
newline. In this mode, \f(CR\-\-colour\fP has no effect, and no context is shown.
That is, the \f(CR\-A\fP, \f(CR\-B\fP, and \f(CR\-C\fP options are ignored. The
\f(CR\-\-newline\fP option has no effect on this option, which is mutually
exclusive with \f(CR\-\-only\-matching\fP, \f(CR\-\-file\-offsets\fP, and
\f(CR\-\-line\-offsets\fP. However, like \f(CR\-\-only\-matching\fP, if there is more
than one match in a line, each of them causes a line of output.
.sp
Escape sequences starting with a dollar character may be used to insert the
contents of the matched part of the line and/or captured substrings into the
text.
.sp
$<digits> or ${<digits>} is replaced by the captured substring of the given
decimal number; $& (or the legacy $0) substitutes the whole match. If the
number is greater than the number of capturing substrings, or if the capture
is unset, the replacement is empty.
.sp
$a is replaced by bell; $b by backspace; $e by escape; $f by form feed; $n by
newline; $r by carriage return; $t by tab; $v by vertical tab.
.sp
$o<digits> or $o{<digits>} is replaced by the character whose code point is the
given octal number. In the first form, up to three octal digits are processed.
When more digits are needed in Unicode mode to specify a wide character, the
second form must be used.
.sp
$x<digits> or $x{<digits>} is replaced by the character represented by the
given hexadecimal number. In the first form, up to two hexadecimal digits are
processed. When more digits are needed in Unicode mode to specify a wide
character, the second form must be used.
.sp
Any other character is substituted by itself. In particular, $$ is replaced by
a single dollar.
.TP 10
\f(CR\-o\fP, \f(CR\-\-only\-matching\fP
Show only the part of the line that matched a pattern instead of the whole
line. In this mode, no context is shown. That is, the \f(CR\-A\fP, \f(CR\-B\fP, and
\f(CR\-C\fP options are ignored. If there is more than one match in a line, each
of them is shown separately, on a separate line of output. If \f(CR\-o\fP is
combined with \f(CR\-v\fP (invert the sense of the match to find non\-matching
lines), no output is generated, but the return code is set appropriately. If
the matched portion of the line is empty, nothing is output unless the file
name or line number are being printed, in which case they are shown on an
otherwise empty line. This option is mutually exclusive with \f(CR\-\-output\fP,
\f(CR\-\-file\-offsets\fP and \f(CR\-\-line\-offsets\fP.
.TP 10
\f(CR\-onumber\fP, \f(CR\-\-only\-matching\fP=\fInumber\fP
Show only the part of the line that matched the capturing parentheses of the
given number. Up to 50 capturing parentheses are supported by default. This
limit can be changed via the \f(CR\-\-om\-capture\fP option. A pattern may contain
any number of capturing parentheses, but only those whose number is within the
limit can be accessed by \f(CR\-o\fP. An error occurs if the number specified by
\f(CR\-o\fP is greater than the limit.
.sp
\-o0 is the same as \f(CR\-o\fP without a number. Because these options can be
given without an argument (see above), if an argument is present, it must be
given in the same shell item, for example, \-o3 or \-\-only\-matching=2. The
comments given for the non\-argument case above also apply to this option. If
the specified capturing parentheses do not exist in the pattern, or were not
set in the match, nothing is output unless the file name or line number are
being output.
.sp
If this option is given multiple times, multiple substrings are output for each
match, in the order the options are given, and all on one line. For example,
\-o3 \-o1 \-o3 causes the substrings matched by capturing parentheses 3 and 1 and
then 3 again to be output. By default, there is no separator (but see the next
but one option).
.TP 10
\f(CR\-\-om\-capture\fP=\fInumber\fP
Set the number of capturing parentheses that can be accessed by \f(CR\-o\fP. The
default is 50.
.TP 10
\f(CR\-\-om\-separator\fP=\fItext\fP
Specify a separating string for multiple occurrences of \f(CR\-o\fP. The default
is an empty string. Separating strings are never coloured.
.TP 10
\f(CR\-P\fP, \f(CR\-\-no\-ucp\fP
Starting from release 10.43, when UTF/Unicode mode is specified with \f(CR\-u\fP
or \f(CR\-U\fP, the PCRE2_UCP option is used by default. This means that the
POSIX classes in patterns match more than just ASCII characters. For example,
[:digit:] matches any Unicode decimal digit. The \f(CR\-\-no\-ucp\fP option
suppresses PCRE2_UCP, thus restricting the POSIX classes to ASCII characters,
as was the case in earlier releases. Note that there are now more fine\-grained
option settings within patterns that affect individual classes. For example,
when in UCP mode, the sequence (?aP) restricts [:word:] to ASCII letters, while
allowing \(rsw to match Unicode letters and digits.
.TP 10
\f(CR\-\-posix\-pattern\-file\fP
When patterns are provided with the \f(CR\-f\fP option, do not trim trailing
spaces or ignore empty lines in a similar way than other grep tools. To keep
the behaviour consistent with older versions, if the pattern read was
terminated with CRLF (as character literals) then both characters won't be
included as part of it, so if you really need to have pattern ending in \*(Aq\(rsr\*(Aq,
use a escape sequence or provide it by a different method.
.TP 10
\f(CR\-q\fP, \f(CR\-\-quiet\fP
Work quietly, that is, display nothing except error messages. The exit
status indicates whether or not any matches were found.
.TP 10
\f(CR\-r\fP, \f(CR\-\-recursive\fP
If any given path is a directory, recursively scan the files it contains,
taking note of any \f(CR\-\-include\fP and \f(CR\-\-exclude\fP settings. By default, a
directory is read as a normal file; in some operating systems this gives an
immediate end\-of\-file. This option is a shorthand for setting the \f(CR\-d\fP
option to "recurse".
.TP 10
\f(CR\-\-recursion\-limit\fP=\fInumber\fP
This is an obsolete synonym for \f(CR\-\-depth\-limit\fP. See \f(CR\-\-match\-limit\fP
above for details.
.TP 10
\f(CR\-s\fP, \f(CR\-\-no\-messages\fP
Suppress error messages about non\-existent or unreadable files. Such files are
quietly skipped. However, the return code is still 2, even if matches were
found in other files.
.TP 10
\f(CR\-t\fP, \f(CR\-\-total\-count\fP
This option is useful when scanning more than one file. If used on its own,
\f(CR\-t\fP suppresses all output except for a grand total number of matching
lines (or non\-matching lines if \f(CR\-v\fP is used) in all the files. If \f(CR\-t\fP
is used with \f(CR\-c\fP, a grand total is output except when the previous output
is just one line. In other words, it is not output when just one file's count
is listed. If file names are being output, the grand total is preceded by
"TOTAL:". Otherwise, it appears as just another number. The \f(CR\-t\fP option is
ignored when used with \f(CR\-L\fP (list files without matches), because the grand
total would always be zero.
.TP 10
\f(CR\-u\fP, \f(CR\-\-utf\fP
Operate in UTF/Unicode mode. This option is available only if PCRE2 has been
compiled with UTF\-8 support. All patterns (including those for any
\f(CR\-\-exclude\fP and \f(CR\-\-include\fP options) and all lines that are scanned
must be valid strings of UTF\-8 characters. If an invalid UTF\-8 string is
encountered, an error occurs.
.TP 10
\f(CR\-U\fP, \f(CR\-\-utf\-allow\-invalid\fP
As \f(CR\-\-utf\fP, but in addition subject lines may contain invalid UTF\-8 code
unit sequences. These can never form part of any pattern match. Patterns
themselves, however, must still be valid UTF\-8 strings. This facility allows
valid UTF\-8 strings to be sought within arbitrary byte sequences in executable
or other binary files. For more details about matching in non\-valid UTF\-8
strings, see the
\f(CRpcre2unicode\fP(3)
documentation.
.TP 10
\f(CR\-V\fP, \f(CR\-\-version\fP
Write the version numbers of \f(CRpcre2grep\fP and the PCRE2 library to the
standard output and then exit. Anything else on the command line is
ignored.
.TP 10
\f(CR\-v\fP, \f(CR\-\-invert\-match\fP
Invert the sense of the match, so that lines which do \fInot\fP match any of
the patterns are the ones that are found. When this option is set, options such
as \f(CR\-\-only\-matching\fP and \f(CR\-\-output\fP, which specify parts of a match
that are to be output, are ignored.
.TP 10
\f(CR\-w\fP, \f(CR\-\-word\-regex\fP, \f(CR\-\-word\-regexp\fP
Force the patterns only to match "words". That is, there must be a word
boundary at the start and end of each matched string. This is equivalent to
having "\(rsb(?:" at the start of each pattern, and ")\(rsb" at the end. This
option applies only to the patterns that are matched against the contents of
files; it does not apply to patterns specified by any of the \f(CR\-\-include\fP or
\f(CR\-\-exclude\fP options.
.TP 10
\f(CR\-x\fP, \f(CR\-\-line\-regex\fP, \f(CR\-\-line\-regexp\fP
Force the patterns to start matching only at the beginnings of lines, and in
addition, require them to match entire lines. In multiline mode the match may
be more than one line. This is equivalent to having "^(?:" at the start of each
pattern and ")$" at the end. This option applies only to the patterns that are
matched against the contents of files; it does not apply to patterns specified
by any of the \f(CR\-\-include\fP or \f(CR\-\-exclude\fP options.
.TP 10
\f(CR\-Z\fP, \f(CR\-\-null\fP
Terminate files names in the regular output with a zero byte (the NUL
character) instead of what would normally appear. This is useful when file
names contain unusual characters such as colons, hyphens, or even newlines. The
option does not apply to file names in error messages.
.PP
.SH "ENVIRONMENT VARIABLES"
.sp
The environment variables \f(CRLC_ALL\fP and \f(CRLC_CTYPE\fP are examined, in that
order, for a locale. The first one that is set is used. This can be overridden
by the \f(CR\-\-locale\fP option. If no locale is set, the PCRE2 library's default
(usually the "C" locale) is used.
.SH "NEWLINES"
.sp
The \f(CR\-N\fP (\f(CR\-\-newline\fP) option allows \f(CRpcre2grep\fP to scan files with
newline conventions that differ from the default. This option affects only the
way scanned files are processed. It does not affect the interpretation of files
specified by the \f(CR\-f\fP, \f(CR\-\-file\-list\fP, \f(CR\-\-exclude\-from\fP, or
\f(CR\-\-include\-from\fP options.
.sp
Any parts of the scanned input files that are written to the standard output
are copied with whatever newline sequences they have in the input. However, if
the final line of a file is output, and it does not end with a newline
sequence, a newline sequence is added. If the newline setting is CR, LF, CRLF
or NUL, that line ending is output; for the other settings (ANYCRLF or ANY) a
single NL is used.
.sp
The newline setting does not affect the way in which \f(CRpcre2grep\fP writes
newlines in informational messages to the standard output and error streams.
Under Windows, the standard output is set to be binary, so that "\(rsr\(rsn" at the
ends of output lines that are copied from the input is not converted to
"\(rsr\(rsr\(rsn" by the C I/O library. This means that any messages written to the
standard output must end with "\(rsr\(rsn". For all other operating systems, and
for all messages to the standard error stream, "\(rsn" is used.
.SH "OPTIONS COMPATIBILITY WITH GNU GREP"
.sp
Many of the short and long forms of \f(CRpcre2grep\fP\*(Aqs options are the same as
in the GNU \f(CRgrep\fP program. Any long option of the form \f(CR\-\-xxx\-regexp\fP
(GNU terminology) is also available as \f(CR\-\-xxx\-regex\fP (PCRE2 terminology).
However, the \f(CR\-\-case\-restrict\fP, \f(CR\-\-depth\-limit\fP, \f(CR\-E\fP,
\f(CR\-\-file\-list\fP, \f(CR\-\-file\-offsets\fP, \f(CR\-\-heap\-limit\fP,
\f(CR\-\-include\-dir\fP, \f(CR\-\-lf\fP, \f(CR\-\-line\-offsets\fP, \f(CR\-\-locale\fP, \f(CR\-\-match\-limit\fP,
\f(CR\-M\fP, \f(CR\-\-multiline\fP, \f(CR\-N\fP, \f(CR\-\-newline\fP, \f(CR\-\-no\-ucp\fP,
\f(CR\-\-om\-separator\fP, \f(CR\-\-output\fP, \f(CR\-P\fP, \f(CR\-u\fP, \f(CR\-\-utf\fP,
\f(CR\-U\fP, and \f(CR\-\-utf\-allow\-invalid\fP options are specific to
\f(CRpcre2grep\fP, as is the use of the \f(CR\-\-only\-matching\fP option with a
capturing parentheses number.
.sp
Although most of the common options work the same way, a few are different in
\f(CRpcre2grep\fP. For example, the \f(CR\-\-include\fP option's argument is a glob
for GNU \f(CRgrep\fP, but in \f(CRpcre2grep\fP it is a regular expression to which
the \f(CR\-i\fP option applies. If both the \f(CR\-c\fP and \f(CR\-l\fP options are
given, GNU grep lists only file names, without counts, but \f(CRpcre2grep\fP
gives the counts as well.
.SH "OPTIONS WITH DATA"
.sp
There are four different ways in which an option with data can be specified.
If a short form option is used, the data may follow immediately, or (with one
exception) in the next command line item. For example:
.sp
.ti +2
\-f/some/file
.br
.ti +2
\-f /some/file
.sp
The exception is the \f(CR\-o\fP option, which may appear with or without data.
Because of this, if data is present, it must follow immediately in the same
item, for example \-o3.
.sp
If a long form option is used, the data may appear in the same command line
item, separated by an equals character, or (with two exceptions) it may appear
in the next command line item. For example:
.sp
.ti +2
\-\-file=/some/file
.br
.ti +2
\-\-file /some/file
.sp
Note, however, that if you want to supply a file name beginning with ~ as data
in a shell command, and have the shell expand ~ to a home directory, you must
separate the file name from the option, because the shell does not treat ~
specially unless it is at the start of an item.
.sp
The exceptions to the above are the \f(CR\-\-colour\fP (or \f(CR\-\-color\fP) and
\f(CR\-\-only\-matching\fP options, for which the data is optional. If one of these
options does have data, it must be given in the first form, using an equals
character. Otherwise \f(CRpcre2grep\fP will assume that it has no data.
.SH "USING PCRE2'S CALLOUT FACILITY"
.sp
\f(CRpcre2grep\fP has, by default, support for calling external programs or
scripts or echoing specific strings during matching by making use of PCRE2's
callout facility. However, this support can be completely or partially disabled
when \f(CRpcre2grep\fP is built. You can find out whether your binary has support
for callouts by running it with the \f(CR\-\-help\fP option. If callout support is
completely disabled, callouts in patterns are forbidden by \f(CRpcre2grep\fP.
If the facility is partially disabled, calling external programs is not
supported, and callouts that request it are ignored.
.sp
A callout in a PCRE2 pattern is of the form (?C<arg>) where the argument is
either a number or a quoted string (see the
\f(CRpcre2callout\fP
documentation for details). Numbered callouts are ignored by \f(CRpcre2grep\fP;
only callouts with string arguments are useful.
.SS "Echoing a specific string"
.sp
Starting the callout string with a pipe character invokes an echoing facility
that avoids calling an external program or script. This facility is always
available, provided that callouts were not completely disabled when
\f(CRpcre2grep\fP was built. The rest of the callout string is processed as a
zero\-terminated string, which means it should not contain any internal binary
zeros. It is written to the output, having first been passed through the same
escape processing as text from the \f(CR\-\-output\fP (\f(CR\-O\fP) option (see
above). However, $0 or $& cannot be used to insert a matched substring because
the match is still in progress. Instead, the single character \*(Aq0\*(Aq is inserted.
Any syntax errors in the string (for example, a dollar not followed by another
character) causes the callout to be ignored. No terminator is added to the
output string, so if you want a newline, you must include it explicitly using
the escape $n. For example:
.sp
.ti +2
pcre2grep \*(Aq(.)(..(.))(?C"|[$1] [$2] [$3]$n")\*(Aq <some file>
.sp
Matching continues normally after the string is output. If you want to see only
the callout output but not any output from an actual match, you should end the
pattern with (*FAIL).
.SS "Calling external programs or scripts"
.sp
This facility can be independently disabled when \f(CRpcre2grep\fP is built. It
is supported for Windows, where a call to \f(CR_spawnvp()\fP is used, for VMS,
where \f(CRlib$spawn()\fP is used, and for any Unix\-like environment where
\f(CRfork()\fP and \f(CRexecv()\fP are available.
.sp
If the callout string does not start with a pipe (vertical bar) character, it
is parsed into a list of substrings separated by pipe characters. The first
substring must be an executable name, with the following substrings specifying
arguments:
.sp
.ti +2
executable_name|arg1|arg2|...
.sp
Any substring (including the executable name) may contain escape sequences
started by a dollar character. These are the same as for the \f(CR\-\-output\fP
(\f(CR\-O\fP) option documented above, except that $0 or $& cannot insert the
matched string because the match is still in progress. Instead, the character
\*(Aq0\*(Aq is inserted. If you need a literal dollar or pipe character in any
substring, use $$ or $| respectively. Here is an example:
.sp
.ti +2
echo \-e "abcde\(rsn12345" | pcre2grep \(rs
.br
.ti +2
  \*(Aq(?x)(.)(..(.))
.br
.ti +2
  (?C"/bin/echo|Arg1: [$1] [$2] [$3]|Arg2: $|${1}$| ($4)")()\*(Aq \-
.sp
.ti +2
Output:
.sp
.ti +2
  Arg1: [a] [bcd] [d] Arg2: |a| ()
.br
.ti +2
  abcde
.br
.ti +2
  Arg1: [1] [234] [4] Arg2: |1| ()
.br
.ti +2
  12345
.sp
The parameters for the system call that is used to run the program or script
are zero\-terminated strings. This means that binary zero characters in the
callout argument will cause premature termination of their substrings, and
therefore should not be present. Any syntax errors in the string (for example,
a dollar not followed by another character) causes the callout to be ignored.
If running the program fails for any reason (including the non\-existence of the
executable), a local matching failure occurs and the matcher backtracks in the
normal way.
.SH "MATCHING ERRORS"
.sp
It is possible to supply a regular expression that takes a very long time to
fail to match certain lines. Such patterns normally involve nested indefinite
repeats, for example: (a+)*\(rsd when matched against a line of a's with no final
digit. The PCRE2 matching function has a resource limit that causes it to abort
in these circumstances. If this happens, \f(CRpcre2grep\fP outputs an error
message and the line that caused the problem to the standard error stream. If
there are more than 20 such errors, \f(CRpcre2grep\fP gives up.
.sp
The \f(CR\-\-match\-limit\fP option of \f(CRpcre2grep\fP can be used to set the
overall resource limit. There are also other limits that affect the amount of
memory used during matching; see the discussion of \f(CR\-\-heap\-limit\fP and
\f(CR\-\-depth\-limit\fP above.
.SH "DIAGNOSTICS"
.sp
Exit status is 0 if any matches were found, 1 if no matches were found, and 2
for syntax errors, overlong lines, non\-existent or inaccessible files (even if
matches were found in other files) or too many matching errors. Using the
\f(CR\-s\fP option to suppress error messages about inaccessible files does not
affect the return code.
.sp
When run under VMS, the return code is placed in the symbol PCRE2GREP_RC
because VMS does not distinguish between exit(0) and exit(1).
.SH "SEE ALSO"
.sp
\f(CRpcre2pattern\fP(3), \f(CRpcre2syntax\fP(3), \f(CRpcre2callout\fP(3),
\f(CRpcre2unicode\fP(3).
.SH "AUTHOR"
.sp
.nf
.fam C
Philip Hazel
Retired from University Computing Service
Cambridge, England.
.fam
.fi
.SH "REVISION"
.sp
Last updated: 24 January 2025
.br
Copyright (c) 1997\-2023 University of Cambridge.