'\" t
.\"     Title: pcre2_jit_stack_create
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 23 January 2023
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_JIT_STACK_CREATE" "3" "23 January 2023" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_jit_stack_create \- create a stack for JIT matching
.SH "SYNOPSIS"
.sp
.nf
.fam C
#include <pcre2.h>

pcre2_jit_stack *pcre2_jit_stack_create(
      size_t startsize, size_t maxsize,
      pcre2_general_context *gcontext);
.fam
.fi
.SH "DESCRIPTION"
.sp
This function is used to create a stack for use by the code compiled by the JIT
compiler. The first two arguments are a starting size for the stack, and a
maximum size to which it is allowed to grow. The final argument is a general
context, for memory allocation functions, or NULL for standard memory
allocation. The result can be passed to the JIT run\-time code by calling
\f(CRpcre2_jit_stack_assign()\fP to associate the stack with a compiled pattern,
which can then be processed by \f(CRpcre2_match()\fP or \f(CRpcre2_jit_match()\fP.
A maximum stack size of 512KiB to 1MiB should be more than enough for any
pattern. If the stack couldn't be allocated or the values passed were not
reasonable, NULL will be returned. For more details, see the
\f(CRpcre2jit\fP
page.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.