'\" t
.\"     Title: pcre2_set_substitute_case_callout
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 26 December 2024
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SET_SUBSTITUTE_CASE_CALLOUT" "3" "26 December 2024" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_set_substitute_case_callout \- set a substitution case callout function
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint\fP pcre2_set_substitute_case_callout(
      \fBpcre2_match_context\fP *\fImcontext\fP,
      \fBPCRE2_SIZE\fP (*\fIsubstitute_case_callout\fP)(
          \fBPCRE2_SPTR\fP \fIinput\fP, \fBPCRE2_SIZE\fP \fIinput_length\fP,
          \fBPCRE2_UCHAR\fP *\fIoutput\fP, \fBPCRE2_SIZE\fP \fIoutput_capacity\fP,
          \fBint\fP \fIcase_operation\fP, \fBvoid\fP *\fIsubstitute_case_callout_data\fP),
      \fBvoid\fP *\fIsubstitute_case_callout_data\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function sets the substitute case callout fields in a match context (the
first argument). The second argument specifies a callout function, and the third
argument is an opaque data item that is passed to it. The result of this
function is always zero.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.