'\" t
.\"     Title: pcre2_set_compile_recursion_guard
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 26 November 2014
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SET_COMPILE_RECURSION_GUARD" "3" "26 November 2014" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_set_compile_recursion_guard \- set up a compile recursion guard function
.SH "SYNOPSIS"
.sp
.nf
.fam C
#include <pcre2.h>

int pcre2_set_compile_recursion_guard(pcre2_compile_context *ccontext,
                                      int (*guard)(uint32_t depth,
                                                   void *user_data),
                                      void *user_data);
.fam
.fi
.SH "DESCRIPTION"
.sp
This function defines, within a compile context, a function that is called
whenever \f(CRpcre2_compile()\fP starts to compile a parenthesized part of a
pattern. The first argument to the function gives the current depth of
parenthesis nesting, and the second is user data that is supplied when the
function is set up. The callout function should return zero if all is well, or
non\-zero to force an error. This feature is provided so that applications can
check the available system stack space, in order to avoid running out. The
result of \f(CRpcre2_set_compile_recursion_guard()\fP is always zero.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.