'\" t
.\"     Title: pcre2_get_ovector_count
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 25 October 2014
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_GET_OVECTOR_COUNT" "3" "25 October 2014" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_get_ovector_count \- get the ovector count
.SH "SYNOPSIS"
.sp
.nf
.fam C
#include <pcre2.h>

uint32_t pcre2_get_ovector_count(pcre2_match_data *match_data);
.fam
.fi
.SH "DESCRIPTION"
.sp
This function returns the number of pairs of offsets in the ovector that forms
part of the given match data block.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.