'\" t
.\"     Title: pcre2_maketables
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 26 February 2025
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_MAKETABLES" "3" "26 February 2025" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_maketables \- build character tables in current locale
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBconst\fP \fBuint8_t\fP *pcre2_maketables(\fBpcre2_general_context\fP *\fIgcontext\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function builds a set of character tables for character code points that
are less than 256. These can be passed to pcre2_compile() in a compile
context in order to override the internal, built\-in tables (which were either
defaulted or made by pcre2_maketables() when PCRE2 was compiled). See the
pcre2_set_character_tables()
page. You might want to do this if you are using a non\-standard locale.
.sp
If the argument is \fBNULL\fP, \f(CRmalloc()\fP is used to get memory for the tables.
Otherwise it must point to a general context, which can supply pointers to a
custom memory manager. The function yields a pointer to the tables.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.