'\" t
.\"     Title: pcre2_serialize_encode
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 13 August 2018
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SERIALIZE_ENCODE" "3" "13 August 2018" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_serialize_encode \- serialize compiled patterns for save/restore
.SH "SYNOPSIS"
.sp
.nf
.fam C
#include <pcre2.h>

int32_t pcre2_serialize_encode(const pcre2_code **codes,
                               int32_t number_of_codes,
                               uint8_t **serialized_bytes,
                               PCRE2_SIZE *serialized_size,
                               pcre2_general_context *gcontext);
.fam
.fi
.SH "DESCRIPTION"
.sp
This function encodes a list of compiled patterns into a byte stream that can
be saved on disc or elsewhere. Note that this is not an abstract format like
Java or .NET. Conversion of the byte stream back into usable compiled patterns
can only happen on a host that is running the same version of PCRE2, with the
same code unit width, and the host must also have the same endianness, pointer
width and PCRE2_SIZE type. The arguments for \f(CRpcre2_serialize_encode()\fP
are:
.sp
.ti +2
\fIcodes\fP             pointer to a vector containing the list
.br
.ti +2
\fInumber_of_codes\fP   number of slots in the vector
.br
.ti +2
\fIserialized_bytes\fP  set to point to the serialized byte stream
.br
.ti +2
\fIserialized_size\fP   set to the number of bytes in the byte stream
.br
.ti +2
\fIgcontext\fP          pointer to a general context or NULL
.sp
The context argument is used to obtain memory for the byte stream. When the
serialized data is no longer needed, it must be freed by calling
\f(CRpcre2_serialize_free()\fP. The yield of the function is the number of
serialized patterns, or one of the following negative error codes:
.sp
.ti +2
PCRE2_ERROR_BADDATA      \fInumber_of_codes\fP is zero or less
.br
.ti +2
PCRE2_ERROR_BADMAGIC     mismatch of id bytes in one of the patterns
.br
.ti +2
PCRE2_ERROR_MEMORY       memory allocation failed
.br
.ti +2
PCRE2_ERROR_MIXEDTABLES  the patterns do not all use the same tables
.br
.ti +2
PCRE2_ERROR_NULL         an argument other than \fIgcontext\fP is NULL
.sp
PCRE2_ERROR_BADMAGIC means either that a pattern's code has been corrupted, or
that a slot in the vector does not point to a compiled pattern.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the serialization functions in the
\f(CRpcre2serialize\fP
page.