'\" t
.\"     Title: pcre2partial
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 16 August 2026
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2PARTIAL" "3" "16 August 2026" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2partial \- PCRE2 partial matching
.SH "PARTIAL MATCHING IN PCRE2"
.sp
In normal use of PCRE2, if there is a match up to the end of a subject string,
but more characters are needed to match the entire pattern, \fBPCRE2_ERROR_NOMATCH\fP
is returned, just like any other failing match. There are circumstances where
it might be helpful to distinguish this "partial match" case.
.sp
One example is an application where the subject string is very long, and not
all available at once. The requirement here is to be able to do the matching
segment by segment, but special action is needed when a matched substring spans
the boundary between two segments.
.sp
Another example is checking a user input string as it is typed, to ensure that
it conforms to a required format. Invalid characters can be immediately
diagnosed and rejected, giving instant feedback.
.sp
Partial matching is a PCRE2\-specific feature; it is not Perl\-compatible. It is
requested by setting one of the \fBPCRE2_PARTIAL_HARD\fP or \fBPCRE2_PARTIAL_SOFT\fP
options when calling a matching function. The difference between the two
options is whether or not a partial match is preferred to an alternative
complete match, though the details differ between the two types of matching
function. If both options are set, \fBPCRE2_PARTIAL_HARD\fP takes precedence.
.sp
If you want to use partial matching with just\-in\-time optimized code, as well
as setting a partial match option for the matching function, you must also call
pcre2_jit_compile() with one or both of these options:
.sp
.RS 4
.PD 0
.TP 7
\fBPCRE2_JIT_PARTIAL_HARD\fP, \fBPCRE2_JIT_PARTIAL_SOFT\fP
.ad l
\fBPCRE2_JIT_COMPLETE\fP should also be set if you are going to run non\-partial
matches on the same pattern. Separate code is compiled for each mode. If the
appropriate JIT mode has not been compiled, interpretive matching code is used.
.PD
.RE
.PP
.ad l
.sp
Setting a partial matching option disables two of PCRE2\(cqs standard
optimization hints. PCRE2 remembers the last literal code unit in a pattern,
and abandons matching immediately if it is not present in the subject string.
This optimization cannot be used for a subject string that might match only
partially. PCRE2 also remembers a minimum length of a matching string, and does
not bother to run the matching function on shorter strings. This optimization
is also disabled for partial matching.
.SH "REQUIREMENTS FOR A PARTIAL MATCH"
.sp
A possible partial match occurs during matching when the end of the subject
string is reached successfully, but either more characters are needed to
complete the match, or the addition of more characters might change what is
matched.
.sp
Example 1: if the pattern is \f(CRabc\fP and the subject is \f(CRab\fP, more characters are
definitely needed to complete a match. In this case both hard and soft matching
options yield a partial match.
.sp
Example 2: if the pattern is \f(CRab+\fP and the subject is \f(CRab\fP, a complete match
can be found, but the addition of more characters might change what is
matched. In this case, only \fBPCRE2_PARTIAL_HARD\fP returns a partial match;
\fBPCRE2_PARTIAL_SOFT\fP returns the complete match.
.sp
On reaching the end of the subject, when \fBPCRE2_PARTIAL_HARD\fP is set, if the next
pattern item is \f(CR\(rsz\fP, \f(CR\(rsZ\fP, \f(CR\(rsb\fP, \f(CR\(rsB\fP, or \f(CR$\fP there is always a partial match.
Otherwise, for both options, the next pattern item must be one that inspects a
character, and at least one of the following must be true:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
At least one character has already been inspected. An inspected character
need not form part of the final matched string; lookbehind assertions and the
\f(CR\(rsK\fP escape sequence provide ways of inspecting characters before the start of a
matched string.
.RE
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
The pattern contains one or more lookbehind assertions. This condition
exists in case there is a lookbehind that inspects characters before the start
of the match.
.RE
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 3." 4.2
.\}
There is a special case when the whole pattern can match an empty string.
When the starting point is at the end of the subject, the empty string match is
a possibility, and if \fBPCRE2_PARTIAL_SOFT\fP is set and neither of the above
conditions is true, it is returned. However, because adding more characters
might result in a non\-empty match, \fBPCRE2_PARTIAL_HARD\fP returns a partial match,
which in this case means "there is going to be a match at this point, but until
some more characters are added, we do not know if it will be an empty string or
something longer".
.RE
.SH "PARTIAL MATCHING USING pcre2_match()"
.sp
When a partial matching option is set, the result of calling
pcre2_match() can be one of the following:
.sp
.RS 4
.PD 0
.TP 20
A successful match
.ad l
A complete match has been found, starting and ending within this subject.
.TP 20
\fBPCRE2_ERROR_NOMATCH\fP
.ad l
No match can start anywhere in this subject.
.TP 20
\fBPCRE2_ERROR_PARTIAL\fP
.ad l
Adding more characters may result in a complete match that uses one or more
characters from the end of this subject.
.PD
.RE
.PP
.ad l
.sp
When a partial match is returned, the first two elements in the ovector point
to the portion of the subject that was matched, but the values in the rest of
the ovector are undefined. The appearance of \f(CR\(rsK\fP in the pattern has no effect
for a partial match. Consider this pattern:
.sp
.ss \n[.ss]
.nf
.fam C
abc\(rsK123
.fam
.fi
.ss \n[.ss] 0
.sp
If it is matched against \f(CR456abc123xyz\fP the result is a complete match, and the
ovector defines the matched string as \f(CR123\fP, because \f(CR\(rsK\fP resets the "start of
match" point. However, if a partial match is requested and the subject string
is \f(CR456abc12\fP, a partial match is found for the string \f(CRabc12\fP, because all
these characters are needed for a subsequent re\-match with additional
characters.
.sp
If there is more than one partial match, the first one that was found provides
the data that is returned. Consider this pattern:
.sp
.ss \n[.ss]
.nf
.fam C
123\(rsw+X|dogY
.fam
.fi
.ss \n[.ss] 0
.sp
If this is matched against the subject string \f(CRabc123dog\fP, both alternatives
fail to match, but the end of the subject is reached during matching, so
\fBPCRE2_ERROR_PARTIAL\fP is returned. The offsets are set to 3 and 9, identifying
\f(CR123dog\fP as the first partial match. (In this example, there are two partial
matches, because \f(CRdog\fP on its own partially matches the second alternative.)
.SS "How a partial match is processed by pcre2_match()"
.sp
What happens when a partial match is identified depends on which of the two
partial matching options is set.
.sp
If \fBPCRE2_PARTIAL_HARD\fP is set, \fBPCRE2_ERROR_PARTIAL\fP is returned as soon as a
partial match is found, without continuing to search for possible complete
matches. This option is "hard" because it prefers an earlier partial match over
a later complete match. For this reason, the assumption is made that the end of
the supplied subject string is not the true end of the available data, which is
why \f(CR\(rsz\fP, \f(CR\(rsZ\fP, \f(CR\(rsb\fP, \f(CR\(rsB\fP, and \f(CR$\fP always give a partial match.
.sp
If \fBPCRE2_PARTIAL_SOFT\fP is set, the partial match is remembered, but matching
continues as normal, and other alternatives in the pattern are tried. If no
complete match can be found, \fBPCRE2_ERROR_PARTIAL\fP is returned instead of
\fBPCRE2_ERROR_NOMATCH\fP. This option is "soft" because it prefers a complete match
over a partial match. All the various matching items in a pattern behave as if
the subject string is potentially complete; \f(CR\(rsz\fP, \f(CR\(rsZ\fP, and \f(CR$\fP match at the end of
the subject, as normal, and for \f(CR\(rsb\fP and \f(CR\(rsB\fP the end of the subject is treated
as a non\-alphanumeric.
.sp
The difference between the two partial matching options can be illustrated by a
pattern such as:
.sp
.ss \n[.ss]
.nf
.fam C
dog(sbody)?
.fam
.fi
.ss \n[.ss] 0
.sp
This matches either \f(CRdog\fP or \f(CRdogsbody\fP, greedily (that is, it prefers the
longer string if possible). If it is matched against the string \f(CRdog\fP with
\fBPCRE2_PARTIAL_SOFT\fP, it yields a complete match for \f(CRdog\fP. However, if
\fBPCRE2_PARTIAL_HARD\fP is set, the result is \fBPCRE2_ERROR_PARTIAL\fP. On the other
hand, if the pattern is made ungreedy the result is different:
.sp
.ss \n[.ss]
.nf
.fam C
dog(sbody)??
.fam
.fi
.ss \n[.ss] 0
.sp
In this case the result is always a complete match because that is found first,
and matching never continues after finding a complete match. It might be easier
to follow this explanation by thinking of the two patterns like this:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRdog(sbody)?\fP    is the same as  \f(CRdogsbody|dog\fP
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\f(CRdog(sbody)??\fP   is the same as  \f(CRdog|dogsbody\fP
.RE
.sp
The second pattern will never match \f(CRdogsbody\fP, because it will always find the
shorter match first.
.SS "Example of partial matching using pcre2test"
.sp
The \f(CRpcre2test\fP data modifiers \f(CRpartial_hard\fP (or \f(CRph\fP) and
\f(CRpartial_soft\fP (or \f(CRps\fP) set \fBPCRE2_PARTIAL_HARD\fP and \fBPCRE2_PARTIAL_SOFT\fP,
respectively, when calling pcre2_match(). Here is a run of
\f(CRpcre2test\fP using a pattern that matches the whole subject in the form of a
date:
.sp
.ss \n[.ss]
.nf
.fam C
  re> /^\(rsd?\(rsd(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\(rsd\(rsd$/
data> 25dec3\(rs=ph
Partial match: 23dec3
data> 3ju\(rs=ph
Partial match: 3ju
data> 3juj\(rs=ph
No match
.fam
.fi
.ss \n[.ss] 0
.sp
This example gives the same results for both hard and soft partial matching
options. Here is an example where there is a difference:
.sp
.ss \n[.ss]
.nf
.fam C
  re> /^\(rsd?\(rsd(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\(rsd\(rsd$/
data> 25jun04\(rs=ps
 0: 25jun04
 1: jun
data> 25jun04\(rs=ph
Partial match: 25jun04
.fam
.fi
.ss \n[.ss] 0
.sp
With \fBPCRE2_PARTIAL_SOFT\fP, the subject is matched completely. For
\fBPCRE2_PARTIAL_HARD\fP, however, the subject is assumed not to be complete, so
there is only a partial match.
.SH "MULTI\-SEGMENT MATCHING WITH pcre2_match()"
.sp
PCRE was not originally designed with multi\-segment matching in mind. However,
over time, features (including partial matching) that make multi\-segment
matching possible have been added. A very long string can be searched segment
by segment by calling pcre2_match() repeatedly, with the aim of achieving
the same results that would happen if the entire string was available for
searching all the time. Normally, the strings that are being sought are much
shorter than each individual segment, and are in the middle of very long
strings, so the pattern is normally not anchored.
.sp
Special logic must be implemented to handle a matched substring that spans a
segment boundary. \fBPCRE2_PARTIAL_HARD\fP should be used, because it returns a
partial match at the end of a segment whenever there is the possibility of
changing the match by adding more characters. The \fBPCRE2_NOTBOL\fP option should
also be set for all but the first segment.
.sp
When a partial match occurs, the next segment must be added to the current
subject and the match re\-run, using the \fIstartoffset\fP argument of
pcre2_match() to begin at the point where the partial match started.
For example:
.sp
.ss \n[.ss]
.nf
.fam C
  re> /\(rsd?\(rsd(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\(rsd\(rsd/
data> ...the date is 23ja\(rs=ph
Partial match: 23ja
data> ...the date is 23jan19 and on that day...\(rs=offset=15
 0: 23jan19
 1: jan
.fam
.fi
.ss \n[.ss] 0
.sp
Note the use of the \f(CRoffset\fP modifier to start the new match where the
partial match was found. In this example, the next segment was added to the one
in which the partial match was found. This is the most straightforward
approach, typically using a memory buffer that is twice the size of each
segment. After a partial match, the first half of the buffer is discarded, the
second half is moved to the start of the buffer, and a new segment is added
before repeating the match as in the example above. After a no match, the
entire buffer can be discarded.
.sp
If there are memory constraints, you may want to discard text that precedes a
partial match before adding the next segment. Unfortunately, this is not at
present straightforward. In cases such as the above, where the pattern does not
contain any lookbehinds, it is sufficient to retain only the partially matched
substring. However, if the pattern contains a lookbehind assertion, characters
that precede the start of the partial match may have been inspected during the
matching process. When \f(CRpcre2test\fP displays a partial match, it indicates
these characters with \f(CR<\fP if the \f(CRallusedtext\fP modifier is set:
.sp
.ss \n[.ss]
.nf
.fam C
  re> "(?<=123)abc"
data> xx123ab\(rs=ph,allusedtext
Partial match: 123ab
               <<<
.fam
.fi
.ss \n[.ss] 0
.sp
However, the \f(CRallusedtext\fP modifier is not available for JIT matching,
because JIT matching does not record the first (or last) consulted characters.
For this reason, this information is not available via the API. It is therefore
not possible in general to obtain the exact number of characters that must be
retained in order to get the right match result. If you cannot retain the
entire segment, you must find some heuristic way of choosing.
.sp
If you know the approximate length of the matching substrings, you can use that
to decide how much text to retain. The only lookbehind information that is
currently available via the API is the length of the longest individual
lookbehind in a pattern, but this can be misleading if there are nested
lookbehinds. The value returned by calling pcre2_pattern_info() with the
\fBPCRE2_INFO_MAXLOOKBEHIND\fP option is the maximum number of characters (not code
units) that any individual lookbehind moves back when it is processed. A
pattern such as \f(CR(?<=(?<!b)a)\fP has a maximum lookbehind value of one, but
inspects two characters before its starting point.
.sp
In a non\-UTF or a 32\-bit case, moving back is just a subtraction, but in
UTF\-8 or UTF\-16 you have to count characters while moving back through the code
units.
.SH "PARTIAL MATCHING USING pcre2_dfa_match()"
.sp
The DFA function moves along the subject string character by character, without
backtracking, searching for all possible matches simultaneously. If the end of
the subject is reached before the end of the pattern, there is the possibility
of a partial match.
.sp
When \fBPCRE2_PARTIAL_SOFT\fP is set, \fBPCRE2_ERROR_PARTIAL\fP is returned only if there
have been no complete matches. Otherwise, the complete matches are returned.
If \fBPCRE2_PARTIAL_HARD\fP is set, a partial match takes precedence over any
complete matches. The portion of the string that was matched when the longest
partial match was found is set as the first matching string.
.sp
Because the DFA function always searches for all possible matches, and there is
no difference between greedy and ungreedy repetition, its behaviour is
different from pcre2_match(). Consider the string \f(CRdog\fP matched
against this ungreedy pattern:
.sp
.ss \n[.ss]
.nf
.fam C
dog(sbody)??
.fam
.fi
.ss \n[.ss] 0
.sp
Whereas the standard function stops as soon as it finds the complete match for
\f(CRdog\fP, the DFA function also finds the partial match for \f(CRdogsbody\fP, and so
returns that when \fBPCRE2_PARTIAL_HARD\fP is set.
.SH "MULTI\-SEGMENT MATCHING WITH pcre2_dfa_match()"
.sp
When a partial match has been found using the DFA matching function, it is
possible to continue the match by providing additional subject data and calling
the function again with the same compiled regular expression, this time setting
the \fBPCRE2_DFA_RESTART\fP option. You must pass the same working space as before,
because this is where details of the previous partial match are stored. You can
set the \fBPCRE2_PARTIAL_SOFT\fP or \fBPCRE2_PARTIAL_HARD\fP options with \fBPCRE2_DFA_RESTART\fP
to continue partial matching over multiple segments. Here is an example using
\f(CRpcre2test\fP:
.sp
.ss \n[.ss]
.nf
.fam C
  re> /^\(rsd?\(rsd(jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)\(rsd\(rsd$/
data> 23ja\(rs=dfa,ps
Partial match: 23ja
data> n05\(rs=dfa,dfa_restart
 0: n05
.fam
.fi
.ss \n[.ss] 0
.sp
The first call has \f(CR23ja\fP as the subject, and requests partial matching; the
second call has \f(CRn05\fP as the subject for the continued (restarted) match.
Notice that when the match is complete, only the last part is shown; PCRE2 does
not retain the previously partially\-matched string. It is up to the calling
program to do that if it needs to. This means that, for an unanchored pattern,
if a continued match fails, it is not possible to try again at a new starting
point. All this facility is capable of doing is continuing with the previous
match attempt. For example, consider this pattern:
.sp
.ss \n[.ss]
.nf
.fam C
1234|3789
.fam
.fi
.ss \n[.ss] 0
.sp
If the first part of the subject is \f(CRABC123\fP, a partial match of the first
alternative is found at offset 3. There is no partial match for the second
alternative, because such a match does not start at the same point in the
subject string. Attempting to continue with the string \f(CR7890\fP does not yield a
match because only those alternatives that match at one point in the subject
are remembered. Depending on the application, this may or may not be what you
want.
.sp
If you do want to allow for starting again at the next character, one way of
doing it is to retain some or all of the segment and try a new complete match,
as described for pcre2_match() above. Another possibility is to work with
two buffers. If a partial match at offset \fIn\fP in the first buffer is
followed by "no match" when \fBPCRE2_DFA_RESTART\fP is used on the second buffer, you
can then try a new match starting at offset \fIn\fP+1 in the first buffer.
.sp
Therefore, \fBPCRE2_DFA_RESTART\fP does not remove the need to keep earlier subject
data. In order to perform a bumpalong and continue matching at the next
character, all subject data from the current match start must be retained,
together with enough preceding data to satisfy the requirements of lookbehind
assertions (remembering as above that \fBPCRE2_INFO_MAXLOOKBEHIND\fP only describes
the buffer requirement of a single lookbehind, and nested lookbehinds can read
back further from the match start). This makes streaming match processing
using \fBPCRE2_DFA_RESTART\fP challenging, and the application cannot easily set a
bound on the number of chunks to buffer. For multi\-segment searching that is
intended to produce the same result as searching the whole subject, it is
usually simpler to avoid \fBPCRE2_DFA_RESTART\fP and run a fresh match, using either
matching function, over the retained text.
.SS "Author"
.sp
Philip Hazel
.br
Retired from University Computing Service
.br
Cambridge, England.
.SS "Revision"
.sp
Last updated: 16 August 2026
.br
Copyright \(co 1997\-2019 University of Cambridge.