'\" t
.\"     Title: pcre2_substring_list_get
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 21 October 2014
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SUBSTRING_LIST_GET" "3" "21 October 2014" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_substring_list_get \- extract all substrings into new memory
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint\fP pcre2_substring_list_get(\fBpcre2_match_data\fP *\fImatch_data\fP,
                             \fBPCRE2_UCHAR\fP ***\fIlistptr\fP,
                             \fBPCRE2_SIZE\fP **\fIlengthsptr\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This is a convenience function for extracting all the captured substrings after
a pattern match. It builds a list of pointers to the strings, and (optionally)
a second list that contains their lengths (in code units), excluding a
terminating zero that is added to each of them. All this is done in a single
block of memory that is obtained using the same memory allocation function that
was used to get the match data block. The convenience function
pcre2_substring_list_free() can be used to free it when it is no longer
needed. The arguments are:
.sp
.RS 4
.PD 0
.TP 11
\fImatch_data\fP
.ad l
The match data block
.TP 11
\fIlistptr\fP
.ad l
Where to put a pointer to the list
.TP 11
\fIlengthsptr\fP
.ad l
Where to put a pointer to the lengths, or \fBNULL\fP
.PD
.RE
.PP
.ad l
.sp
A pointer to a list of pointers is put in the variable whose address is in
\fIlistptr\fP. The list is terminated by a \fBNULL\fP pointer. If \fIlengthsptr\fP is
not \fBNULL\fP, a matching list of lengths is created, and its address is placed in
\fIlengthsptr\fP. The yield of the function is zero on success or
\fBPCRE2_ERROR_NOMEMORY\fP if sufficient memory could not be obtained.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.