'\" t
.\"     Title: pcre2_compile
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 30 October 2024
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_COMPILE" "3" "30 October 2024" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_compile \- compile a regular expression pattern
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBpcre2_code\fP *pcre2_compile(\fBPCRE2_SPTR\fP \fIpattern\fP, \fBPCRE2_SIZE\fP \fIpatlen\fP,
                          \fBuint32_t\fP \fIoptions\fP, \fBint\fP *\fIerrorptr\fP,
                          \fBPCRE2_SIZE\fP *\fIerroroffset\fP,
                          \fBpcre2_compile_context\fP *\fIccontext\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function compiles a regular expression pattern into an internal form. Its
arguments are:
.sp
.RS 4
.PD 0
.TP 12
\fIpattern\fP
.ad l
A string containing expression to be compiled
.TP 12
\fIpatlen\fP
.ad l
The length of the string or \fBPCRE2_ZERO_TERMINATED\fP
.TP 12
\fIoptions\fP
.ad l
Primary option bits
.TP 12
\fIerrorptr\fP
.ad l
Where to put an error code
.TP 12
\fIerroroffset\fP
.ad l
Where to put an error offset
.TP 12
\fIccontext\fP
.ad l
Pointer to a compile context or \fBNULL\fP
.PD
.RE
.PP
.ad l
.sp
The length of the pattern and any error offset that is returned are in code
units, not characters. A \fBNULL\fP pattern with zero length is treated as an empty
string. A compile context is needed only if you want to provide custom memory
allocation functions, or to provide an external function for system stack size
checking (see pcre2_set_compile_recursion_guard()), or to change one or
more of these parameters:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
What \f(CR\(rsR\fP matches (Unicode newlines, or CR, LF, CRLF only);
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
PCRE2\(cqs character tables;
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The newline character sequence;
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The compile time nested parentheses limit;
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The maximum pattern length (in code units) that is allowed;
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
The additional options bits.
.RE
.sp
The primary option bits are:
.sp
.RS 4
.PD 0
.TP 26
\fBPCRE2_ANCHORED\fP
.ad l
Force pattern anchoring
.TP 26
\fBPCRE2_ALLOW_EMPTY_CLASS\fP
.ad l
Allow empty classes
.TP 26
\fBPCRE2_ALT_BSUX\fP
.ad l
Alternative handling of \f(CR\(rsu\fP, \f(CR\(rsU\fP, and \f(CR\(rsx\fP
.TP 26
\fBPCRE2_ALT_CIRCUMFLEX\fP
.ad l
Alternative handling of \f(CR^\fP in multiline mode
.TP 26
\fBPCRE2_ALT_EXTENDED_CLASS\fP
.ad l
Alternative extended character class syntax
.TP 26
\fBPCRE2_ALT_VERBNAMES\fP
.ad l
Process backslashes in verb names
.TP 26
\fBPCRE2_AUTO_CALLOUT\fP
.ad l
Compile automatic callouts
.TP 26
\fBPCRE2_CASELESS\fP
.ad l
Do caseless matching
.TP 26
\fBPCRE2_DOLLAR_ENDONLY\fP
.ad l
\f(CR$\fP not to match newline at end
.TP 26
\fBPCRE2_DOTALL\fP
.ad l
\f(CR.\fP matches anything including NL
.TP 26
\fBPCRE2_DUPNAMES\fP
.ad l
Allow duplicate names for subpatterns
.TP 26
\fBPCRE2_ENDANCHORED\fP
.ad l
Pattern can match only at end of subject
.TP 26
\fBPCRE2_EXTENDED\fP
.ad l
Ignore white space and \f(CR#\fP comments
.TP 26
\fBPCRE2_FIRSTLINE\fP
.ad l
Force matching to be before newline
.TP 26
\fBPCRE2_LITERAL\fP
.ad l
Pattern characters are all literal
.TP 26
\fBPCRE2_MATCH_INVALID_UTF\fP
.ad l
Enable support for matching invalid UTF
.TP 26
\fBPCRE2_MATCH_UNSET_BACKREF\fP
.ad l
Match unset backreferences
.TP 26
\fBPCRE2_MULTILINE\fP
.ad l
\f(CR^\fP and \f(CR$\fP match newlines within data
.TP 26
\fBPCRE2_NEVER_BACKSLASH_C\fP
.ad l
Lock out the use of \f(CR\(rsC\fP in patterns
.TP 26
\fBPCRE2_NEVER_UCP\fP
.ad l
Lock out \fBPCRE2_UCP\fP, e.g. via \f(CR(*UCP)\fP
.TP 26
\fBPCRE2_NEVER_UTF\fP
.ad l
Lock out \fBPCRE2_UTF\fP, e.g. via \f(CR(*UTF)\fP
.TP 26
\fBPCRE2_NO_AUTO_CAPTURE\fP
.ad l
Disable numbered capturing paren\-
theses (named ones available)
.TP 26
\fBPCRE2_NO_AUTO_POSSESS\fP
.ad l
Disable auto\-possessification
.TP 26
\fBPCRE2_NO_DOTSTAR_ANCHOR\fP
.ad l
Disable automatic anchoring for \f(CR.*\fP
.TP 26
\fBPCRE2_NO_START_OPTIMIZE\fP
.ad l
Disable match\-time start optimizations
.TP 26
\fBPCRE2_NO_UTF_CHECK\fP
.ad l
Do not check the pattern for UTF validity
(only relevant if \fBPCRE2_UTF\fP is set)
.TP 26
\fBPCRE2_UCP\fP
.ad l
Use Unicode properties for \f(CR\(rsd\fP, \f(CR\(rsw\fP, etc.
.TP 26
\fBPCRE2_UNGREEDY\fP
.ad l
Invert greediness of quantifiers
.TP 26
\fBPCRE2_USE_OFFSET_LIMIT\fP
.ad l
Enable offset limit for unanchored matching
.TP 26
\fBPCRE2_UTF\fP
.ad l
Treat pattern and subjects as UTF strings
.PD
.RE
.PP
.ad l
.sp
PCRE2 must be built with Unicode support (the default) in order to use
\fBPCRE2_UTF\fP, \fBPCRE2_UCP\fP and related options.
.sp
Additional options may be set in the compile context via the
pcre2_set_compile_extra_options()
function.
.sp
If either of \fIerrorptr\fP or \fIerroroffset\fP is \fBNULL\fP, the function returns
\fBNULL\fP immediately. Otherwise, the yield of this function is a pointer to a
private data structure that contains the compiled pattern, or \fBNULL\fP if an error
was detected. In the error case, a text error message can be obtained by
passing the value returned via the \fIerrorptr\fP argument to the
pcre2_get_error_message() function. The offset (in code units) where the
error was encountered is returned via the \fIerroroffset\fP argument.
.sp
If there is no error, the value passed via \fIerrorptr\fP returns the message
"no error" if passed to pcre2_get_error_message(), and the value passed
via \fIerroroffset\fP is zero.
.sp
There is a complete description of the PCRE2 native API, with more detail on
each option, in the
\f(CRpcre2api\fP
page, and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.