'\" t
.\"     Title: pcre2_substring_nametable_scan
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 06 February 2019
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SUBSTRING_NAMETABLE_SCAN" "3" "06 February 2019" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_substring_nametable_scan \- find table entries for given string name
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint\fP pcre2_substring_nametable_scan(\fBconst\fP \fBpcre2_code\fP *\fIcode\fP,
                                   \fBPCRE2_SPTR\fP \fIstringname\fP,
                                   \fBPCRE2_SPTR\fP *\fIfirstptr\fP,
                                   \fBPCRE2_SPTR\fP *\fIlastptr\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This convenience function finds, for a compiled pattern, the first and last
entries for a given name in the table that translates capture group names into
numbers.
.sp
.RS 4
.PD 0
.TP 11
\fIcode\fP
.ad l
Compiled regular expression
.TP 11
\fIstringname\fP
.ad l
Name whose entries required
.TP 11
\fIfirstptr\fP
.ad l
Where to return a pointer to the first entry
.TP 11
\fIlastptr\fP
.ad l
Where to return a pointer to the last entry
.PD
.RE
.PP
.ad l
.sp
When the name is found in the table, if \fIfirstptr\fP is \fBNULL\fP, the function
returns a group number, but if there is more than one matching entry, it is not
defined which one. Otherwise, when both \fIfirstptr\fP and \fIlastptr\fP have been
set, the yield of
the function is the length of each entry in code units. If the name is not
found, \fBPCRE2_ERROR_NOSUBSTRING\fP is returned.
.sp
There is a complete description of the PCRE2 native API, including the format of
the table entries, in the
\f(CRpcre2api\fP
page, and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.