'\" t
.\"     Title: pcre2syntax
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 14 October 2025
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2SYNTAX" "3" "14 October 2025" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2syntax \- PCRE2 syntax quick reference
.SH "PCRE2 REGULAR EXPRESSION SYNTAX SUMMARY"
.sp
The full syntax and semantics of the regular expression patterns that are
supported by PCRE2 are described in the
\f(CRpcre2pattern\fP
documentation. This document contains a quick\-reference summary of the pattern
syntax followed by the syntax of replacement strings in substitution function.
The full description of the latter is in the
\f(CRpcre2api\fP
documentation.
.SH "QUOTING"
.sp
.RS 4
.PD 0
.TP 8
\f(CR\(rs\fP\fIx\fP
.ad l
where \fIx\fP is non\-alphanumeric, matches a literal \fIx\fP
.TP 8
\f(CR\(rsQ...\(rsE\fP
.ad l
treat enclosed characters as literal
.PD
.RE
.PP
.ad l
.sp
Note that white space inside \f(CR\(rsQ...\(rsE\fP is always treated as literal, even if
\fBPCRE2_EXTENDED\fP is set, causing most other white space to be ignored. Note also
that PCRE2\(cqs handling of \f(CR\(rsQ...\(rsE\fP has some differences from Perl\(cqs. See the
\f(CRpcre2pattern\fP
documentation for details.
.SH "BRACED ITEMS"
.sp
With one exception, wherever brace characters \f(CR{\fP and \f(CR}\fP are required to enclose
data for constructions such as \f(CR\(rsg{2}\fP or \f(CR\(rsk{name}\fP, space and/or horizontal tab
characters that follow \f(CR{\fP or precede \f(CR}\fP are allowed and are ignored. In the case
of quantifiers, they may also appear before or after the comma. The exception
is \f(CR\(rsu{...}\fP which is not Perl\-compatible and is recognized only when
\fBPCRE2_EXTRA_ALT_BSUX\fP is set. This is an ECMAScript compatibility feature, and
follows ECMAScript\(cqs behaviour.
.SH "ESCAPED CHARACTERS"
.sp
This table applies to ASCII and Unicode environments. An unrecognized escape
sequence causes an error.
.sp
.RS 4
.PD 0
.TP 21
\f(CR\(rsa\fP
.ad l
alarm, that is, the BEL character (\f(CR0x07\fP)
.TP 21
\f(CR\(rsc\fP\fIx\fP
.ad l
"control\-\fIx\fP", where \fIx\fP is a non\-control ASCII character
.TP 21
\f(CR\(rse\fP
.ad l
escape (\f(CR0x1B\fP)
.TP 21
\f(CR\(rsf\fP
.ad l
form feed (\f(CR0x0C\fP)
.TP 21
\f(CR\(rsn\fP
.ad l
newline (\f(CR0x0A\fP)
.TP 21
\f(CR\(rsr\fP
.ad l
carriage return (\f(CR0x0D\fP)
.TP 21
\f(CR\(rst\fP
.ad l
tab (\f(CR0x09\fP)
.TP 21
\f(CR\(rs0\fP\fIdd\fP
.ad l
character with octal code 0\fIdd\fP
.TP 21
\f(CR\(rs\fP\fIddd\fP
.ad l
character with octal code \fIddd\fP, or backreference
.TP 21
\f(CR\(rso{\fP\fIddd...\fP\f(CR}\fP
.ad l
character with octal code \fIddd...\fP
.TP 21
\f(CR\(rsN{U+\fP\fIhh...\fP\f(CR}\fP
.ad l
character with Unicode code point \fIhh...\fP (Unicode mode only)
.TP 21
\f(CR\(rsx\fP\fIhh\fP
.ad l
character with hex code \fIhh\fP
.TP 21
\f(CR\(rsx{\fP\fIhh...\fP\f(CR}\fP
.ad l
character with hex code \fIhh...\fP
.PD
.RE
.PP
.ad l
.sp
\f(CR\(rsN{U+\fP\fIhh...\fP\f(CR}\fP is synonymous with \f(CR\(rsx{\fP\fIhh...\fP\f(CR}\fP but is not supported in environments
that use EBCDIC code (mainly IBM mainframes). Note that \f(CR\(rsN\fP not followed by an
opening curly bracket has a different meaning (see below).
.sp
If \fBPCRE2_ALT_BSUX\fP or \fBPCRE2_EXTRA_ALT_BSUX\fP is set ("ALT_BSUX mode"), the
following are also recognized:
.sp
.RS 4
.PD 0
.TP 14
\f(CR\(rsU\fP
.ad l
the character "U"
.TP 14
\f(CR\(rsu\fP\fIhhhh\fP
.ad l
character with hex code \fIhhhh\fP
.TP 14
\f(CR\(rsu{\fP\fIhh...\fP\f(CR}\fP
.ad l
character with hex code \fIhh...\fP but only for EXTRA_ALT_BSUX
.PD
.RE
.PP
.ad l
.sp
When \f(CR\(rsx\fP is not followed by \f(CR{\fP, one or two hexadecimal digits are read,
but in ALT_BSUX mode \f(CR\(rsx\fP must be followed by two hexadecimal digits to be
recognized as a hexadecimal escape; otherwise it matches a literal \f(CRx\fP.
Likewise, if \f(CR\(rsu\fP (in ALT_BSUX mode) is not followed by four hexadecimal digits
or (in EXTRA_ALT_BSUX mode) a sequence of hex digits in curly brackets, it
matches a literal \f(CRu\fP.
.sp
Note that \f(CR\(rs0\fP\fIdd\fP is always an octal code. The treatment of backslash followed by
a non\-zero digit is complicated; for details see the section
Non\-printing characters
in the
\f(CRpcre2pattern\fP
documentation, where details of escape processing in EBCDIC environments are
also given.
.SH "CHARACTER TYPES"
.sp
.RS 4
.PD 0
.TP 11
\f(CR.\fP
.ad l
any character except newline; in dotall mode, any character whatsoever
.TP 11
\f(CR\(rsC\fP
.ad l
one code unit, even in UTF mode (best avoided)
.TP 11
\f(CR\(rsd\fP
.ad l
a decimal digit
.TP 11
\f(CR\(rsD\fP
.ad l
a character that is not a decimal digit
.TP 11
\f(CR\(rsh\fP
.ad l
a horizontal white space character
.TP 11
\f(CR\(rsH\fP
.ad l
a character that is not a horizontal white space character
.TP 11
\f(CR\(rsN\fP
.ad l
a character that is not a newline
.TP 11
\f(CR\(rsp{\fP\fIxx\fP\f(CR}\fP
.ad l
a character with the \fIxx\fP property
.TP 11
\f(CR\(rsP{\fP\fIxx\fP\f(CR}\fP
.ad l
a character without the \fIxx\fP property
.TP 11
\f(CR\(rsR\fP
.ad l
a newline sequence
.TP 11
\f(CR\(rss\fP
.ad l
a white space character
.TP 11
\f(CR\(rsS\fP
.ad l
a character that is not a white space character
.TP 11
\f(CR\(rsv\fP
.ad l
a vertical white space character
.TP 11
\f(CR\(rsV\fP
.ad l
a character that is not a vertical white space character
.TP 11
\f(CR\(rsw\fP
.ad l
a "word" character
.TP 11
\f(CR\(rsW\fP
.ad l
a "non\-word" character
.TP 11
\f(CR\(rsX\fP
.ad l
a Unicode extended grapheme cluster
.PD
.RE
.PP
.ad l
.sp
\f(CR\(rsC\fP is dangerous because it may leave the current matching point in the middle
of a UTF\-8 or UTF\-16 character. The application can lock out the use of \f(CR\(rsC\fP by
setting the \fBPCRE2_NEVER_BACKSLASH_C\fP option. It is also possible to build PCRE2
with the use of \f(CR\(rsC\fP permanently disabled.
.sp
By default, \f(CR\(rsd\fP, \f(CR\(rss\fP, and \f(CR\(rsw\fP match only ASCII characters, even in UTF\-8 mode
or in the 16\-bit and 32\-bit libraries. However, if locale\-specific matching is
happening, \f(CR\(rss\fP and \f(CR\(rsw\fP may also match characters with code points in the range
128\(em255. If the \fBPCRE2_UCP\fP option is set, the behaviour of these escape
sequences is changed to use Unicode properties and they match many more
characters, but there are some option settings that can restrict individual
sequences to matching only ASCII characters.
.sp
Property descriptions in \f(CR\(rsp\fP and \f(CR\(rsP\fP are matched caselessly; hyphens,
underscores, and ASCII white space characters are ignored, in accordance with
Unicode\(cqs "loose matching" rules. For example, \f(CR\(rsp{Bidi_Class=al}\fP is the same
as \f(CR\(rsp{ bidi class = AL }\fP.
.SH "GENERAL CATEGORY PROPERTIES FOR \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
.RS 4
.PD 0
.TP 7
\f(CRC\fP
.ad l
Other
.TP 7
\f(CRCc\fP
.ad l
Control
.TP 7
\f(CRCf\fP
.ad l
Format
.TP 7
\f(CRCn\fP
.ad l
Unassigned
.TP 7
\f(CRCo\fP
.ad l
Private use
.TP 7
\f(CRCs\fP
.ad l
Surrogate
.TP 7
\f(CRL\fP
.ad l
Letter
.TP 7
\f(CRLc\fP
.ad l
Cased letter, the union of \f(CRLl\fP, \f(CRLu\fP, and \f(CRLt\fP
.TP 7
\f(CRL&\fP
.ad l
Synonym of \f(CRLc\fP
.TP 7
\f(CRLl\fP
.ad l
Lower case letter
.TP 7
\f(CRLm\fP
.ad l
Modifier letter
.TP 7
\f(CRLo\fP
.ad l
Other letter
.TP 7
\f(CRLt\fP
.ad l
Title case letter
.TP 7
\f(CRLu\fP
.ad l
Upper case letter
.TP 7
\f(CRM\fP
.ad l
Mark
.TP 7
\f(CRMc\fP
.ad l
Spacing mark
.TP 7
\f(CRMe\fP
.ad l
Enclosing mark
.TP 7
\f(CRMn\fP
.ad l
Non\-spacing mark
.TP 7
\f(CRN\fP
.ad l
Number
.TP 7
\f(CRNd\fP
.ad l
Decimal number
.TP 7
\f(CRNl\fP
.ad l
Letter number
.TP 7
\f(CRNo\fP
.ad l
Other number
.TP 7
\f(CRP\fP
.ad l
Punctuation
.TP 7
\f(CRPc\fP
.ad l
Connector punctuation
.TP 7
\f(CRPd\fP
.ad l
Dash punctuation
.TP 7
\f(CRPe\fP
.ad l
Close punctuation
.TP 7
\f(CRPf\fP
.ad l
Final punctuation
.TP 7
\f(CRPi\fP
.ad l
Initial punctuation
.TP 7
\f(CRPo\fP
.ad l
Other punctuation
.TP 7
\f(CRPs\fP
.ad l
Open punctuation
.TP 7
\f(CRS\fP
.ad l
Symbol
.TP 7
\f(CRSc\fP
.ad l
Currency symbol
.TP 7
\f(CRSk\fP
.ad l
Modifier symbol
.TP 7
\f(CRSm\fP
.ad l
Mathematical symbol
.TP 7
\f(CRSo\fP
.ad l
Other symbol
.TP 7
\f(CRZ\fP
.ad l
Separator
.TP 7
\f(CRZl\fP
.ad l
Line separator
.TP 7
\f(CRZp\fP
.ad l
Paragraph separator
.TP 7
\f(CRZs\fP
.ad l
Space separator
.PD
.RE
.PP
.ad l
.sp
From release 10.45, when caseless matching is set, \f(CRLl\fP, \f(CRLu\fP, and
\f(CRLt\fP are all equivalent to \f(CRLc\fP.
.SH "PCRE2 SPECIAL CATEGORY PROPERTIES FOR \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
.RS 4
.PD 0
.TP 7
\f(CRXan\fP
.ad l
Alphanumeric: union of properties \f(CRL\fP and \f(CRN\fP
.TP 7
\f(CRXps\fP
.ad l
POSIX space: property \f(CRZ\fP or tab, NL, VT, FF, CR
.TP 7
\f(CRXsp\fP
.ad l
Perl space: property \f(CRZ\fP or tab, NL, VT, FF, CR
.TP 7
\f(CRXuc\fP
.ad l
Universally\-named character: one that can be represented by a
Universal Character Name
.TP 7
\f(CRXwd\fP
.ad l
Perl word: property \f(CRXan\fP or underscore
.PD
.RE
.PP
.ad l
.sp
Perl and POSIX space are now the same. Perl added VT to its space character set
at release 5.18.
.SH "BINARY PROPERTIES FOR \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
Unicode defines a number of binary properties, that is, properties whose only
values are true or false. You can obtain a list of those that are recognized by
\f(CR\(rsp\fP and \f(CR\(rsP\fP, along with their abbreviations, by running this command:
.sp
.ss \n[.ss]
.nf
.fam C
pcre2test \-LP
.fam
.fi
.ss \n[.ss] 0
.SH "SCRIPT MATCHING WITH \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
Many script names and their 4\-letter abbreviations are recognized in
\f(CR\(rsp{sc:...}\fP or \f(CR\(rsp{scx:...}\fP items, or on their own with \f(CR\(rsp\fP (and also \f(CR\(rsP\fP of
course). You can obtain a list of these scripts by running this command:
.sp
.ss \n[.ss]
.nf
.fam C
pcre2test \-LS
.fam
.fi
.ss \n[.ss] 0
.SH "THE \f(CRBidi_Class\fP PROPERTY FOR \f(CR\(rsp\fP AND \f(CR\(rsP\fP"
.sp
.RS 4
.PD 0
.TP 21
\f(CR\(rsp{Bidi_Class:\fP\fIclass\fP\f(CR}\fP
.ad l
Matches a character with the given class
.TP 21
\f(CR\(rsp{BC:\fP\fIclass\fP\f(CR}\fP
.ad l
Matches a character with the given class
.PD
.RE
.PP
.ad l
.sp
The recognized classes are:
.sp
.RS 4
.PD 0
.TP 7
\f(CRAL\fP
.ad l
Arabic letter
.TP 7
\f(CRAN\fP
.ad l
Arabic number
.TP 7
\f(CRB\fP
.ad l
Paragraph separator
.TP 7
\f(CRBN\fP
.ad l
Boundary neutral
.TP 7
\f(CRCS\fP
.ad l
Common separator
.TP 7
\f(CREN\fP
.ad l
European number
.TP 7
\f(CRES\fP
.ad l
European separator
.TP 7
\f(CRET\fP
.ad l
European terminator
.TP 7
\f(CRFSI\fP
.ad l
First strong isolate
.TP 7
\f(CRL\fP
.ad l
Left\-to\-right
.TP 7
\f(CRLRE\fP
.ad l
Left\-to\-right embedding
.TP 7
\f(CRLRI\fP
.ad l
Left\-to\-right isolate
.TP 7
\f(CRLRO\fP
.ad l
Left\-to\-right override
.TP 7
\f(CRNSM\fP
.ad l
Non\-spacing mark
.TP 7
\f(CRON\fP
.ad l
Other neutral
.TP 7
\f(CRPDF\fP
.ad l
Pop directional format
.TP 7
\f(CRPDI\fP
.ad l
Pop directional isolate
.TP 7
\f(CRR\fP
.ad l
Right\-to\-left
.TP 7
\f(CRRLE\fP
.ad l
Right\-to\-left embedding
.TP 7
\f(CRRLI\fP
.ad l
Right\-to\-left isolate
.TP 7
\f(CRRLO\fP
.ad l
Right\-to\-left override
.TP 7
\f(CRS\fP
.ad l
Segment separator
.TP 7
\f(CRWS\fP
.ad l
White space
.PD
.RE
.PP
.ad l
.SH "CHARACTER CLASSES"
.sp
.RS 4
.PD 0
.TP 11
\f(CR[...]\fP
.ad l
Positive character class
.TP 11
\f(CR[^...]\fP
.ad l
Negative character class
.TP 11
\f(CR[x\-y]\fP
.ad l
Range (can be used for hexadecimal characters)
.TP 11
\f(CR[[:\fP\fIxxx\fP\f(CR:]]\fP
.ad l
Positive POSIX named set
.TP 11
\f(CR[[:^\fP\fIxxx\fP\f(CR:]]\fP
.ad l
Negative POSIX named set
.PD
.RE
.PP
.ad l
.sp
The recognized POSIX named sets are:
.sp
.RS 4
.PD 0
.TP 7
\f(CRalnum\fP
.ad l
Alphanumeric
.TP 7
\f(CRalpha\fP
.ad l
Alphabetic
.TP 7
\f(CRascii\fP
.ad l
0\(em127
.TP 7
\f(CRblank\fP
.ad l
Space or tab
.TP 7
\f(CRcntrl\fP
.ad l
Control character
.TP 7
\f(CRdigit\fP
.ad l
Decimal digit
.TP 7
\f(CRgraph\fP
.ad l
Printing, excluding space
.TP 7
\f(CRlower\fP
.ad l
Lower case letter
.TP 7
\f(CRprint\fP
.ad l
Printing, including space
.TP 7
\f(CRpunct\fP
.ad l
Printing, excluding alphanumeric
.TP 7
\f(CRspace\fP
.ad l
White space
.TP 7
\f(CRupper\fP
.ad l
Upper case letter
.TP 7
\f(CRword\fP
.ad l
Same as \f(CR\(rsw\fP
.TP 7
\f(CRxdigit\fP
.ad l
Hexadecimal digit
.PD
.RE
.PP
.ad l
.sp
In PCRE2, POSIX character set names recognize only ASCII characters by default,
but some of them use Unicode properties if \fBPCRE2_UCP\fP is set. You can use
\f(CR\(rsQ...\(rsE\fP inside a character class.
.sp
When \fBPCRE2_ALT_EXTENDED_CLASS\fP is set, UTS#18 extended character classes may be
used, allowing nested character classes, combined using set operators.
.sp
.RS 4
.PD 0
.TP 18
\f(CR[x&&[^y]]\fP
.ad l
UTS#18 extended character class
.TP 18
\f(CRx||y\fP
.ad l
Set union (OR)
.TP 18
\f(CRx&&y\fP
.ad l
Set intersection (AND)
.TP 18
\f(CRx\-\-y\fP
.ad l
Set difference (AND NOT)
.TP 18
\f(CRx~~y\fP
.ad l
Set symmetric difference (XOR)
.PD
.RE
.PP
.ad l
.SH "PERL EXTENDED CHARACTER CLASSES"
.sp
.RS 4
.PD 0
.TP 25
\f(CR(?[...])\fP
.ad l
Perl extended character class
.TP 25
\f(CR(?[\(rsp{Thai} & \(rsp{Nd}])\fP
.ad l
Operators; white space ignored
.TP 25
\f(CR(?[(\fP\fIX\fP\f(CR \- \fP\fIY\fP\f(CR) & \fP\fIZ\fP\f(CR])\fP
.ad l
Parentheses for grouping
.TP 25
\f(CR(?[ [^3] & \(rsp{Nd} ])\fP
.ad l
\f(CR[ ... ]\fP is a nested ordinary class
.TP 25
\f(CR(?[ [:alpha:] \- [z] ])\fP
.ad l
POSIX set is allowed outside \f(CR[ ... ]\fP but character literal must be enclosed
.TP 25
\f(CR(?[ \(rsd \- [3] ])\fP
.ad l
Backslash\-escaped set is allowed outside \f(CR[ ... ]\fP
.TP 25
\f(CR(?[ !\(rsn & [:ascii:] ])\fP
.ad l
Backslash\-escaped character is allowed outside
\f(CR[ ... ]\fP; all other characters or ranges must be enclosed in \f(CR[ ... ]\fP
.TP 25
\f(CRx|y\fP, \f(CRx+y\fP
.ad l
Set union (OR)
.TP 25
\f(CRx&y\fP
.ad l
Set intersection (AND)
.TP 25
\f(CRx\-y\fP
.ad l
Set difference (AND NOT)
.TP 25
\f(CRx^y\fP
.ad l
Set symmetric difference (XOR)
.TP 25
\f(CR!x\fP
.ad l
Set complement (NOT)
.PD
.RE
.PP
.ad l
.sp
Inside a Perl extended character class, \f(CR[...]\fP switches mode to be interpreted
as an ordinary character class. Outside of a nested \f(CR[...]\fP, the only items
permitted are backslash\-escapes, POSIX sets, operators, and parentheses. Inside
a nested ordinary class, \f(CR^\fP has its usual meaning (inverts the class when used
as the first character); outside of a nested class, \f(CR^\fP is the XOR operator.
.SH "QUANTIFIERS"
.sp
.RS 4
.PD 0
.TP 7
\f(CR?\fP
.ad l
0 or 1, greedy
.TP 7
\f(CR?+\fP
.ad l
0 or 1, possessive
.TP 7
\f(CR??\fP
.ad l
0 or 1, lazy
.TP 7
\f(CR*\fP
.ad l
0 or more, greedy
.TP 7
\f(CR*+\fP
.ad l
0 or more, possessive
.TP 7
\f(CR*?\fP
.ad l
0 or more, lazy
.TP 7
\f(CR+\fP
.ad l
1 or more, greedy
.TP 7
\f(CR++\fP
.ad l
1 or more, possessive
.TP 7
\f(CR+?\fP
.ad l
1 or more, lazy
.TP 7
\f(CR{\fP\fIn\fP\f(CR}\fP
.ad l
Exactly \fIn\fP
.TP 7
\f(CR{\fP\fIn\fP\f(CR,\fP\fIm\fP\f(CR}\fP
.ad l
At least \fIn\fP, no more than \fIm\fP, greedy
.TP 7
\f(CR{\fP\fIn\fP\f(CR,\fP\fIm\fP\f(CR}+\fP
.ad l
At least \fIn\fP, no more than \fIm\fP, possessive
.TP 7
\f(CR{\fP\fIn\fP\f(CR,\fP\fIm\fP\f(CR}?\fP
.ad l
At least \fIn\fP, no more than \fIm\fP, lazy
.TP 7
\f(CR{\fP\fIn\fP\f(CR,}\fP
.ad l
\fIn\fP or more, greedy
.TP 7
\f(CR{\fP\fIn\fP\f(CR,}+\fP
.ad l
\fIn\fP or more, possessive
.TP 7
\f(CR{\fP\fIn\fP\f(CR,}?\fP
.ad l
\fIn\fP or more, lazy
.TP 7
\f(CR{,\fP\fIm\fP\f(CR}\fP
.ad l
Zero up to \fIm\fP, greedy
.TP 7
\f(CR{,\fP\fIm\fP\f(CR}+\fP
.ad l
Zero up to \fIm\fP, possessive
.TP 7
\f(CR{,\fP\fIm\fP\f(CR}?\fP
.ad l
Zero up to \fIm\fP, lazy
.PD
.RE
.PP
.ad l
.SH "ANCHORS AND SIMPLE ASSERTIONS"
.sp
.RS 4
.PD 0
.TP 7
\f(CR\(rsb\fP
.ad l
Word boundary
.TP 7
\f(CR\(rsB\fP
.ad l
Not a word boundary
.TP 7
\f(CR^\fP
.ad l
Start of subject; also after an internal newline in multiline mode
(after any newline if \fBPCRE2_ALT_CIRCUMFLEX\fP is set)
.TP 7
\f(CR\(rsA\fP
.ad l
Start of subject
.TP 7
\f(CR$\fP
.ad l
End of subject; also before newline at end of subject and before
an internal newline in multiline mode
.TP 7
\f(CR\(rsZ\fP
.ad l
End of subject; also before newline at end of subject
.TP 7
\f(CR\(rsz\fP
.ad l
End of subject
.TP 7
\f(CR\(rsG\fP
.ad l
First matching position in subject
.PD
.RE
.PP
.ad l
.SH "REPORTED MATCH POINT SETTING"
.sp
.RS 4
.PD 0
.TP 7
\f(CR\(rsK\fP
.ad l
Set reported start of match
.PD
.RE
.PP
.ad l
.sp
From release 10.38, \f(CR\(rsK\fP is not permitted by default in lookaround assertions,
for compatibility with Perl. However, if the \fBPCRE2_EXTRA_ALLOW_LOOKAROUND_BSK\fP
option is set, the previous behaviour is re\-enabled. When this option is set,
\f(CR\(rsK\fP is honoured in positive assertions, but ignored in negative ones.
.SH "ALTERNATION"
.sp
.RS 4
.PD 0
.TP 18
\fIexpr\fP\f(CR|\fP\fIexpr\fP\f(CR|\fP\fIexpr\fP\f(CR...\fP
.ad l
Alternative expressions
.PD
.RE
.PP
.ad l
.SH "CAPTURING"
.sp
.RS 4
.PD 0
.TP 20
\f(CR(...)\fP
.ad l
Capture group
.TP 20
\f(CR(?<\fP\fIname\fP\f(CR>...)\fP
.ad l
Named capture group (Perl)
.TP 20
\f(CR(?\*(Aq\fP\fIname\fP\f(CR\*(Aq...)\fP
.ad l
Named capture group (Perl)
.TP 20
\f(CR(?P<\fP\fIname\fP\f(CR>...)\fP
.ad l
Named capture group (Python)
.TP 20
\f(CR(?:...)\fP
.ad l
Non\-capture group
.TP 20
\f(CR(?|...)\fP
.ad l
Non\-capture group; reset group numbers for capture groups
in each alternative
.PD
.RE
.PP
.ad l
.sp
In non\-UTF modes, names may contain underscores and ASCII letters and digits;
in UTF modes, any Unicode letters and Unicode decimal digits are permitted. In
both cases, a name must not start with a digit.
.SH "ATOMIC GROUPS"
.sp
.RS 4
.PD 0
.TP 14
\f(CR(?>...)\fP
.ad l
Atomic non\-capture group
.TP 14
\f(CR(*atomic:...)\fP
.ad l
Atomic non\-capture group
.PD
.RE
.PP
.ad l
.SH "COMMENT"
.sp
.RS 4
.PD 0
.TP 8
\f(CR(?#...)\fP
.ad l
Comment (not nestable)
.PD
.RE
.PP
.ad l
.SH "OPTION SETTING"
.sp
Changes of these options within a group are automatically cancelled at the end
of the group.
.sp
.RS 4
.PD 0
.TP 8
\f(CR(?a)\fP
.ad l
All ASCII options
.TP 8
\f(CR(?aD)\fP
.ad l
Restrict \f(CR\(rsd\fP to ASCII in UCP mode
.TP 8
\f(CR(?aS)\fP
.ad l
Restrict \f(CR\(rss\fP to ASCII in UCP mode
.TP 8
\f(CR(?aW)\fP
.ad l
Restrict \f(CR\(rsw\fP to ASCII in UCP mode
.TP 8
\f(CR(?aP)\fP
.ad l
Restrict all POSIX classes to ASCII in UCP mode
.TP 8
\f(CR(?aT)\fP
.ad l
Restrict POSIX digit classes to ASCII in UCP mode
.TP 8
\f(CR(?i)\fP
.ad l
Caseless
.TP 8
\f(CR(?J)\fP
.ad l
Allow duplicate named groups
.TP 8
\f(CR(?m)\fP
.ad l
Multiline
.TP 8
\f(CR(?n)\fP
.ad l
No auto capture
.TP 8
\f(CR(?r)\fP
.ad l
Restrict caseless to either ASCII or non\-ASCII
.TP 8
\f(CR(?s)\fP
.ad l
Single line (dotall)
.TP 8
\f(CR(?U)\fP
.ad l
Default ungreedy (lazy)
.TP 8
\f(CR(?x)\fP
.ad l
Ignore white space except in classes or \f(CR\(rsQ...\(rsE\fP
.TP 8
\f(CR(?xx)\fP
.ad l
As \f(CR(?x)\fP, but also ignore space and tab in classes
.TP 8
\f(CR(?\-...)\fP
.ad l
Unset the given option(s)
.TP 8
\f(CR(?^)\fP
.ad l
Unset \f(CRimnrsx\fP options
.PD
.RE
.PP
.ad l
.sp
\f(CR(?aP)\fP implies \f(CR(?aT)\fP as well, though this has no additional effect. However, it
means that \f(CR(?\-aP)\fP also implies \f(CR(?\-aT)\fP and disables all ASCII restrictions for
POSIX classes.
.sp
Unsetting \f(CRx\fP or \f(CRxx\fP unsets both. Several options may be set at once, and a
mixture of setting and unsetting such as \f(CR(?i\-x)\fP is allowed, but there may be
only one hyphen. Setting (but no unsetting) is allowed after \f(CR(?^\fP, for example
\f(CR(?^in)\fP. An option setting may appear at the start of a non\-capture group, for
example \f(CR(?i:...)\fP.
.sp
The following are recognized only at the very start of a pattern or after one
of the newline or \f(CR\(rsR\fP sequences or options with similar syntax. More than one
of them may appear. For the first three, d is a decimal number.
.sp
.RS 4
.PD 0
.TP 21
\f(CR(*LIMIT_DEPTH=\fP\fId\fP\f(CR)\fP
.ad l
Set the backtracking limit to \fId\fP
.TP 21
\f(CR(*LIMIT_HEAP=\fP\fId\fP\f(CR)\fP
.ad l
Set the heap size limit to \fId\fP * 1024 bytes
.TP 21
\f(CR(*LIMIT_MATCH=\fP\fId\fP\f(CR)\fP
.ad l
Set the match limit to \fId\fP
.TP 21
\f(CR(*CASELESS_RESTRICT)\fP
.ad l
Set \fBPCRE2_EXTRA_CASELESS_RESTRICT\fP when matching
.TP 21
\f(CR(*NOTEMPTY)\fP
.ad l
Set \fBPCRE2_NOTEMPTY\fP when matching
.TP 21
\f(CR(*NOTEMPTY_ATSTART)\fP
.ad l
Set \fBPCRE2_NOTEMPTY_ATSTART\fP when matching
.TP 21
\f(CR(*NO_AUTO_POSSESS)\fP
.ad l
No auto\-possessification
(\fBPCRE2_NO_AUTO_POSSESS\fP)
.TP 21
\f(CR(*NO_DOTSTAR_ANCHOR)\fP
.ad l
No \f(CR.*\fP anchoring
(\fBPCRE2_NO_DOTSTAR_ANCHOR\fP)
.TP 21
\f(CR(*NO_JIT)\fP
.ad l
Disable JIT optimization
.TP 21
\f(CR(*NO_START_OPT)\fP
.ad l
No start\-match optimization
(\fBPCRE2_NO_START_OPTIMIZE\fP)
.TP 21
\f(CR(*TURKISH_CASING)\fP
.ad l
Set \fBPCRE2_EXTRA_TURKISH_CASING\fP when matching
.TP 21
\f(CR(*UTF)\fP
.ad l
Set appropriate UTF mode for the library in use
.TP 21
\f(CR(*UCP)\fP
.ad l
Set \fBPCRE2_UCP\fP (use Unicode properties for \f(CR\(rsd\fP, etc.)
.PD
.RE
.PP
.ad l
.sp
Note that \f(CRLIMIT_DEPTH\fP, \f(CRLIMIT_HEAP\fP, and \f(CRLIMIT_MATCH\fP can only reduce the value of
the limits set by the caller of pcre2_match() or pcre2_dfa_match(),
not increase them. \f(CRLIMIT_RECURSION\fP is an obsolete synonym for \f(CRLIMIT_DEPTH\fP. The
application can lock out the use of \f(CR(*UTF)\fP and \f(CR(*UCP)\fP by setting the
\fBPCRE2_NEVER_UTF\fP or \fBPCRE2_NEVER_UCP\fP options, respectively, at compile time.
.SH "NEWLINE CONVENTION"
.sp
These are recognized only at the very start of the pattern or after option
settings with a similar syntax.
.sp
.RS 4
.PD 0
.TP 11
\f(CR(*CR)\fP
.ad l
Carriage return only
.TP 11
\f(CR(*LF)\fP
.ad l
Linefeed only
.TP 11
\f(CR(*CRLF)\fP
.ad l
Carriage return followed by linefeed
.TP 11
\f(CR(*ANYCRLF)\fP
.ad l
All three of the above
.TP 11
\f(CR(*ANY)\fP
.ad l
Any Unicode newline sequence
.TP 11
\f(CR(*NUL)\fP
.ad l
The NUL character (binary zero)
.PD
.RE
.PP
.ad l
.SH "WHAT \f(CR\(rsR\fP MATCHES"
.sp
These are recognized only at the very start of the pattern or after option
setting with a similar syntax.
.sp
.RS 4
.PD 0
.TP 15
\f(CR(*BSR_ANYCRLF)\fP
.ad l
CR, LF, or CRLF
.TP 15
\f(CR(*BSR_UNICODE)\fP
.ad l
Any Unicode newline sequence
.PD
.RE
.PP
.ad l
.SH "LOOKAHEAD AND LOOKBEHIND ASSERTIONS"
.sp
.RS 4
.PD 0
.TP 7
\f(CR(?=...)\fP, \f(CR(*pla:...)\fP, \f(CR(*positive_lookahead:...)\fP
.ad l
Positive lookahead
.TP 7
\f(CR(?!...)\fP, \f(CR(*nla:...)\fP, \f(CR(*negative_lookahead:...)\fP
.ad l
Negative lookahead
.TP 7
\f(CR(?<=...)\fP, \f(CR(*plb:...)\fP, \f(CR(*positive_lookbehind:...)\fP
.ad l
Positive lookbehind
.TP 7
\f(CR(?<!...)\fP, \f(CR(*nlb:...)\fP, \f(CR(*negative_lookbehind:...)\fP
.ad l
Negative lookbehind
.PD
.RE
.PP
.ad l
.sp
Each top\-level branch of a lookbehind must have a limit for the number of
characters it matches. If any branch can match a variable number of characters,
the maximum for each branch is limited to a value set by the caller of
pcre2_compile() or defaulted. The default is set when PCRE2 is built
(ultimate default 255). If every branch matches a fixed number of characters,
the limit for each branch is 65535 characters.
.SH "NON\-ATOMIC LOOKAROUND ASSERTIONS"
.sp
These assertions are specific to PCRE2 and are not Perl\-compatible.
.sp
.RS 4
.PD 0
.TP 7
\f(CR(?*...)\fP, \f(CR(*napla:...)\fP, \f(CR(*non_atomic_positive_lookahead:...)\fP
.ad l
Synonyms for non\-atomic
positive lookahead
.TP 7
\f(CR(?<*...)\fP, \f(CR(*naplb:...)\fP, \f(CR(*non_atomic_positive_lookbehind:...)\fP
.ad l
Synonyms for non\-atomic
positive lookbehind
.PD
.RE
.PP
.ad l
.SH "SUBSTRING SCAN ASSERTION"
.sp
This feature is not Perl\-compatible.
.sp
.RS 4
.PD 0
.TP 7
\f(CR(*scan_substring:(\fP\fIgrouplist\fP\f(CR)...)\fP
.ad l
Scan captured substring
.TP 7
\f(CR(*scs:(\fP\fIgrouplist\fP\f(CR)...)\fP
.ad l
Scan captured substring
.PD
.RE
.PP
.ad l
.sp
The comma\-separated list \fIgrouplist\fP may identify groups in any of the
following ways:
.sp
.RS 4
.PD 0
.TP 13
\fIn\fP
.ad l
Absolute reference
.TP 13
\f(CR+\fP\fIn\fP
.ad l
Relative reference
.TP 13
\f(CR\-\fP\fIn\fP
.ad l
Relative reference
.TP 13
\f(CR<\fP\fIname\fP\f(CR>\fP
.ad l
Name
.TP 13
\f(CR\*(Aq\fP\fIname\fP\f(CR\*(Aq\fP
.ad l
Name
.PD
.RE
.PP
.ad l
.SH "SCRIPT RUNS"
.sp
.RS 4
.PD 0
.TP 7
\f(CR(*script_run:...)\fP, \f(CR(*sr:...)\fP
.ad l
Script run; can be
backtracked into
.TP 7
\f(CR(*atomic_script_run:...)\fP, \f(CR(*asr:...)\fP
.ad l
Atomic script run
.PD
.RE
.PP
.ad l
.SH "BACKREFERENCES"
.sp
.RS 4
.PD 0
.TP 15
\f(CR\(rs\fP\fIn\fP
.ad l
Reference by number (can be ambiguous)
.TP 15
\f(CR\(rsg\fP\fIn\fP
.ad l
Reference by number
.TP 15
\f(CR\(rsg{\fP\fIn\fP\f(CR}\fP
.ad l
Reference by number
.TP 15
\f(CR\(rsg+\fP\fIn\fP
.ad l
Relative reference by number (PCRE2 extension)
.TP 15
\f(CR\(rsg\-\fP\fIn\fP
.ad l
Relative reference by number
.TP 15
\f(CR\(rsg{+\fP\fIn\fP\f(CR}\fP
.ad l
Relative reference by number (PCRE2 extension)
.TP 15
\f(CR\(rsg{\-\fP\fIn\fP\f(CR}\fP
.ad l
Relative reference by number
.TP 15
\f(CR\(rsk<\fP\fIname\fP\f(CR>\fP
.ad l
Reference by name (Perl)
.TP 15
\f(CR\(rsk\*(Aq\fP\fIname\fP\f(CR\*(Aq\fP
.ad l
Reference by name (Perl)
.TP 15
\f(CR\(rsg{\fP\fIname\fP\f(CR}\fP
.ad l
Reference by name (Perl)
.TP 15
\f(CR\(rsk{\fP\fIname\fP\f(CR}\fP
.ad l
Reference by name (.NET)
.TP 15
\f(CR(?P=\fP\fIname\fP\f(CR)\fP
.ad l
Reference by name (Python)
.PD
.RE
.PP
.ad l
.SH "SUBROUTINE REFERENCES (POSSIBLY RECURSIVE)"
.sp
.RS 4
.PD 0
.TP 15
\f(CR(?R)\fP
.ad l
Recurse whole pattern
.TP 15
\f(CR(?\fP\fIn\fP\f(CR)\fP
.ad l
Call subroutine by absolute number
.TP 15
\f(CR(?+\fP\fIn\fP\f(CR)\fP
.ad l
Call subroutine by relative number
.TP 15
\f(CR(?\-\fP\fIn\fP\f(CR)\fP
.ad l
Call subroutine by relative number
.TP 15
\f(CR(?&\fP\fIname\fP\f(CR)\fP
.ad l
Call subroutine by name (Perl)
.TP 15
\f(CR(?P>\fP\fIname\fP\f(CR)\fP
.ad l
Call subroutine by name (Python)
.TP 15
\f(CR\(rsg<\fP\fIname\fP\f(CR>\fP
.ad l
Call subroutine by name (Oniguruma)
.TP 15
\f(CR\(rsg\*(Aq\fP\fIname\fP\f(CR\*(Aq\fP
.ad l
Call subroutine by name (Oniguruma)
.TP 15
\f(CR\(rsg<\fP\fIn\fP\f(CR>\fP
.ad l
Call subroutine by absolute number (Oniguruma)
.TP 15
\f(CR\(rsg\*(Aq\fP\fIn\fP\f(CR\*(Aq\fP
.ad l
Call subroutine by absolute number (Oniguruma)
.TP 15
\f(CR\(rsg<+\fP\fIn\fP\f(CR>\fP
.ad l
Call subroutine by relative number (PCRE2 extension)
.TP 15
\f(CR\(rsg\*(Aq+\fP\fIn\fP\f(CR\*(Aq\fP
.ad l
Call subroutine by relative number (PCRE2 extension)
.TP 15
\f(CR\(rsg<\-\fP\fIn\fP\f(CR>\fP
.ad l
Call subroutine by relative number (PCRE2 extension)
.TP 15
\f(CR\(rsg\*(Aq\-\fP\fIn\fP\f(CR\*(Aq\fP
.ad l
Call subroutine by relative number (PCRE2 extension)
.PD
.RE
.PP
.ad l
.sp
The variants using parentheses \f(CR(?...)\fP may also specify a list of capture groups
to return, which shall be retained in the calling subexpression if set during
the recursion (this feature is not supported by Perl).
.sp
.RS 4
.PD 0
.TP 7
\f(CR(?R(\fP\fIgrouplist\fP\f(CR))\fP
.ad l
Recurse whole pattern, returning capture groups
(PCRE2 extension)
.TP 7
\f(CR(?\fP\fIn\fP\f(CR(\fP\fIgrouplist\fP\f(CR))\fP, \f(CR(?+\fP\fIn\fP\f(CR(\fP\fIgrouplist\fP\f(CR))\fP, \f(CR(?\-\fP\fIn\fP\f(CR(\fP\fIgrouplist\fP\f(CR))\fP, \f(CR(?&\fP\fIname\fP\f(CR(\fP\fIgrouplist\fP\f(CR))\fP, \f(CR(?P>\fP\fIname\fP\f(CR(\fP\fIgrouplist\fP\f(CR))\fP
.ad l
Call subroutine, returning capture groups
(PCRE2 extension)
.PD
.RE
.PP
.ad l
.sp
The comma\-separated list \fIgrouplist\fP uses the same syntax as
\f(CR(*scan_substring:(\fP\fIgrouplist\fP\f(CR)...)\fP, and may identify groups in any of the
following ways:
.sp
.RS 4
.PD 0
.TP 13
\fIn\fP
.ad l
Absolute reference
.TP 13
\f(CR+\fP\fIn\fP
.ad l
Relative reference
.TP 13
\f(CR\-\fP\fIn\fP
.ad l
Relative reference
.TP 13
\f(CR<\fP\fIname\fP\f(CR>\fP
.ad l
Name
.TP 13
\f(CR\*(Aq\fP\fIname\fP\f(CR\*(Aq\fP
.ad l
Name
.PD
.RE
.PP
.ad l
.SH "CONDITIONAL PATTERNS"
.sp
.RS 4
.PD 0
.TP 7
\f(CR(?(\fP\fIcondition\fP\f(CR)\fP\fIyes\-pattern\fP\f(CR)\fP
.ad l
Conditional pattern without an alternative
.TP 7
\f(CR(?(\fP\fIcondition\fP\f(CR)\fP\fIyes\-pattern\fP\f(CR|\fP\fIno\-pattern\fP\f(CR)\fP
.ad l
Conditional pattern with an alternative
.PD
.RE
.PP
.ad l
.sp
The forms for the \fIcondition\fP are:
.sp
.RS 4
.PD 0
.TP 24
\f(CR(?(\fP\fIn\fP\f(CR)\fP
.ad l
Absolute reference condition
.TP 24
\f(CR(?(+\fP\fIn\fP\f(CR)\fP
.ad l
Relative reference condition (PCRE2 extension)
.TP 24
\f(CR(?(\-\fP\fIn\fP\f(CR)\fP
.ad l
Relative reference condition (PCRE2 extension)
.TP 24
\f(CR(?(<\fP\fIname\fP\f(CR>)\fP
.ad l
Named reference condition (Perl)
.TP 24
\f(CR(?(\*(Aq\fP\fIname\fP\f(CR\*(Aq)\fP
.ad l
Named reference condition (Perl)
.TP 24
\f(CR(?(\fP\fIname\fP\f(CR)\fP
.ad l
Named reference condition (PCRE2, deprecated)
.TP 24
\f(CR(?(R)\fP
.ad l
Overall recursion condition
.TP 24
\f(CR(?(R\fP\fIn\fP\f(CR)\fP
.ad l
Specific numbered group recursion condition
.TP 24
\f(CR(?(R&\fP\fIname\fP\f(CR)\fP
.ad l
Specific named group recursion condition
.TP 24
\f(CR(?(DEFINE)\fP
.ad l
Define groups for reference
.TP 24
\f(CR(?(VERSION\fP\fI[\fP\f(CR>\fP\fI]\fP\f(CR=\fP\fIn\fP\fI[\fP\f(CR.\fP\fIm\fP\fI]\fP\f(CR)\fP
.ad l
Test PCRE2 version
.TP 24
\f(CR(?(\fP\fIassert\fP\f(CR)\fP
.ad l
Assertion condition
.PD
.RE
.PP
.ad l
.sp
Note the ambiguity of \f(CR(?(R)\fP and \f(CR(?(R\fP\fIn\fP\f(CR)\fP which might be named reference
conditions or recursion tests. Such a condition is interpreted as a reference
condition if the relevant named group exists.
.sp
The parts within brackets for the VERSION conditional syntax can be ommited.
The fractional part of the version number defaults to 0 in that case.
.SH "BACKTRACKING CONTROL"
.sp
All backtracking control verbs may be in the form \f(CR(*VERB:\fP\fINAME\fP\f(CR)\fP. For \f(CR(*MARK)\fP the
name is mandatory, for the others it is optional. \f(CR(*SKIP)\fP changes its behaviour
if \f(CR:\fP\fINAME\fP is present. The others just set a name for passing back to the caller,
but this is not a name that \f(CR(*SKIP)\fP can see. The following act immediately they
are reached:
.sp
.RS 4
.PD 0
.TP 13
\f(CR(*ACCEPT)\fP
.ad l
Force successful match
.TP 13
\f(CR(*FAIL)\fP
.ad l
Force backtrack; synonym \f(CR(*F)\fP
.TP 13
\f(CR(*MARK:\fP\fINAME\fP\f(CR)\fP
.ad l
Set name to be passed back; synonym \f(CR(*:\fP\fINAME\fP\f(CR)\fP
.PD
.RE
.PP
.ad l
.sp
The following act only when a subsequent match failure causes a backtrack to
reach them. They all force a match failure, but they differ in what happens
afterwards. Those that advance the start\-of\-match point do so only if the
pattern is not anchored.
.sp
.RS 4
.PD 0
.TP 13
\f(CR(*COMMIT)\fP
.ad l
Overall failure, no advance of starting point
.TP 13
\f(CR(*PRUNE)\fP
.ad l
Advance to next starting character
.TP 13
\f(CR(*SKIP)\fP
.ad l
Advance to current matching position
.TP 13
\f(CR(*SKIP:\fP\fINAME\fP\f(CR)\fP
.ad l
Advance to position corresponding to an earlier
\f(CR(*MARK:\fP\fINAME\fP\f(CR)\fP; if not found, the \f(CR(*SKIP)\fP is ignored
.TP 13
\f(CR(*THEN)\fP
.ad l
Local failure, backtrack to next alternation
.PD
.RE
.PP
.ad l
.sp
The effect of one of these verbs in a group called as a subroutine is confined
to the subroutine call.
.SH "CALLOUTS"
.sp
.RS 4
.PD 0
.TP 11
\f(CR(?C)\fP
.ad l
Callout (assumed number 0)
.TP 11
\f(CR(?C\fP\fIn\fP\f(CR)\fP
.ad l
Callout with numerical data \fIn\fP
.TP 11
\f(CR(?C"\fP\fItext\fP\f(CR")\fP
.ad l
Callout with string data
.PD
.RE
.PP
.ad l
.sp
The allowed string delimiters are \f(CR\*(Aq\fP, \f(CR"\fP, \f(CR^\fP,
\f(CR%\fP, \f(CR#\fP, and \f(CR$\fP (which are the same for the start
and the end), and the starting delimiter \f(CR{\fP matched with the ending
delimiter \f(CR}\fP. To encode the ending delimiter within the string, double it.
.SH "REPLACEMENT STRINGS"
.sp
If the \fBPCRE2_SUBSTITUTE_LITERAL\fP option is set, a replacement string for
pcre2_substitute() is not interpreted. Otherwise, by default, the only
special character is the dollar character in one of the following forms:
.sp
.RS 4
.PD 0
.TP 19
\f(CR$$\fP
.ad l
Insert a dollar character
.TP 19
\f(CR$\fP\fIn\fP or \f(CR${\fP\fIn\fP\f(CR}\fP
.ad l
Insert the contents of group \fIn\fP
.TP 19
\f(CR$<\fP\fIname\fP\f(CR>\fP
.ad l
Insert the contents of named group
.TP 19
\f(CR$0\fP or \f(CR$&\fP
.ad l
Insert the entire matched substring
.TP 19
\f(CR$`\fP
.ad l
Insert the substring that precedes the match
.TP 19
\f(CR$\*(Aq\fP
.ad l
Insert the substring that follows the match
.TP 19
\f(CR$_\fP
.ad l
Insert the entire input string
.TP 19
\f(CR$+\fP
.ad l
Insert the highest\-numbered capture group which matched
.TP 19
\f(CR$*MARK\fP or \f(CR${*MARK}\fP
.ad l
Insert a control verb name
.PD
.RE
.PP
.ad l
.sp
For \f(CR${\fP\fIn\fP\f(CR}\fP, \fIn\fP can be a name or a number. If \fBPCRE2_SUBSTITUTE_EXTENDED\fP is set,
there is additional interpretation:
.sp
.RS 4
.ie n \{\
\h'-04' 1.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 1." 4.2
.\}
Backslash is an escape character, and the forms described in "ESCAPED
CHARACTERS" above are recognized. Also:
.sp
.RS 4
.PD 0
.TP 8
\f(CR\(rsQ...\(rsE\fP
.ad l
Suppress interpretation
.TP 8
\f(CR\(rsl\fP
.ad l
Force the next character to lower case
.TP 8
\f(CR\(rsu\fP
.ad l
Force the next character to upper case
.TP 8
\f(CR\(rsL\fP
.ad l
Force subsequent characters to lower case
.TP 8
\f(CR\(rsU\fP
.ad l
Force subsequent characters to upper case
.TP 8
\f(CR\(rsu\(rsL\fP
.ad l
Force next character to upper case, then all lower
.TP 8
\f(CR\(rsl\(rsU\fP
.ad l
Force next character to lower case, then all upper
.TP 8
\f(CR\(rsE\fP
.ad l
End \f(CR\(rsL\fP or \f(CR\(rsU\fP case forcing
.TP 8
\f(CR\(rsb\fP
.ad l
Backspace character (note: as in character class in pattern)
.TP 8
\f(CR\(rsv\fP
.ad l
Vertical tab character (note: not the same as in a pattern)
.PD
.RE
.PP
.ad l
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 2.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 2." 4.2
.\}
The Python form \f(CR\(rsg<\fP\fIn\fP\f(CR>\fP, where the angle brackets are part of the syntax and
\fIn\fP is either a group name or a number, is recognized as an alternative way
of inserting the contents of a group, for example \f(CR\(rsg<3>\fP.
.RE
.sp
.RS 4
.ie n \{\
\h'-04' 3.\h'+01'\c
.\}
.el \{\
.  sp -1
.  IP " 3." 4.2
.\}
Capture substitution supports the following additional forms:
.sp
.RS 4
.PD 0
.TP 22
\f(CR${\fP\fIn\fP\f(CR:\-\fP\fIstring\fP\f(CR}\fP
.ad l
Default for unset group
.TP 22
\f(CR${\fP\fIn\fP\f(CR:+\fP\fIstring1\fP\f(CR:\fP\fIstring2\fP\f(CR}\fP
.ad l
Values for set/unset group
.PD
.RE
.PP
.ad l
.sp
The substitution strings themselves are expanded. Backslash can be used to
escape colons and closing curly brackets.
.RE
.SH "SEE ALSO"
.sp
\f(CRpcre2pattern\fP, \f(CRpcre2api\fP, \f(CRpcre2callout\fP,
\f(CRpcre2matching\fP, \f(CRpcre2\fP.
.SS "Author"
.sp
Philip Hazel
.br
Retired from University Computing Service
.br
Cambridge, England.
.SS "Revision"
.sp
Last updated: 14 October 2025
.br
Copyright \(co 1997\-2024 University of Cambridge.