'\" t
.\"     Title: pcre2_set_max_pattern_length
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 05 October 2016
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SET_MAX_PATTERN_LENGTH" "3" "05 October 2016" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_set_max_pattern_length \- set the maximum length of a pattern
.SH "SYNOPSIS"
.sp
.nf
.fam C
#include <pcre2.h>

int pcre2_set_max_pattern_length(pcre2_compile_context *ccontext,
                                 PCRE2_SIZE length);
.fam
.fi
.SH "DESCRIPTION"
.sp
This function sets, in a compile context, the maximum text length (in code
units) of the pattern that can be compiled. The result is always zero. If a
longer pattern is passed to \f(CRpcre2_compile()\fP there is an immediate error
return. The default is effectively unlimited, being the largest value a
PCRE2_SIZE variable can hold. Setting this value makes the limit unlimited.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.