'\" t
.\"     Title: pcre2_set_optimize
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 22 September 2024
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_SET_OPTIMIZE" "3" "22 September 2024" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_set_optimize \- set an optimization directive
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint\fP pcre2_set_optimize(\fBpcre2_compile_context\fP *\fIccontext\fP,
                       \fBuint32_t\fP \fIdirective\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function controls which performance optimizations will be applied
by pcre2_compile(). It can be called multiple times with the same compile
context; the effects are cumulative, with the effects of later calls taking
precedence over earlier ones.
.sp
The result is zero for success, \fBPCRE2_ERROR_NULL\fP if \fIccontext\fP is \f(CRNULL\fP,
or \fBPCRE2_ERROR_BADOPTION\fP if \fIdirective\fP is unknown. The latter could be
useful to detect if a certain optimization is available.
.sp
The list of possible values for the \fIdirective\fP parameter are:
.sp
.RS 4
.PD 0
.TP 24
\fBPCRE2_OPTIMIZATION_FULL\fP
.ad l
Enable all optimizations (default)
.TP 24
\fBPCRE2_OPTIMIZATION_NONE\fP
.ad l
Disable all optimizations
.TP 24
\fBPCRE2_AUTO_POSSESS\fP
.ad l
Enable auto\-possessification
.TP 24
\fBPCRE2_AUTO_POSSESS_OFF\fP
.ad l
Disable auto\-possessification
.TP 24
\fBPCRE2_DOTSTAR_ANCHOR\fP
.ad l
Enable implicit dotstar anchoring
.TP 24
\fBPCRE2_DOTSTAR_ANCHOR_OFF\fP
.ad l
Disable implicit dotstar anchoring
.TP 24
\fBPCRE2_START_OPTIMIZE\fP
.ad l
Enable start\-up optimizations at match time
.TP 24
\fBPCRE2_START_OPTIMIZE_OFF\fP
.ad l
Disable start\-up optimizations at match time
.PD
.RE
.PP
.ad l
.sp
There is a complete description of the PCRE2 native API, including detailed
descriptions of \fIdirective\fP parameter values in the
\f(CRpcre2api\fP
page.