'\" t
.\"     Title: pcre2_code_copy_with_tables
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 16 January 2017
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_CODE_COPY_WITH_TABLES" "3" "16 January 2017" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_code_copy_with_tables \- copy a compiled pattern and its character tables
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBpcre2_code\fP *pcre2_code_copy_with_tables(\fBconst\fP \fBpcre2_code\fP *\fIcode\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function makes a copy of the memory used for a compiled pattern, excluding
any memory used by the JIT compiler. Without a subsequent call to
pcre2_jit_compile(), the copy can be used only for non\-JIT matching.
Unlike pcre2_code_copy(), a separate copy of the character tables is also
made, with the new code pointing to it. This memory will be automatically freed
when pcre2_code_free() is called. The yield of the function is \f(CRNULL\fP if
\fIcode\fP is \f(CRNULL\fP or if sufficient memory cannot be obtained.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.