'\" t
.\"     Title: pcre2_get_mark
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.20
.\"      Date: 13 January 2018
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_GET_MARK" "3" "13 January 2018" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_get_mark \- get a (*MARK) name
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBPCRE2_SPTR\fP pcre2_get_mark(\fBpcre2_match_data\fP *\fImatch_data\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
After a call of pcre2_match() that was passed the match block that is
this function\(cqs argument, this function returns a pointer to the last \f(CR(*MARK)\fP,
\f(CR(*PRUNE)\fP, or \f(CR(*THEN)\fP name that was encountered during the matching process. The
name is zero\-terminated, and is within the compiled pattern. The length of the
name is in the preceding code unit. If no name is available, \f(CRNULL\fP is returned.
.sp
After a successful match, the name that is returned is the last one on the
matching path. After a failed match or a partial match, the last encountered
name is returned.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.