'\" t
.\"     Title: pcre2_dfa_match
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 31 August 2021
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_DFA_MATCH" "3" "31 August 2021" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_dfa_match \- match a compiled pattern to a subject string using the alternative matching algorithm (DFA algorithm; not Perl compatible)
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint\fP pcre2_dfa_match(\fBconst\fP \fBpcre2_code\fP *\fIcode\fP, \fBPCRE2_SPTR\fP \fIsubject\fP,
                    \fBPCRE2_SIZE\fP \fIlength\fP, \fBPCRE2_SIZE\fP \fIstart_offset\fP,
                    \fBuint32_t\fP \fIoptions\fP, \fBpcre2_match_data\fP *\fImatch_data\fP,
                    \fBpcre2_match_context\fP *\fImcontext\fP, \fBint\fP *\fIworkspace\fP,
                    \fBPCRE2_SIZE\fP \fIwscount\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function matches a compiled regular expression against a given subject
string, using an alternative matching algorithm that scans the subject string
just once (except when processing lookaround assertions). This function is
\fInot\fP Perl\-compatible (the Perl\-compatible matching function is
pcre2_match()). The arguments for this function are:
.sp
.RS 4
.PD 0
.TP 13
\fIcode\fP
.ad l
Points to the compiled pattern
.TP 13
\fIsubject\fP
.ad l
Points to the subject string
.TP 13
\fIlength\fP
.ad l
Length of the subject string
.TP 13
\fIstart_offset\fP
.ad l
Offset in the subject at which to start matching
.TP 13
\fIoptions\fP
.ad l
Option bits
.TP 13
\fImatch_data\fP
.ad l
Points to a match data block, for results
.TP 13
\fImcontext\fP
.ad l
Points to a match context, or is \fBNULL\fP
.TP 13
\fIworkspace\fP
.ad l
Points to a vector of ints used as working space
.TP 13
\fIwscount\fP
.ad l
Number of elements in the vector
.PD
.RE
.PP
.ad l
.sp
The size of output vector needed to contain all the results depends on the
number of simultaneous matches, not on the number of parentheses in the
pattern. Using pcre2_match_data_create_from_pattern() to create the match
data block is therefore not advisable when using this function.
.sp
A match context is needed only if you want to set up a callout function or
specify the heap limit or the match or the recursion depth limits. The
\fIlength\fP and \fIstart_offset\fP values are code units, not characters. The
options are:
.sp
.RS 4
.PD 0
.TP 23
\fBPCRE2_ANCHORED\fP
.ad l
Match only at the first position
.TP 23
\fBPCRE2_COPY_MATCHED_SUBJECT\fP
.ad l
On success, make a private subject copy
.TP 23
\fBPCRE2_ENDANCHORED\fP
.ad l
Pattern can match only at end of subject
.TP 23
\fBPCRE2_NOTBOL\fP
.ad l
Subject is not the beginning of a line
.TP 23
\fBPCRE2_NOTEOL\fP
.ad l
Subject is not the end of a line
.TP 23
\fBPCRE2_NOTEMPTY\fP
.ad l
An empty string is not a valid match
.TP 23
\fBPCRE2_NOTEMPTY_ATSTART\fP
.ad l
An empty string at the start of the subject
is not a valid match
.TP 23
\fBPCRE2_NO_UTF_CHECK\fP
.ad l
Do not check the subject for UTF
validity (only relevant if \fBPCRE2_UTF\fP
was set at compile time)
.TP 23
\fBPCRE2_PARTIAL_HARD\fP
.ad l
Return \fBPCRE2_ERROR_PARTIAL\fP for a partial
match even if there is a full match
.TP 23
\fBPCRE2_PARTIAL_SOFT\fP
.ad l
Return \fBPCRE2_ERROR_PARTIAL\fP for a partial
match if no full matches are found
.TP 23
\fBPCRE2_DFA_RESTART\fP
.ad l
Restart after a partial match
.TP 23
\fBPCRE2_DFA_SHORTEST\fP
.ad l
Return only the shortest match
.PD
.RE
.PP
.ad l
.sp
There are restrictions on what may appear in a pattern when using this matching
function. Details are given in the
\f(CRpcre2matching\fP
documentation. For details of partial matching, see the
\f(CRpcre2partial\fP
page. There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.