'\" t
.\"     Title: pcre2_config
.\"    Author: [see the "AUTHOR(S)" section]
.\" Generator: Asciidoctor 2.0.26
.\"      Date: 03 September 2025
.\"    Manual: PCRE2
.\"    Source: PCRE2 10.49-DEV
.\"  Language: English
.\"
.TH "PCRE2_CONFIG" "3" "03 September 2025" "PCRE2 10.49\-DEV" "PCRE2"
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.SH "NAME"
pcre2_config \- show build\-time related configuration options
.SH "SYNOPSIS"
.sp
.ss \n[.ss]
.nf
.fam C
\fB\&#include\fP \fB<pcre2.h>\fP

\fBint\fP pcre2_config(\fBuint32_t\fP \fIwhat\fP, \fBvoid\fP *\fIwhere\fP);
.fam
.fi
.ss \n[.ss] 0
.SH "DESCRIPTION"
.sp
This function makes it possible for a client program to find out which optional
features are available in the version of the PCRE2 library it is using. The
arguments are as follows:
.sp
.RS 4
.PD 0
.TP 7
\fIwhat\fP
.ad l
A code specifying what information is required
.TP 7
\fIwhere\fP
.ad l
Points to where to put the information
.PD
.RE
.PP
.ad l
.sp
If \fIwhere\fP is \fBNULL\fP, the function returns the amount of memory needed for
the requested information. When the information is a string, the value is in
code units; for other types of data it is in bytes.
.sp
If \fIwhere\fP is not \fBNULL\fP, for \fBPCRE2_CONFIG_JITTARGET\fP,
\fBPCRE2_CONFIG_UNICODE_VERSION\fP, and \fBPCRE2_CONFIG_VERSION\fP it must point to a
buffer that is large enough to hold the string. For all other codes it must
point to a \fBuint32_t\fP integer variable. The available codes are:
.sp
.RS 4
.PD
.TP 26
\fBPCRE2_CONFIG_BSR\fP
.ad l
Indicates what \f(CR\(rsR\fP matches by default:
.RS 26
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBPCRE2_BSR_UNICODE\fP
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBPCRE2_BSR_ANYCRLF\fP
.RE
.RE
.TP 26
\fBPCRE2_CONFIG_COMPILED_WIDTHS\fP
.ad l
Which of 8/16/32 support was compiled
.TP 26
\fBPCRE2_CONFIG_DEPTHLIMIT\fP
.ad l
Default backtracking depth limit
.TP 26
\fBPCRE2_CONFIG_EFFECTIVE_LINKSIZE\fP
.ad l
How many bytes are used for link size
.TP 26
\fBPCRE2_CONFIG_HEAPLIMIT\fP
.ad l
Default heap memory limit
.TP 26
\fBPCRE2_CONFIG_JIT\fP
.ad l
Availability of just\-in\-time compiler
support (1=yes 0=no)
.TP 26
\fBPCRE2_CONFIG_JITTARGET\fP
.ad l
Information (a string) about the target
architecture for the JIT compiler
.TP 26
\fBPCRE2_CONFIG_LINKSIZE\fP
.ad l
Configured internal link size (2, 3, 4)
.TP 26
\fBPCRE2_CONFIG_MATCHLIMIT\fP
.ad l
Default internal resource limit
.TP 26
\fBPCRE2_CONFIG_NEVER_BACKSLASH_C\fP
.ad l
Whether or not \f(CR\(rsC\fP is disabled
.TP 26
\fBPCRE2_CONFIG_NEWLINE\fP
.ad l
Code for the default newline sequence:
.RS 26
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBPCRE2_NEWLINE_CR\fP
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBPCRE2_NEWLINE_LF\fP
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBPCRE2_NEWLINE_CRLF\fP
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBPCRE2_NEWLINE_ANY\fP
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBPCRE2_NEWLINE_ANYCRLF\fP
.RE
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.  sp -1
.  IP \(bu 2.3
.\}
\fBPCRE2_NEWLINE_NUL\fP
.RE
.RE
.TP 26
\fBPCRE2_CONFIG_PARENSLIMIT\fP
.ad l
Default parentheses nesting limit
.TP 26
\fBPCRE2_CONFIG_RECURSIONLIMIT\fP
.ad l
Obsolete: use \fBPCRE2_CONFIG_DEPTHLIMIT\fP
.TP 26
\fBPCRE2_CONFIG_STACKRECURSE\fP
.ad l
Obsolete: always returns 0
.TP 26
\fBPCRE2_CONFIG_UNICODE\fP
.ad l
Availability of Unicode support
(1=yes 0=no)
.TP 26
\fBPCRE2_CONFIG_UNICODE_VERSION\fP
.ad l
The Unicode version (a string)
.TP 26
\fBPCRE2_CONFIG_VERSION\fP
.ad l
The PCRE2 version (a string)
.PD
.RE
.PP
.ad l
.sp
The function yields a non\-negative value on success or the negative value
\fBPCRE2_ERROR_BADOPTION\fP otherwise. This is also the result for the
\fBPCRE2_CONFIG_JITTARGET\fP code if JIT support is not available. When a string is
requested, the function returns the number of code units used, including the
terminating zero.
.sp
There is a complete description of the PCRE2 native API in the
\f(CRpcre2api\fP
page and a description of the POSIX API in the
\f(CRpcre2posix\fP
page.